
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Proponente: 'Proponente',
  Projeto: 'Projeto',
  PlanoTrabalho: 'PlanoTrabalho',
  CronogramaItem: 'CronogramaItem',
  EquipeItem: 'EquipeItem',
  Participante: 'Participante',
  Responsabilidade: 'Responsabilidade',
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  OtpCode: 'OtpCode'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ProponenteScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  email: 'email',
  instituicao: 'instituicao',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProponenteScalarFieldEnum = (typeof ProponenteScalarFieldEnum)[keyof typeof ProponenteScalarFieldEnum]


export const ProjetoScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  objetivos: 'objetivos',
  justificativa: 'justificativa',
  abrangencia: 'abrangencia',
  proponenteId: 'proponenteId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjetoScalarFieldEnum = (typeof ProjetoScalarFieldEnum)[keyof typeof ProjetoScalarFieldEnum]


export const PlanoTrabalhoScalarFieldEnum = {
  id: 'id',
  projetoId: 'projetoId',
  objeto: 'objeto',
  diagnostico: 'diagnostico',
  abrangenciaPlano: 'abrangenciaPlano',
  justificativaPlano: 'justificativaPlano',
  objetivoGeral: 'objetivoGeral',
  objetivosEspecificos: 'objetivosEspecificos',
  metodologia: 'metodologia',
  unidadeResponsavel: 'unidadeResponsavel',
  gestorICT: 'gestorICT',
  gestorParceiro: 'gestorParceiro',
  acompanhamento: 'acompanhamento',
  resultadosEsperados: 'resultadosEsperados',
  vigenciaInicio: 'vigenciaInicio',
  vigenciaFim: 'vigenciaFim',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlanoTrabalhoScalarFieldEnum = (typeof PlanoTrabalhoScalarFieldEnum)[keyof typeof PlanoTrabalhoScalarFieldEnum]


export const CronogramaItemScalarFieldEnum = {
  id: 'id',
  planoTrabalhoId: 'planoTrabalhoId',
  eixoMeta: 'eixoMeta',
  acaoEtapa: 'acaoEtapa',
  indicador: 'indicador',
  responsavel: 'responsavel',
  inicio: 'inicio',
  termino: 'termino',
  situacao: 'situacao'
} as const

export type CronogramaItemScalarFieldEnum = (typeof CronogramaItemScalarFieldEnum)[keyof typeof CronogramaItemScalarFieldEnum]


export const EquipeItemScalarFieldEnum = {
  id: 'id',
  planoTrabalhoId: 'planoTrabalhoId',
  nome: 'nome',
  titulacaoArea: 'titulacaoArea',
  instituicao: 'instituicao',
  funcao: 'funcao',
  cargaHorariaSemanal: 'cargaHorariaSemanal'
} as const

export type EquipeItemScalarFieldEnum = (typeof EquipeItemScalarFieldEnum)[keyof typeof EquipeItemScalarFieldEnum]


export const ParticipanteScalarFieldEnum = {
  id: 'id',
  planoTrabalhoId: 'planoTrabalhoId',
  orgaoEntidade: 'orgaoEntidade',
  cnpj: 'cnpj',
  esfera: 'esfera',
  endereco: 'endereco',
  autoridadeNome: 'autoridadeNome',
  autoridadeCargo: 'autoridadeCargo',
  autoridadeDoc: 'autoridadeDoc',
  contato: 'contato'
} as const

export type ParticipanteScalarFieldEnum = (typeof ParticipanteScalarFieldEnum)[keyof typeof ParticipanteScalarFieldEnum]


export const ResponsabilidadeScalarFieldEnum = {
  id: 'id',
  planoTrabalhoId: 'planoTrabalhoId',
  participanteId: 'participanteId',
  descricao: 'descricao'
} as const

export type ResponsabilidadeScalarFieldEnum = (typeof ResponsabilidadeScalarFieldEnum)[keyof typeof ResponsabilidadeScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
} as const

export type VerificationTokenScalarFieldEnum = (typeof VerificationTokenScalarFieldEnum)[keyof typeof VerificationTokenScalarFieldEnum]


export const OtpCodeScalarFieldEnum = {
  id: 'id',
  email: 'email',
  codeHash: 'codeHash',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  sentAt: 'sentAt',
  attempts: 'attempts'
} as const

export type OtpCodeScalarFieldEnum = (typeof OtpCodeScalarFieldEnum)[keyof typeof OtpCodeScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

