
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Proponente
 * 
 */
export type Proponente = Prisma.ProponenteModel
/**
 * Model Projeto
 * 
 */
export type Projeto = Prisma.ProjetoModel
/**
 * Model PlanoTrabalho
 * 
 */
export type PlanoTrabalho = Prisma.PlanoTrabalhoModel
/**
 * Model CronogramaItem
 * 
 */
export type CronogramaItem = Prisma.CronogramaItemModel
/**
 * Model EquipeItem
 * 
 */
export type EquipeItem = Prisma.EquipeItemModel
/**
 * Model Participante
 * 
 */
export type Participante = Prisma.ParticipanteModel
/**
 * Model Responsabilidade
 * 
 */
export type Responsabilidade = Prisma.ResponsabilidadeModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model OtpCode
 * 
 */
export type OtpCode = Prisma.OtpCodeModel
