
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const SituacaoCronograma = {
  PLANEJADO: 'PLANEJADO',
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  CONCLUIDO: 'CONCLUIDO',
  ATRASADO: 'ATRASADO',
  SUSPENSO: 'SUSPENSO'
} as const

export type SituacaoCronograma = (typeof SituacaoCronograma)[keyof typeof SituacaoCronograma]


export const EsferaAdministrativa = {
  FEDERAL: 'FEDERAL',
  ESTADUAL: 'ESTADUAL',
  MUNICIPAL: 'MUNICIPAL',
  PRIVADO: 'PRIVADO',
  OUTRO: 'OUTRO'
} as const

export type EsferaAdministrativa = (typeof EsferaAdministrativa)[keyof typeof EsferaAdministrativa]


export const SetorAprovacao = {
  TECNICO: 'TECNICO',
  JURIDICO: 'JURIDICO',
  OUTRO: 'OUTRO'
} as const

export type SetorAprovacao = (typeof SetorAprovacao)[keyof typeof SetorAprovacao]
