
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ScheduleStatus = {
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  DELAYED: 'DELAYED',
  SUSPENDED: 'SUSPENDED'
} as const

export type ScheduleStatus = (typeof ScheduleStatus)[keyof typeof ScheduleStatus]


export const AdministrativeSphere = {
  FEDERAL: 'FEDERAL',
  STATE: 'STATE',
  MUNICIPAL: 'MUNICIPAL',
  PRIVATE: 'PRIVATE',
  OTHER: 'OTHER'
} as const

export type AdministrativeSphere = (typeof AdministrativeSphere)[keyof typeof AdministrativeSphere]


export const ApprovalSector = {
  TECHNICAL: 'TECHNICAL',
  LEGAL: 'LEGAL',
  OTHER: 'OTHER'
} as const

export type ApprovalSector = (typeof ApprovalSector)[keyof typeof ApprovalSector]
