
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CronogramaItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CronogramaItem
 * 
 */
export type CronogramaItemModel = runtime.Types.Result.DefaultSelection<Prisma.$CronogramaItemPayload>

export type AggregateCronogramaItem = {
  _count: CronogramaItemCountAggregateOutputType | null
  _avg: CronogramaItemAvgAggregateOutputType | null
  _sum: CronogramaItemSumAggregateOutputType | null
  _min: CronogramaItemMinAggregateOutputType | null
  _max: CronogramaItemMaxAggregateOutputType | null
}

export type CronogramaItemAvgAggregateOutputType = {
  id: number | null
  planoTrabalhoId: number | null
}

export type CronogramaItemSumAggregateOutputType = {
  id: number | null
  planoTrabalhoId: number | null
}

export type CronogramaItemMinAggregateOutputType = {
  id: number | null
  planoTrabalhoId: number | null
  eixoMeta: string | null
  acaoEtapa: string | null
  indicador: string | null
  responsavel: string | null
  inicio: Date | null
  termino: Date | null
  situacao: $Enums.SituacaoCronograma | null
}

export type CronogramaItemMaxAggregateOutputType = {
  id: number | null
  planoTrabalhoId: number | null
  eixoMeta: string | null
  acaoEtapa: string | null
  indicador: string | null
  responsavel: string | null
  inicio: Date | null
  termino: Date | null
  situacao: $Enums.SituacaoCronograma | null
}

export type CronogramaItemCountAggregateOutputType = {
  id: number
  planoTrabalhoId: number
  eixoMeta: number
  acaoEtapa: number
  indicador: number
  responsavel: number
  inicio: number
  termino: number
  situacao: number
  _all: number
}


export type CronogramaItemAvgAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
}

export type CronogramaItemSumAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
}

export type CronogramaItemMinAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
  eixoMeta?: true
  acaoEtapa?: true
  indicador?: true
  responsavel?: true
  inicio?: true
  termino?: true
  situacao?: true
}

export type CronogramaItemMaxAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
  eixoMeta?: true
  acaoEtapa?: true
  indicador?: true
  responsavel?: true
  inicio?: true
  termino?: true
  situacao?: true
}

export type CronogramaItemCountAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
  eixoMeta?: true
  acaoEtapa?: true
  indicador?: true
  responsavel?: true
  inicio?: true
  termino?: true
  situacao?: true
  _all?: true
}

export type CronogramaItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CronogramaItem to aggregate.
   */
  where?: Prisma.CronogramaItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CronogramaItems to fetch.
   */
  orderBy?: Prisma.CronogramaItemOrderByWithRelationInput | Prisma.CronogramaItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CronogramaItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CronogramaItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CronogramaItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CronogramaItems
  **/
  _count?: true | CronogramaItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CronogramaItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CronogramaItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CronogramaItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CronogramaItemMaxAggregateInputType
}

export type GetCronogramaItemAggregateType<T extends CronogramaItemAggregateArgs> = {
      [P in keyof T & keyof AggregateCronogramaItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCronogramaItem[P]>
    : Prisma.GetScalarType<T[P], AggregateCronogramaItem[P]>
}




export type CronogramaItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CronogramaItemWhereInput
  orderBy?: Prisma.CronogramaItemOrderByWithAggregationInput | Prisma.CronogramaItemOrderByWithAggregationInput[]
  by: Prisma.CronogramaItemScalarFieldEnum[] | Prisma.CronogramaItemScalarFieldEnum
  having?: Prisma.CronogramaItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CronogramaItemCountAggregateInputType | true
  _avg?: CronogramaItemAvgAggregateInputType
  _sum?: CronogramaItemSumAggregateInputType
  _min?: CronogramaItemMinAggregateInputType
  _max?: CronogramaItemMaxAggregateInputType
}

export type CronogramaItemGroupByOutputType = {
  id: number
  planoTrabalhoId: number
  eixoMeta: string
  acaoEtapa: string
  indicador: string
  responsavel: string
  inicio: Date
  termino: Date
  situacao: $Enums.SituacaoCronograma
  _count: CronogramaItemCountAggregateOutputType | null
  _avg: CronogramaItemAvgAggregateOutputType | null
  _sum: CronogramaItemSumAggregateOutputType | null
  _min: CronogramaItemMinAggregateOutputType | null
  _max: CronogramaItemMaxAggregateOutputType | null
}

type GetCronogramaItemGroupByPayload<T extends CronogramaItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CronogramaItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CronogramaItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CronogramaItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CronogramaItemGroupByOutputType[P]>
      }
    >
  >



export type CronogramaItemWhereInput = {
  AND?: Prisma.CronogramaItemWhereInput | Prisma.CronogramaItemWhereInput[]
  OR?: Prisma.CronogramaItemWhereInput[]
  NOT?: Prisma.CronogramaItemWhereInput | Prisma.CronogramaItemWhereInput[]
  id?: Prisma.IntFilter<"CronogramaItem"> | number
  planoTrabalhoId?: Prisma.IntFilter<"CronogramaItem"> | number
  eixoMeta?: Prisma.StringFilter<"CronogramaItem"> | string
  acaoEtapa?: Prisma.StringFilter<"CronogramaItem"> | string
  indicador?: Prisma.StringFilter<"CronogramaItem"> | string
  responsavel?: Prisma.StringFilter<"CronogramaItem"> | string
  inicio?: Prisma.DateTimeFilter<"CronogramaItem"> | Date | string
  termino?: Prisma.DateTimeFilter<"CronogramaItem"> | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFilter<"CronogramaItem"> | $Enums.SituacaoCronograma
  planoTrabalho?: Prisma.XOR<Prisma.PlanoTrabalhoScalarRelationFilter, Prisma.PlanoTrabalhoWhereInput>
}

export type CronogramaItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  eixoMeta?: Prisma.SortOrder
  acaoEtapa?: Prisma.SortOrder
  indicador?: Prisma.SortOrder
  responsavel?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  termino?: Prisma.SortOrder
  situacao?: Prisma.SortOrder
  planoTrabalho?: Prisma.PlanoTrabalhoOrderByWithRelationInput
}

export type CronogramaItemWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.CronogramaItemWhereInput | Prisma.CronogramaItemWhereInput[]
  OR?: Prisma.CronogramaItemWhereInput[]
  NOT?: Prisma.CronogramaItemWhereInput | Prisma.CronogramaItemWhereInput[]
  planoTrabalhoId?: Prisma.IntFilter<"CronogramaItem"> | number
  eixoMeta?: Prisma.StringFilter<"CronogramaItem"> | string
  acaoEtapa?: Prisma.StringFilter<"CronogramaItem"> | string
  indicador?: Prisma.StringFilter<"CronogramaItem"> | string
  responsavel?: Prisma.StringFilter<"CronogramaItem"> | string
  inicio?: Prisma.DateTimeFilter<"CronogramaItem"> | Date | string
  termino?: Prisma.DateTimeFilter<"CronogramaItem"> | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFilter<"CronogramaItem"> | $Enums.SituacaoCronograma
  planoTrabalho?: Prisma.XOR<Prisma.PlanoTrabalhoScalarRelationFilter, Prisma.PlanoTrabalhoWhereInput>
}, "id">

export type CronogramaItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  eixoMeta?: Prisma.SortOrder
  acaoEtapa?: Prisma.SortOrder
  indicador?: Prisma.SortOrder
  responsavel?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  termino?: Prisma.SortOrder
  situacao?: Prisma.SortOrder
  _count?: Prisma.CronogramaItemCountOrderByAggregateInput
  _avg?: Prisma.CronogramaItemAvgOrderByAggregateInput
  _max?: Prisma.CronogramaItemMaxOrderByAggregateInput
  _min?: Prisma.CronogramaItemMinOrderByAggregateInput
  _sum?: Prisma.CronogramaItemSumOrderByAggregateInput
}

export type CronogramaItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.CronogramaItemScalarWhereWithAggregatesInput | Prisma.CronogramaItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.CronogramaItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CronogramaItemScalarWhereWithAggregatesInput | Prisma.CronogramaItemScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"CronogramaItem"> | number
  planoTrabalhoId?: Prisma.IntWithAggregatesFilter<"CronogramaItem"> | number
  eixoMeta?: Prisma.StringWithAggregatesFilter<"CronogramaItem"> | string
  acaoEtapa?: Prisma.StringWithAggregatesFilter<"CronogramaItem"> | string
  indicador?: Prisma.StringWithAggregatesFilter<"CronogramaItem"> | string
  responsavel?: Prisma.StringWithAggregatesFilter<"CronogramaItem"> | string
  inicio?: Prisma.DateTimeWithAggregatesFilter<"CronogramaItem"> | Date | string
  termino?: Prisma.DateTimeWithAggregatesFilter<"CronogramaItem"> | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaWithAggregatesFilter<"CronogramaItem"> | $Enums.SituacaoCronograma
}

export type CronogramaItemCreateInput = {
  eixoMeta: string
  acaoEtapa: string
  indicador: string
  responsavel: string
  inicio: Date | string
  termino: Date | string
  situacao?: $Enums.SituacaoCronograma
  planoTrabalho: Prisma.PlanoTrabalhoCreateNestedOneWithoutCronogramaInput
}

export type CronogramaItemUncheckedCreateInput = {
  id?: number
  planoTrabalhoId: number
  eixoMeta: string
  acaoEtapa: string
  indicador: string
  responsavel: string
  inicio: Date | string
  termino: Date | string
  situacao?: $Enums.SituacaoCronograma
}

export type CronogramaItemUpdateInput = {
  eixoMeta?: Prisma.StringFieldUpdateOperationsInput | string
  acaoEtapa?: Prisma.StringFieldUpdateOperationsInput | string
  indicador?: Prisma.StringFieldUpdateOperationsInput | string
  responsavel?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  termino?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFieldUpdateOperationsInput | $Enums.SituacaoCronograma
  planoTrabalho?: Prisma.PlanoTrabalhoUpdateOneRequiredWithoutCronogramaNestedInput
}

export type CronogramaItemUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  planoTrabalhoId?: Prisma.IntFieldUpdateOperationsInput | number
  eixoMeta?: Prisma.StringFieldUpdateOperationsInput | string
  acaoEtapa?: Prisma.StringFieldUpdateOperationsInput | string
  indicador?: Prisma.StringFieldUpdateOperationsInput | string
  responsavel?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  termino?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFieldUpdateOperationsInput | $Enums.SituacaoCronograma
}

export type CronogramaItemCreateManyInput = {
  id?: number
  planoTrabalhoId: number
  eixoMeta: string
  acaoEtapa: string
  indicador: string
  responsavel: string
  inicio: Date | string
  termino: Date | string
  situacao?: $Enums.SituacaoCronograma
}

export type CronogramaItemUpdateManyMutationInput = {
  eixoMeta?: Prisma.StringFieldUpdateOperationsInput | string
  acaoEtapa?: Prisma.StringFieldUpdateOperationsInput | string
  indicador?: Prisma.StringFieldUpdateOperationsInput | string
  responsavel?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  termino?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFieldUpdateOperationsInput | $Enums.SituacaoCronograma
}

export type CronogramaItemUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  planoTrabalhoId?: Prisma.IntFieldUpdateOperationsInput | number
  eixoMeta?: Prisma.StringFieldUpdateOperationsInput | string
  acaoEtapa?: Prisma.StringFieldUpdateOperationsInput | string
  indicador?: Prisma.StringFieldUpdateOperationsInput | string
  responsavel?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  termino?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFieldUpdateOperationsInput | $Enums.SituacaoCronograma
}

export type CronogramaItemListRelationFilter = {
  every?: Prisma.CronogramaItemWhereInput
  some?: Prisma.CronogramaItemWhereInput
  none?: Prisma.CronogramaItemWhereInput
}

export type CronogramaItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CronogramaItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  eixoMeta?: Prisma.SortOrder
  acaoEtapa?: Prisma.SortOrder
  indicador?: Prisma.SortOrder
  responsavel?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  termino?: Prisma.SortOrder
  situacao?: Prisma.SortOrder
}

export type CronogramaItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
}

export type CronogramaItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  eixoMeta?: Prisma.SortOrder
  acaoEtapa?: Prisma.SortOrder
  indicador?: Prisma.SortOrder
  responsavel?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  termino?: Prisma.SortOrder
  situacao?: Prisma.SortOrder
}

export type CronogramaItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  eixoMeta?: Prisma.SortOrder
  acaoEtapa?: Prisma.SortOrder
  indicador?: Prisma.SortOrder
  responsavel?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  termino?: Prisma.SortOrder
  situacao?: Prisma.SortOrder
}

export type CronogramaItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
}

export type CronogramaItemCreateNestedManyWithoutPlanoTrabalhoInput = {
  create?: Prisma.XOR<Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput, Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput> | Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput[] | Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput[]
  connectOrCreate?: Prisma.CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput | Prisma.CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput[]
  createMany?: Prisma.CronogramaItemCreateManyPlanoTrabalhoInputEnvelope
  connect?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
}

export type CronogramaItemUncheckedCreateNestedManyWithoutPlanoTrabalhoInput = {
  create?: Prisma.XOR<Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput, Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput> | Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput[] | Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput[]
  connectOrCreate?: Prisma.CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput | Prisma.CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput[]
  createMany?: Prisma.CronogramaItemCreateManyPlanoTrabalhoInputEnvelope
  connect?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
}

export type CronogramaItemUpdateManyWithoutPlanoTrabalhoNestedInput = {
  create?: Prisma.XOR<Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput, Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput> | Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput[] | Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput[]
  connectOrCreate?: Prisma.CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput | Prisma.CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput[]
  upsert?: Prisma.CronogramaItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput | Prisma.CronogramaItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput[]
  createMany?: Prisma.CronogramaItemCreateManyPlanoTrabalhoInputEnvelope
  set?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
  disconnect?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
  delete?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
  connect?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
  update?: Prisma.CronogramaItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput | Prisma.CronogramaItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput[]
  updateMany?: Prisma.CronogramaItemUpdateManyWithWhereWithoutPlanoTrabalhoInput | Prisma.CronogramaItemUpdateManyWithWhereWithoutPlanoTrabalhoInput[]
  deleteMany?: Prisma.CronogramaItemScalarWhereInput | Prisma.CronogramaItemScalarWhereInput[]
}

export type CronogramaItemUncheckedUpdateManyWithoutPlanoTrabalhoNestedInput = {
  create?: Prisma.XOR<Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput, Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput> | Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput[] | Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput[]
  connectOrCreate?: Prisma.CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput | Prisma.CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput[]
  upsert?: Prisma.CronogramaItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput | Prisma.CronogramaItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput[]
  createMany?: Prisma.CronogramaItemCreateManyPlanoTrabalhoInputEnvelope
  set?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
  disconnect?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
  delete?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
  connect?: Prisma.CronogramaItemWhereUniqueInput | Prisma.CronogramaItemWhereUniqueInput[]
  update?: Prisma.CronogramaItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput | Prisma.CronogramaItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput[]
  updateMany?: Prisma.CronogramaItemUpdateManyWithWhereWithoutPlanoTrabalhoInput | Prisma.CronogramaItemUpdateManyWithWhereWithoutPlanoTrabalhoInput[]
  deleteMany?: Prisma.CronogramaItemScalarWhereInput | Prisma.CronogramaItemScalarWhereInput[]
}

export type EnumSituacaoCronogramaFieldUpdateOperationsInput = {
  set?: $Enums.SituacaoCronograma
}

export type CronogramaItemCreateWithoutPlanoTrabalhoInput = {
  eixoMeta: string
  acaoEtapa: string
  indicador: string
  responsavel: string
  inicio: Date | string
  termino: Date | string
  situacao?: $Enums.SituacaoCronograma
}

export type CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput = {
  id?: number
  eixoMeta: string
  acaoEtapa: string
  indicador: string
  responsavel: string
  inicio: Date | string
  termino: Date | string
  situacao?: $Enums.SituacaoCronograma
}

export type CronogramaItemCreateOrConnectWithoutPlanoTrabalhoInput = {
  where: Prisma.CronogramaItemWhereUniqueInput
  create: Prisma.XOR<Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput, Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput>
}

export type CronogramaItemCreateManyPlanoTrabalhoInputEnvelope = {
  data: Prisma.CronogramaItemCreateManyPlanoTrabalhoInput | Prisma.CronogramaItemCreateManyPlanoTrabalhoInput[]
  skipDuplicates?: boolean
}

export type CronogramaItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput = {
  where: Prisma.CronogramaItemWhereUniqueInput
  update: Prisma.XOR<Prisma.CronogramaItemUpdateWithoutPlanoTrabalhoInput, Prisma.CronogramaItemUncheckedUpdateWithoutPlanoTrabalhoInput>
  create: Prisma.XOR<Prisma.CronogramaItemCreateWithoutPlanoTrabalhoInput, Prisma.CronogramaItemUncheckedCreateWithoutPlanoTrabalhoInput>
}

export type CronogramaItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput = {
  where: Prisma.CronogramaItemWhereUniqueInput
  data: Prisma.XOR<Prisma.CronogramaItemUpdateWithoutPlanoTrabalhoInput, Prisma.CronogramaItemUncheckedUpdateWithoutPlanoTrabalhoInput>
}

export type CronogramaItemUpdateManyWithWhereWithoutPlanoTrabalhoInput = {
  where: Prisma.CronogramaItemScalarWhereInput
  data: Prisma.XOR<Prisma.CronogramaItemUpdateManyMutationInput, Prisma.CronogramaItemUncheckedUpdateManyWithoutPlanoTrabalhoInput>
}

export type CronogramaItemScalarWhereInput = {
  AND?: Prisma.CronogramaItemScalarWhereInput | Prisma.CronogramaItemScalarWhereInput[]
  OR?: Prisma.CronogramaItemScalarWhereInput[]
  NOT?: Prisma.CronogramaItemScalarWhereInput | Prisma.CronogramaItemScalarWhereInput[]
  id?: Prisma.IntFilter<"CronogramaItem"> | number
  planoTrabalhoId?: Prisma.IntFilter<"CronogramaItem"> | number
  eixoMeta?: Prisma.StringFilter<"CronogramaItem"> | string
  acaoEtapa?: Prisma.StringFilter<"CronogramaItem"> | string
  indicador?: Prisma.StringFilter<"CronogramaItem"> | string
  responsavel?: Prisma.StringFilter<"CronogramaItem"> | string
  inicio?: Prisma.DateTimeFilter<"CronogramaItem"> | Date | string
  termino?: Prisma.DateTimeFilter<"CronogramaItem"> | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFilter<"CronogramaItem"> | $Enums.SituacaoCronograma
}

export type CronogramaItemCreateManyPlanoTrabalhoInput = {
  id?: number
  eixoMeta: string
  acaoEtapa: string
  indicador: string
  responsavel: string
  inicio: Date | string
  termino: Date | string
  situacao?: $Enums.SituacaoCronograma
}

export type CronogramaItemUpdateWithoutPlanoTrabalhoInput = {
  eixoMeta?: Prisma.StringFieldUpdateOperationsInput | string
  acaoEtapa?: Prisma.StringFieldUpdateOperationsInput | string
  indicador?: Prisma.StringFieldUpdateOperationsInput | string
  responsavel?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  termino?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFieldUpdateOperationsInput | $Enums.SituacaoCronograma
}

export type CronogramaItemUncheckedUpdateWithoutPlanoTrabalhoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  eixoMeta?: Prisma.StringFieldUpdateOperationsInput | string
  acaoEtapa?: Prisma.StringFieldUpdateOperationsInput | string
  indicador?: Prisma.StringFieldUpdateOperationsInput | string
  responsavel?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  termino?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFieldUpdateOperationsInput | $Enums.SituacaoCronograma
}

export type CronogramaItemUncheckedUpdateManyWithoutPlanoTrabalhoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  eixoMeta?: Prisma.StringFieldUpdateOperationsInput | string
  acaoEtapa?: Prisma.StringFieldUpdateOperationsInput | string
  indicador?: Prisma.StringFieldUpdateOperationsInput | string
  responsavel?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  termino?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  situacao?: Prisma.EnumSituacaoCronogramaFieldUpdateOperationsInput | $Enums.SituacaoCronograma
}



export type CronogramaItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  planoTrabalhoId?: boolean
  eixoMeta?: boolean
  acaoEtapa?: boolean
  indicador?: boolean
  responsavel?: boolean
  inicio?: boolean
  termino?: boolean
  situacao?: boolean
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cronogramaItem"]>

export type CronogramaItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  planoTrabalhoId?: boolean
  eixoMeta?: boolean
  acaoEtapa?: boolean
  indicador?: boolean
  responsavel?: boolean
  inicio?: boolean
  termino?: boolean
  situacao?: boolean
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cronogramaItem"]>

export type CronogramaItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  planoTrabalhoId?: boolean
  eixoMeta?: boolean
  acaoEtapa?: boolean
  indicador?: boolean
  responsavel?: boolean
  inicio?: boolean
  termino?: boolean
  situacao?: boolean
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cronogramaItem"]>

export type CronogramaItemSelectScalar = {
  id?: boolean
  planoTrabalhoId?: boolean
  eixoMeta?: boolean
  acaoEtapa?: boolean
  indicador?: boolean
  responsavel?: boolean
  inicio?: boolean
  termino?: boolean
  situacao?: boolean
}

export type CronogramaItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "planoTrabalhoId" | "eixoMeta" | "acaoEtapa" | "indicador" | "responsavel" | "inicio" | "termino" | "situacao", ExtArgs["result"]["cronogramaItem"]>
export type CronogramaItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}
export type CronogramaItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}
export type CronogramaItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}

export type $CronogramaItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CronogramaItem"
  objects: {
    planoTrabalho: Prisma.$PlanoTrabalhoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    planoTrabalhoId: number
    eixoMeta: string
    acaoEtapa: string
    indicador: string
    responsavel: string
    inicio: Date
    termino: Date
    situacao: $Enums.SituacaoCronograma
  }, ExtArgs["result"]["cronogramaItem"]>
  composites: {}
}

export type CronogramaItemGetPayload<S extends boolean | null | undefined | CronogramaItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload, S>

export type CronogramaItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CronogramaItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CronogramaItemCountAggregateInputType | true
  }

export interface CronogramaItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CronogramaItem'], meta: { name: 'CronogramaItem' } }
  /**
   * Find zero or one CronogramaItem that matches the filter.
   * @param {CronogramaItemFindUniqueArgs} args - Arguments to find a CronogramaItem
   * @example
   * // Get one CronogramaItem
   * const cronogramaItem = await prisma.cronogramaItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CronogramaItemFindUniqueArgs>(args: Prisma.SelectSubset<T, CronogramaItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CronogramaItemClient<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CronogramaItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CronogramaItemFindUniqueOrThrowArgs} args - Arguments to find a CronogramaItem
   * @example
   * // Get one CronogramaItem
   * const cronogramaItem = await prisma.cronogramaItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CronogramaItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CronogramaItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CronogramaItemClient<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CronogramaItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CronogramaItemFindFirstArgs} args - Arguments to find a CronogramaItem
   * @example
   * // Get one CronogramaItem
   * const cronogramaItem = await prisma.cronogramaItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CronogramaItemFindFirstArgs>(args?: Prisma.SelectSubset<T, CronogramaItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__CronogramaItemClient<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CronogramaItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CronogramaItemFindFirstOrThrowArgs} args - Arguments to find a CronogramaItem
   * @example
   * // Get one CronogramaItem
   * const cronogramaItem = await prisma.cronogramaItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CronogramaItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CronogramaItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CronogramaItemClient<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CronogramaItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CronogramaItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CronogramaItems
   * const cronogramaItems = await prisma.cronogramaItem.findMany()
   * 
   * // Get first 10 CronogramaItems
   * const cronogramaItems = await prisma.cronogramaItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cronogramaItemWithIdOnly = await prisma.cronogramaItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CronogramaItemFindManyArgs>(args?: Prisma.SelectSubset<T, CronogramaItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CronogramaItem.
   * @param {CronogramaItemCreateArgs} args - Arguments to create a CronogramaItem.
   * @example
   * // Create one CronogramaItem
   * const CronogramaItem = await prisma.cronogramaItem.create({
   *   data: {
   *     // ... data to create a CronogramaItem
   *   }
   * })
   * 
   */
  create<T extends CronogramaItemCreateArgs>(args: Prisma.SelectSubset<T, CronogramaItemCreateArgs<ExtArgs>>): Prisma.Prisma__CronogramaItemClient<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CronogramaItems.
   * @param {CronogramaItemCreateManyArgs} args - Arguments to create many CronogramaItems.
   * @example
   * // Create many CronogramaItems
   * const cronogramaItem = await prisma.cronogramaItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CronogramaItemCreateManyArgs>(args?: Prisma.SelectSubset<T, CronogramaItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CronogramaItems and returns the data saved in the database.
   * @param {CronogramaItemCreateManyAndReturnArgs} args - Arguments to create many CronogramaItems.
   * @example
   * // Create many CronogramaItems
   * const cronogramaItem = await prisma.cronogramaItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CronogramaItems and only return the `id`
   * const cronogramaItemWithIdOnly = await prisma.cronogramaItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CronogramaItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CronogramaItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CronogramaItem.
   * @param {CronogramaItemDeleteArgs} args - Arguments to delete one CronogramaItem.
   * @example
   * // Delete one CronogramaItem
   * const CronogramaItem = await prisma.cronogramaItem.delete({
   *   where: {
   *     // ... filter to delete one CronogramaItem
   *   }
   * })
   * 
   */
  delete<T extends CronogramaItemDeleteArgs>(args: Prisma.SelectSubset<T, CronogramaItemDeleteArgs<ExtArgs>>): Prisma.Prisma__CronogramaItemClient<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CronogramaItem.
   * @param {CronogramaItemUpdateArgs} args - Arguments to update one CronogramaItem.
   * @example
   * // Update one CronogramaItem
   * const cronogramaItem = await prisma.cronogramaItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CronogramaItemUpdateArgs>(args: Prisma.SelectSubset<T, CronogramaItemUpdateArgs<ExtArgs>>): Prisma.Prisma__CronogramaItemClient<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CronogramaItems.
   * @param {CronogramaItemDeleteManyArgs} args - Arguments to filter CronogramaItems to delete.
   * @example
   * // Delete a few CronogramaItems
   * const { count } = await prisma.cronogramaItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CronogramaItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, CronogramaItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CronogramaItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CronogramaItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CronogramaItems
   * const cronogramaItem = await prisma.cronogramaItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CronogramaItemUpdateManyArgs>(args: Prisma.SelectSubset<T, CronogramaItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CronogramaItems and returns the data updated in the database.
   * @param {CronogramaItemUpdateManyAndReturnArgs} args - Arguments to update many CronogramaItems.
   * @example
   * // Update many CronogramaItems
   * const cronogramaItem = await prisma.cronogramaItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CronogramaItems and only return the `id`
   * const cronogramaItemWithIdOnly = await prisma.cronogramaItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CronogramaItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CronogramaItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CronogramaItem.
   * @param {CronogramaItemUpsertArgs} args - Arguments to update or create a CronogramaItem.
   * @example
   * // Update or create a CronogramaItem
   * const cronogramaItem = await prisma.cronogramaItem.upsert({
   *   create: {
   *     // ... data to create a CronogramaItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CronogramaItem we want to update
   *   }
   * })
   */
  upsert<T extends CronogramaItemUpsertArgs>(args: Prisma.SelectSubset<T, CronogramaItemUpsertArgs<ExtArgs>>): Prisma.Prisma__CronogramaItemClient<runtime.Types.Result.GetResult<Prisma.$CronogramaItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CronogramaItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CronogramaItemCountArgs} args - Arguments to filter CronogramaItems to count.
   * @example
   * // Count the number of CronogramaItems
   * const count = await prisma.cronogramaItem.count({
   *   where: {
   *     // ... the filter for the CronogramaItems we want to count
   *   }
   * })
  **/
  count<T extends CronogramaItemCountArgs>(
    args?: Prisma.Subset<T, CronogramaItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CronogramaItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CronogramaItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CronogramaItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CronogramaItemAggregateArgs>(args: Prisma.Subset<T, CronogramaItemAggregateArgs>): Prisma.PrismaPromise<GetCronogramaItemAggregateType<T>>

  /**
   * Group by CronogramaItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CronogramaItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CronogramaItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CronogramaItemGroupByArgs['orderBy'] }
      : { orderBy?: CronogramaItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CronogramaItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCronogramaItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CronogramaItem model
 */
readonly fields: CronogramaItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CronogramaItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CronogramaItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  planoTrabalho<T extends Prisma.PlanoTrabalhoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>>): Prisma.Prisma__PlanoTrabalhoClient<runtime.Types.Result.GetResult<Prisma.$PlanoTrabalhoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CronogramaItem model
 */
export interface CronogramaItemFieldRefs {
  readonly id: Prisma.FieldRef<"CronogramaItem", 'Int'>
  readonly planoTrabalhoId: Prisma.FieldRef<"CronogramaItem", 'Int'>
  readonly eixoMeta: Prisma.FieldRef<"CronogramaItem", 'String'>
  readonly acaoEtapa: Prisma.FieldRef<"CronogramaItem", 'String'>
  readonly indicador: Prisma.FieldRef<"CronogramaItem", 'String'>
  readonly responsavel: Prisma.FieldRef<"CronogramaItem", 'String'>
  readonly inicio: Prisma.FieldRef<"CronogramaItem", 'DateTime'>
  readonly termino: Prisma.FieldRef<"CronogramaItem", 'DateTime'>
  readonly situacao: Prisma.FieldRef<"CronogramaItem", 'SituacaoCronograma'>
}
    

// Custom InputTypes
/**
 * CronogramaItem findUnique
 */
export type CronogramaItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * Filter, which CronogramaItem to fetch.
   */
  where: Prisma.CronogramaItemWhereUniqueInput
}

/**
 * CronogramaItem findUniqueOrThrow
 */
export type CronogramaItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * Filter, which CronogramaItem to fetch.
   */
  where: Prisma.CronogramaItemWhereUniqueInput
}

/**
 * CronogramaItem findFirst
 */
export type CronogramaItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * Filter, which CronogramaItem to fetch.
   */
  where?: Prisma.CronogramaItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CronogramaItems to fetch.
   */
  orderBy?: Prisma.CronogramaItemOrderByWithRelationInput | Prisma.CronogramaItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CronogramaItems.
   */
  cursor?: Prisma.CronogramaItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CronogramaItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CronogramaItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CronogramaItems.
   */
  distinct?: Prisma.CronogramaItemScalarFieldEnum | Prisma.CronogramaItemScalarFieldEnum[]
}

/**
 * CronogramaItem findFirstOrThrow
 */
export type CronogramaItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * Filter, which CronogramaItem to fetch.
   */
  where?: Prisma.CronogramaItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CronogramaItems to fetch.
   */
  orderBy?: Prisma.CronogramaItemOrderByWithRelationInput | Prisma.CronogramaItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CronogramaItems.
   */
  cursor?: Prisma.CronogramaItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CronogramaItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CronogramaItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CronogramaItems.
   */
  distinct?: Prisma.CronogramaItemScalarFieldEnum | Prisma.CronogramaItemScalarFieldEnum[]
}

/**
 * CronogramaItem findMany
 */
export type CronogramaItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * Filter, which CronogramaItems to fetch.
   */
  where?: Prisma.CronogramaItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CronogramaItems to fetch.
   */
  orderBy?: Prisma.CronogramaItemOrderByWithRelationInput | Prisma.CronogramaItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CronogramaItems.
   */
  cursor?: Prisma.CronogramaItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CronogramaItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CronogramaItems.
   */
  skip?: number
  distinct?: Prisma.CronogramaItemScalarFieldEnum | Prisma.CronogramaItemScalarFieldEnum[]
}

/**
 * CronogramaItem create
 */
export type CronogramaItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * The data needed to create a CronogramaItem.
   */
  data: Prisma.XOR<Prisma.CronogramaItemCreateInput, Prisma.CronogramaItemUncheckedCreateInput>
}

/**
 * CronogramaItem createMany
 */
export type CronogramaItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CronogramaItems.
   */
  data: Prisma.CronogramaItemCreateManyInput | Prisma.CronogramaItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CronogramaItem createManyAndReturn
 */
export type CronogramaItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * The data used to create many CronogramaItems.
   */
  data: Prisma.CronogramaItemCreateManyInput | Prisma.CronogramaItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CronogramaItem update
 */
export type CronogramaItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * The data needed to update a CronogramaItem.
   */
  data: Prisma.XOR<Prisma.CronogramaItemUpdateInput, Prisma.CronogramaItemUncheckedUpdateInput>
  /**
   * Choose, which CronogramaItem to update.
   */
  where: Prisma.CronogramaItemWhereUniqueInput
}

/**
 * CronogramaItem updateMany
 */
export type CronogramaItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CronogramaItems.
   */
  data: Prisma.XOR<Prisma.CronogramaItemUpdateManyMutationInput, Prisma.CronogramaItemUncheckedUpdateManyInput>
  /**
   * Filter which CronogramaItems to update
   */
  where?: Prisma.CronogramaItemWhereInput
  /**
   * Limit how many CronogramaItems to update.
   */
  limit?: number
}

/**
 * CronogramaItem updateManyAndReturn
 */
export type CronogramaItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * The data used to update CronogramaItems.
   */
  data: Prisma.XOR<Prisma.CronogramaItemUpdateManyMutationInput, Prisma.CronogramaItemUncheckedUpdateManyInput>
  /**
   * Filter which CronogramaItems to update
   */
  where?: Prisma.CronogramaItemWhereInput
  /**
   * Limit how many CronogramaItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CronogramaItem upsert
 */
export type CronogramaItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * The filter to search for the CronogramaItem to update in case it exists.
   */
  where: Prisma.CronogramaItemWhereUniqueInput
  /**
   * In case the CronogramaItem found by the `where` argument doesn't exist, create a new CronogramaItem with this data.
   */
  create: Prisma.XOR<Prisma.CronogramaItemCreateInput, Prisma.CronogramaItemUncheckedCreateInput>
  /**
   * In case the CronogramaItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CronogramaItemUpdateInput, Prisma.CronogramaItemUncheckedUpdateInput>
}

/**
 * CronogramaItem delete
 */
export type CronogramaItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
  /**
   * Filter which CronogramaItem to delete.
   */
  where: Prisma.CronogramaItemWhereUniqueInput
}

/**
 * CronogramaItem deleteMany
 */
export type CronogramaItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CronogramaItems to delete
   */
  where?: Prisma.CronogramaItemWhereInput
  /**
   * Limit how many CronogramaItems to delete.
   */
  limit?: number
}

/**
 * CronogramaItem without action
 */
export type CronogramaItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CronogramaItem
   */
  select?: Prisma.CronogramaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CronogramaItem
   */
  omit?: Prisma.CronogramaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CronogramaItemInclude<ExtArgs> | null
}
