
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EquipeItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EquipeItem
 * 
 */
export type EquipeItemModel = runtime.Types.Result.DefaultSelection<Prisma.$EquipeItemPayload>

export type AggregateEquipeItem = {
  _count: EquipeItemCountAggregateOutputType | null
  _avg: EquipeItemAvgAggregateOutputType | null
  _sum: EquipeItemSumAggregateOutputType | null
  _min: EquipeItemMinAggregateOutputType | null
  _max: EquipeItemMaxAggregateOutputType | null
}

export type EquipeItemAvgAggregateOutputType = {
  id: number | null
  planoTrabalhoId: number | null
  cargaHorariaSemanal: number | null
}

export type EquipeItemSumAggregateOutputType = {
  id: number | null
  planoTrabalhoId: number | null
  cargaHorariaSemanal: number | null
}

export type EquipeItemMinAggregateOutputType = {
  id: number | null
  planoTrabalhoId: number | null
  nome: string | null
  titulacaoArea: string | null
  instituicao: string | null
  funcao: string | null
  cargaHorariaSemanal: number | null
}

export type EquipeItemMaxAggregateOutputType = {
  id: number | null
  planoTrabalhoId: number | null
  nome: string | null
  titulacaoArea: string | null
  instituicao: string | null
  funcao: string | null
  cargaHorariaSemanal: number | null
}

export type EquipeItemCountAggregateOutputType = {
  id: number
  planoTrabalhoId: number
  nome: number
  titulacaoArea: number
  instituicao: number
  funcao: number
  cargaHorariaSemanal: number
  _all: number
}


export type EquipeItemAvgAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
  cargaHorariaSemanal?: true
}

export type EquipeItemSumAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
  cargaHorariaSemanal?: true
}

export type EquipeItemMinAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
  nome?: true
  titulacaoArea?: true
  instituicao?: true
  funcao?: true
  cargaHorariaSemanal?: true
}

export type EquipeItemMaxAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
  nome?: true
  titulacaoArea?: true
  instituicao?: true
  funcao?: true
  cargaHorariaSemanal?: true
}

export type EquipeItemCountAggregateInputType = {
  id?: true
  planoTrabalhoId?: true
  nome?: true
  titulacaoArea?: true
  instituicao?: true
  funcao?: true
  cargaHorariaSemanal?: true
  _all?: true
}

export type EquipeItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EquipeItem to aggregate.
   */
  where?: Prisma.EquipeItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EquipeItems to fetch.
   */
  orderBy?: Prisma.EquipeItemOrderByWithRelationInput | Prisma.EquipeItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EquipeItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EquipeItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EquipeItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EquipeItems
  **/
  _count?: true | EquipeItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EquipeItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EquipeItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EquipeItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EquipeItemMaxAggregateInputType
}

export type GetEquipeItemAggregateType<T extends EquipeItemAggregateArgs> = {
      [P in keyof T & keyof AggregateEquipeItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEquipeItem[P]>
    : Prisma.GetScalarType<T[P], AggregateEquipeItem[P]>
}




export type EquipeItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EquipeItemWhereInput
  orderBy?: Prisma.EquipeItemOrderByWithAggregationInput | Prisma.EquipeItemOrderByWithAggregationInput[]
  by: Prisma.EquipeItemScalarFieldEnum[] | Prisma.EquipeItemScalarFieldEnum
  having?: Prisma.EquipeItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EquipeItemCountAggregateInputType | true
  _avg?: EquipeItemAvgAggregateInputType
  _sum?: EquipeItemSumAggregateInputType
  _min?: EquipeItemMinAggregateInputType
  _max?: EquipeItemMaxAggregateInputType
}

export type EquipeItemGroupByOutputType = {
  id: number
  planoTrabalhoId: number
  nome: string
  titulacaoArea: string | null
  instituicao: string | null
  funcao: string | null
  cargaHorariaSemanal: number | null
  _count: EquipeItemCountAggregateOutputType | null
  _avg: EquipeItemAvgAggregateOutputType | null
  _sum: EquipeItemSumAggregateOutputType | null
  _min: EquipeItemMinAggregateOutputType | null
  _max: EquipeItemMaxAggregateOutputType | null
}

type GetEquipeItemGroupByPayload<T extends EquipeItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EquipeItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EquipeItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EquipeItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EquipeItemGroupByOutputType[P]>
      }
    >
  >



export type EquipeItemWhereInput = {
  AND?: Prisma.EquipeItemWhereInput | Prisma.EquipeItemWhereInput[]
  OR?: Prisma.EquipeItemWhereInput[]
  NOT?: Prisma.EquipeItemWhereInput | Prisma.EquipeItemWhereInput[]
  id?: Prisma.IntFilter<"EquipeItem"> | number
  planoTrabalhoId?: Prisma.IntFilter<"EquipeItem"> | number
  nome?: Prisma.StringFilter<"EquipeItem"> | string
  titulacaoArea?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  instituicao?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  funcao?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  cargaHorariaSemanal?: Prisma.IntNullableFilter<"EquipeItem"> | number | null
  planoTrabalho?: Prisma.XOR<Prisma.PlanoTrabalhoScalarRelationFilter, Prisma.PlanoTrabalhoWhereInput>
}

export type EquipeItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  titulacaoArea?: Prisma.SortOrderInput | Prisma.SortOrder
  instituicao?: Prisma.SortOrderInput | Prisma.SortOrder
  funcao?: Prisma.SortOrderInput | Prisma.SortOrder
  cargaHorariaSemanal?: Prisma.SortOrderInput | Prisma.SortOrder
  planoTrabalho?: Prisma.PlanoTrabalhoOrderByWithRelationInput
}

export type EquipeItemWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.EquipeItemWhereInput | Prisma.EquipeItemWhereInput[]
  OR?: Prisma.EquipeItemWhereInput[]
  NOT?: Prisma.EquipeItemWhereInput | Prisma.EquipeItemWhereInput[]
  planoTrabalhoId?: Prisma.IntFilter<"EquipeItem"> | number
  nome?: Prisma.StringFilter<"EquipeItem"> | string
  titulacaoArea?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  instituicao?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  funcao?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  cargaHorariaSemanal?: Prisma.IntNullableFilter<"EquipeItem"> | number | null
  planoTrabalho?: Prisma.XOR<Prisma.PlanoTrabalhoScalarRelationFilter, Prisma.PlanoTrabalhoWhereInput>
}, "id">

export type EquipeItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  titulacaoArea?: Prisma.SortOrderInput | Prisma.SortOrder
  instituicao?: Prisma.SortOrderInput | Prisma.SortOrder
  funcao?: Prisma.SortOrderInput | Prisma.SortOrder
  cargaHorariaSemanal?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EquipeItemCountOrderByAggregateInput
  _avg?: Prisma.EquipeItemAvgOrderByAggregateInput
  _max?: Prisma.EquipeItemMaxOrderByAggregateInput
  _min?: Prisma.EquipeItemMinOrderByAggregateInput
  _sum?: Prisma.EquipeItemSumOrderByAggregateInput
}

export type EquipeItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.EquipeItemScalarWhereWithAggregatesInput | Prisma.EquipeItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.EquipeItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EquipeItemScalarWhereWithAggregatesInput | Prisma.EquipeItemScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"EquipeItem"> | number
  planoTrabalhoId?: Prisma.IntWithAggregatesFilter<"EquipeItem"> | number
  nome?: Prisma.StringWithAggregatesFilter<"EquipeItem"> | string
  titulacaoArea?: Prisma.StringNullableWithAggregatesFilter<"EquipeItem"> | string | null
  instituicao?: Prisma.StringNullableWithAggregatesFilter<"EquipeItem"> | string | null
  funcao?: Prisma.StringNullableWithAggregatesFilter<"EquipeItem"> | string | null
  cargaHorariaSemanal?: Prisma.IntNullableWithAggregatesFilter<"EquipeItem"> | number | null
}

export type EquipeItemCreateInput = {
  nome: string
  titulacaoArea?: string | null
  instituicao?: string | null
  funcao?: string | null
  cargaHorariaSemanal?: number | null
  planoTrabalho: Prisma.PlanoTrabalhoCreateNestedOneWithoutEquipeInput
}

export type EquipeItemUncheckedCreateInput = {
  id?: number
  planoTrabalhoId: number
  nome: string
  titulacaoArea?: string | null
  instituicao?: string | null
  funcao?: string | null
  cargaHorariaSemanal?: number | null
}

export type EquipeItemUpdateInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  titulacaoArea?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cargaHorariaSemanal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  planoTrabalho?: Prisma.PlanoTrabalhoUpdateOneRequiredWithoutEquipeNestedInput
}

export type EquipeItemUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  planoTrabalhoId?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  titulacaoArea?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cargaHorariaSemanal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type EquipeItemCreateManyInput = {
  id?: number
  planoTrabalhoId: number
  nome: string
  titulacaoArea?: string | null
  instituicao?: string | null
  funcao?: string | null
  cargaHorariaSemanal?: number | null
}

export type EquipeItemUpdateManyMutationInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  titulacaoArea?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cargaHorariaSemanal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type EquipeItemUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  planoTrabalhoId?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  titulacaoArea?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cargaHorariaSemanal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type EquipeItemListRelationFilter = {
  every?: Prisma.EquipeItemWhereInput
  some?: Prisma.EquipeItemWhereInput
  none?: Prisma.EquipeItemWhereInput
}

export type EquipeItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EquipeItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  titulacaoArea?: Prisma.SortOrder
  instituicao?: Prisma.SortOrder
  funcao?: Prisma.SortOrder
  cargaHorariaSemanal?: Prisma.SortOrder
}

export type EquipeItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  cargaHorariaSemanal?: Prisma.SortOrder
}

export type EquipeItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  titulacaoArea?: Prisma.SortOrder
  instituicao?: Prisma.SortOrder
  funcao?: Prisma.SortOrder
  cargaHorariaSemanal?: Prisma.SortOrder
}

export type EquipeItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  titulacaoArea?: Prisma.SortOrder
  instituicao?: Prisma.SortOrder
  funcao?: Prisma.SortOrder
  cargaHorariaSemanal?: Prisma.SortOrder
}

export type EquipeItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planoTrabalhoId?: Prisma.SortOrder
  cargaHorariaSemanal?: Prisma.SortOrder
}

export type EquipeItemCreateNestedManyWithoutPlanoTrabalhoInput = {
  create?: Prisma.XOR<Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput, Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput> | Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput[] | Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput[]
  connectOrCreate?: Prisma.EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput | Prisma.EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput[]
  createMany?: Prisma.EquipeItemCreateManyPlanoTrabalhoInputEnvelope
  connect?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
}

export type EquipeItemUncheckedCreateNestedManyWithoutPlanoTrabalhoInput = {
  create?: Prisma.XOR<Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput, Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput> | Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput[] | Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput[]
  connectOrCreate?: Prisma.EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput | Prisma.EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput[]
  createMany?: Prisma.EquipeItemCreateManyPlanoTrabalhoInputEnvelope
  connect?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
}

export type EquipeItemUpdateManyWithoutPlanoTrabalhoNestedInput = {
  create?: Prisma.XOR<Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput, Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput> | Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput[] | Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput[]
  connectOrCreate?: Prisma.EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput | Prisma.EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput[]
  upsert?: Prisma.EquipeItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput | Prisma.EquipeItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput[]
  createMany?: Prisma.EquipeItemCreateManyPlanoTrabalhoInputEnvelope
  set?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
  disconnect?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
  delete?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
  connect?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
  update?: Prisma.EquipeItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput | Prisma.EquipeItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput[]
  updateMany?: Prisma.EquipeItemUpdateManyWithWhereWithoutPlanoTrabalhoInput | Prisma.EquipeItemUpdateManyWithWhereWithoutPlanoTrabalhoInput[]
  deleteMany?: Prisma.EquipeItemScalarWhereInput | Prisma.EquipeItemScalarWhereInput[]
}

export type EquipeItemUncheckedUpdateManyWithoutPlanoTrabalhoNestedInput = {
  create?: Prisma.XOR<Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput, Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput> | Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput[] | Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput[]
  connectOrCreate?: Prisma.EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput | Prisma.EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput[]
  upsert?: Prisma.EquipeItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput | Prisma.EquipeItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput[]
  createMany?: Prisma.EquipeItemCreateManyPlanoTrabalhoInputEnvelope
  set?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
  disconnect?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
  delete?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
  connect?: Prisma.EquipeItemWhereUniqueInput | Prisma.EquipeItemWhereUniqueInput[]
  update?: Prisma.EquipeItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput | Prisma.EquipeItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput[]
  updateMany?: Prisma.EquipeItemUpdateManyWithWhereWithoutPlanoTrabalhoInput | Prisma.EquipeItemUpdateManyWithWhereWithoutPlanoTrabalhoInput[]
  deleteMany?: Prisma.EquipeItemScalarWhereInput | Prisma.EquipeItemScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EquipeItemCreateWithoutPlanoTrabalhoInput = {
  nome: string
  titulacaoArea?: string | null
  instituicao?: string | null
  funcao?: string | null
  cargaHorariaSemanal?: number | null
}

export type EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput = {
  id?: number
  nome: string
  titulacaoArea?: string | null
  instituicao?: string | null
  funcao?: string | null
  cargaHorariaSemanal?: number | null
}

export type EquipeItemCreateOrConnectWithoutPlanoTrabalhoInput = {
  where: Prisma.EquipeItemWhereUniqueInput
  create: Prisma.XOR<Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput, Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput>
}

export type EquipeItemCreateManyPlanoTrabalhoInputEnvelope = {
  data: Prisma.EquipeItemCreateManyPlanoTrabalhoInput | Prisma.EquipeItemCreateManyPlanoTrabalhoInput[]
  skipDuplicates?: boolean
}

export type EquipeItemUpsertWithWhereUniqueWithoutPlanoTrabalhoInput = {
  where: Prisma.EquipeItemWhereUniqueInput
  update: Prisma.XOR<Prisma.EquipeItemUpdateWithoutPlanoTrabalhoInput, Prisma.EquipeItemUncheckedUpdateWithoutPlanoTrabalhoInput>
  create: Prisma.XOR<Prisma.EquipeItemCreateWithoutPlanoTrabalhoInput, Prisma.EquipeItemUncheckedCreateWithoutPlanoTrabalhoInput>
}

export type EquipeItemUpdateWithWhereUniqueWithoutPlanoTrabalhoInput = {
  where: Prisma.EquipeItemWhereUniqueInput
  data: Prisma.XOR<Prisma.EquipeItemUpdateWithoutPlanoTrabalhoInput, Prisma.EquipeItemUncheckedUpdateWithoutPlanoTrabalhoInput>
}

export type EquipeItemUpdateManyWithWhereWithoutPlanoTrabalhoInput = {
  where: Prisma.EquipeItemScalarWhereInput
  data: Prisma.XOR<Prisma.EquipeItemUpdateManyMutationInput, Prisma.EquipeItemUncheckedUpdateManyWithoutPlanoTrabalhoInput>
}

export type EquipeItemScalarWhereInput = {
  AND?: Prisma.EquipeItemScalarWhereInput | Prisma.EquipeItemScalarWhereInput[]
  OR?: Prisma.EquipeItemScalarWhereInput[]
  NOT?: Prisma.EquipeItemScalarWhereInput | Prisma.EquipeItemScalarWhereInput[]
  id?: Prisma.IntFilter<"EquipeItem"> | number
  planoTrabalhoId?: Prisma.IntFilter<"EquipeItem"> | number
  nome?: Prisma.StringFilter<"EquipeItem"> | string
  titulacaoArea?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  instituicao?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  funcao?: Prisma.StringNullableFilter<"EquipeItem"> | string | null
  cargaHorariaSemanal?: Prisma.IntNullableFilter<"EquipeItem"> | number | null
}

export type EquipeItemCreateManyPlanoTrabalhoInput = {
  id?: number
  nome: string
  titulacaoArea?: string | null
  instituicao?: string | null
  funcao?: string | null
  cargaHorariaSemanal?: number | null
}

export type EquipeItemUpdateWithoutPlanoTrabalhoInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  titulacaoArea?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cargaHorariaSemanal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type EquipeItemUncheckedUpdateWithoutPlanoTrabalhoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  titulacaoArea?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cargaHorariaSemanal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type EquipeItemUncheckedUpdateManyWithoutPlanoTrabalhoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  titulacaoArea?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cargaHorariaSemanal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type EquipeItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  planoTrabalhoId?: boolean
  nome?: boolean
  titulacaoArea?: boolean
  instituicao?: boolean
  funcao?: boolean
  cargaHorariaSemanal?: boolean
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["equipeItem"]>

export type EquipeItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  planoTrabalhoId?: boolean
  nome?: boolean
  titulacaoArea?: boolean
  instituicao?: boolean
  funcao?: boolean
  cargaHorariaSemanal?: boolean
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["equipeItem"]>

export type EquipeItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  planoTrabalhoId?: boolean
  nome?: boolean
  titulacaoArea?: boolean
  instituicao?: boolean
  funcao?: boolean
  cargaHorariaSemanal?: boolean
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["equipeItem"]>

export type EquipeItemSelectScalar = {
  id?: boolean
  planoTrabalhoId?: boolean
  nome?: boolean
  titulacaoArea?: boolean
  instituicao?: boolean
  funcao?: boolean
  cargaHorariaSemanal?: boolean
}

export type EquipeItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "planoTrabalhoId" | "nome" | "titulacaoArea" | "instituicao" | "funcao" | "cargaHorariaSemanal", ExtArgs["result"]["equipeItem"]>
export type EquipeItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}
export type EquipeItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}
export type EquipeItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  planoTrabalho?: boolean | Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>
}

export type $EquipeItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EquipeItem"
  objects: {
    planoTrabalho: Prisma.$PlanoTrabalhoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    planoTrabalhoId: number
    nome: string
    titulacaoArea: string | null
    instituicao: string | null
    funcao: string | null
    cargaHorariaSemanal: number | null
  }, ExtArgs["result"]["equipeItem"]>
  composites: {}
}

export type EquipeItemGetPayload<S extends boolean | null | undefined | EquipeItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload, S>

export type EquipeItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EquipeItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EquipeItemCountAggregateInputType | true
  }

export interface EquipeItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EquipeItem'], meta: { name: 'EquipeItem' } }
  /**
   * Find zero or one EquipeItem that matches the filter.
   * @param {EquipeItemFindUniqueArgs} args - Arguments to find a EquipeItem
   * @example
   * // Get one EquipeItem
   * const equipeItem = await prisma.equipeItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EquipeItemFindUniqueArgs>(args: Prisma.SelectSubset<T, EquipeItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EquipeItemClient<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EquipeItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EquipeItemFindUniqueOrThrowArgs} args - Arguments to find a EquipeItem
   * @example
   * // Get one EquipeItem
   * const equipeItem = await prisma.equipeItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EquipeItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EquipeItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EquipeItemClient<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EquipeItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EquipeItemFindFirstArgs} args - Arguments to find a EquipeItem
   * @example
   * // Get one EquipeItem
   * const equipeItem = await prisma.equipeItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EquipeItemFindFirstArgs>(args?: Prisma.SelectSubset<T, EquipeItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__EquipeItemClient<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EquipeItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EquipeItemFindFirstOrThrowArgs} args - Arguments to find a EquipeItem
   * @example
   * // Get one EquipeItem
   * const equipeItem = await prisma.equipeItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EquipeItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EquipeItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EquipeItemClient<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EquipeItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EquipeItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EquipeItems
   * const equipeItems = await prisma.equipeItem.findMany()
   * 
   * // Get first 10 EquipeItems
   * const equipeItems = await prisma.equipeItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const equipeItemWithIdOnly = await prisma.equipeItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EquipeItemFindManyArgs>(args?: Prisma.SelectSubset<T, EquipeItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EquipeItem.
   * @param {EquipeItemCreateArgs} args - Arguments to create a EquipeItem.
   * @example
   * // Create one EquipeItem
   * const EquipeItem = await prisma.equipeItem.create({
   *   data: {
   *     // ... data to create a EquipeItem
   *   }
   * })
   * 
   */
  create<T extends EquipeItemCreateArgs>(args: Prisma.SelectSubset<T, EquipeItemCreateArgs<ExtArgs>>): Prisma.Prisma__EquipeItemClient<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EquipeItems.
   * @param {EquipeItemCreateManyArgs} args - Arguments to create many EquipeItems.
   * @example
   * // Create many EquipeItems
   * const equipeItem = await prisma.equipeItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EquipeItemCreateManyArgs>(args?: Prisma.SelectSubset<T, EquipeItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EquipeItems and returns the data saved in the database.
   * @param {EquipeItemCreateManyAndReturnArgs} args - Arguments to create many EquipeItems.
   * @example
   * // Create many EquipeItems
   * const equipeItem = await prisma.equipeItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EquipeItems and only return the `id`
   * const equipeItemWithIdOnly = await prisma.equipeItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EquipeItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EquipeItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EquipeItem.
   * @param {EquipeItemDeleteArgs} args - Arguments to delete one EquipeItem.
   * @example
   * // Delete one EquipeItem
   * const EquipeItem = await prisma.equipeItem.delete({
   *   where: {
   *     // ... filter to delete one EquipeItem
   *   }
   * })
   * 
   */
  delete<T extends EquipeItemDeleteArgs>(args: Prisma.SelectSubset<T, EquipeItemDeleteArgs<ExtArgs>>): Prisma.Prisma__EquipeItemClient<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EquipeItem.
   * @param {EquipeItemUpdateArgs} args - Arguments to update one EquipeItem.
   * @example
   * // Update one EquipeItem
   * const equipeItem = await prisma.equipeItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EquipeItemUpdateArgs>(args: Prisma.SelectSubset<T, EquipeItemUpdateArgs<ExtArgs>>): Prisma.Prisma__EquipeItemClient<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EquipeItems.
   * @param {EquipeItemDeleteManyArgs} args - Arguments to filter EquipeItems to delete.
   * @example
   * // Delete a few EquipeItems
   * const { count } = await prisma.equipeItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EquipeItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, EquipeItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EquipeItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EquipeItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EquipeItems
   * const equipeItem = await prisma.equipeItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EquipeItemUpdateManyArgs>(args: Prisma.SelectSubset<T, EquipeItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EquipeItems and returns the data updated in the database.
   * @param {EquipeItemUpdateManyAndReturnArgs} args - Arguments to update many EquipeItems.
   * @example
   * // Update many EquipeItems
   * const equipeItem = await prisma.equipeItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EquipeItems and only return the `id`
   * const equipeItemWithIdOnly = await prisma.equipeItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EquipeItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EquipeItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EquipeItem.
   * @param {EquipeItemUpsertArgs} args - Arguments to update or create a EquipeItem.
   * @example
   * // Update or create a EquipeItem
   * const equipeItem = await prisma.equipeItem.upsert({
   *   create: {
   *     // ... data to create a EquipeItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EquipeItem we want to update
   *   }
   * })
   */
  upsert<T extends EquipeItemUpsertArgs>(args: Prisma.SelectSubset<T, EquipeItemUpsertArgs<ExtArgs>>): Prisma.Prisma__EquipeItemClient<runtime.Types.Result.GetResult<Prisma.$EquipeItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EquipeItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EquipeItemCountArgs} args - Arguments to filter EquipeItems to count.
   * @example
   * // Count the number of EquipeItems
   * const count = await prisma.equipeItem.count({
   *   where: {
   *     // ... the filter for the EquipeItems we want to count
   *   }
   * })
  **/
  count<T extends EquipeItemCountArgs>(
    args?: Prisma.Subset<T, EquipeItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EquipeItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EquipeItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EquipeItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EquipeItemAggregateArgs>(args: Prisma.Subset<T, EquipeItemAggregateArgs>): Prisma.PrismaPromise<GetEquipeItemAggregateType<T>>

  /**
   * Group by EquipeItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EquipeItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EquipeItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EquipeItemGroupByArgs['orderBy'] }
      : { orderBy?: EquipeItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EquipeItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEquipeItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EquipeItem model
 */
readonly fields: EquipeItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EquipeItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EquipeItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  planoTrabalho<T extends Prisma.PlanoTrabalhoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlanoTrabalhoDefaultArgs<ExtArgs>>): Prisma.Prisma__PlanoTrabalhoClient<runtime.Types.Result.GetResult<Prisma.$PlanoTrabalhoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EquipeItem model
 */
export interface EquipeItemFieldRefs {
  readonly id: Prisma.FieldRef<"EquipeItem", 'Int'>
  readonly planoTrabalhoId: Prisma.FieldRef<"EquipeItem", 'Int'>
  readonly nome: Prisma.FieldRef<"EquipeItem", 'String'>
  readonly titulacaoArea: Prisma.FieldRef<"EquipeItem", 'String'>
  readonly instituicao: Prisma.FieldRef<"EquipeItem", 'String'>
  readonly funcao: Prisma.FieldRef<"EquipeItem", 'String'>
  readonly cargaHorariaSemanal: Prisma.FieldRef<"EquipeItem", 'Int'>
}
    

// Custom InputTypes
/**
 * EquipeItem findUnique
 */
export type EquipeItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * Filter, which EquipeItem to fetch.
   */
  where: Prisma.EquipeItemWhereUniqueInput
}

/**
 * EquipeItem findUniqueOrThrow
 */
export type EquipeItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * Filter, which EquipeItem to fetch.
   */
  where: Prisma.EquipeItemWhereUniqueInput
}

/**
 * EquipeItem findFirst
 */
export type EquipeItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * Filter, which EquipeItem to fetch.
   */
  where?: Prisma.EquipeItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EquipeItems to fetch.
   */
  orderBy?: Prisma.EquipeItemOrderByWithRelationInput | Prisma.EquipeItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EquipeItems.
   */
  cursor?: Prisma.EquipeItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EquipeItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EquipeItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EquipeItems.
   */
  distinct?: Prisma.EquipeItemScalarFieldEnum | Prisma.EquipeItemScalarFieldEnum[]
}

/**
 * EquipeItem findFirstOrThrow
 */
export type EquipeItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * Filter, which EquipeItem to fetch.
   */
  where?: Prisma.EquipeItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EquipeItems to fetch.
   */
  orderBy?: Prisma.EquipeItemOrderByWithRelationInput | Prisma.EquipeItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EquipeItems.
   */
  cursor?: Prisma.EquipeItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EquipeItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EquipeItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EquipeItems.
   */
  distinct?: Prisma.EquipeItemScalarFieldEnum | Prisma.EquipeItemScalarFieldEnum[]
}

/**
 * EquipeItem findMany
 */
export type EquipeItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * Filter, which EquipeItems to fetch.
   */
  where?: Prisma.EquipeItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EquipeItems to fetch.
   */
  orderBy?: Prisma.EquipeItemOrderByWithRelationInput | Prisma.EquipeItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EquipeItems.
   */
  cursor?: Prisma.EquipeItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EquipeItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EquipeItems.
   */
  skip?: number
  distinct?: Prisma.EquipeItemScalarFieldEnum | Prisma.EquipeItemScalarFieldEnum[]
}

/**
 * EquipeItem create
 */
export type EquipeItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * The data needed to create a EquipeItem.
   */
  data: Prisma.XOR<Prisma.EquipeItemCreateInput, Prisma.EquipeItemUncheckedCreateInput>
}

/**
 * EquipeItem createMany
 */
export type EquipeItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EquipeItems.
   */
  data: Prisma.EquipeItemCreateManyInput | Prisma.EquipeItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EquipeItem createManyAndReturn
 */
export type EquipeItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * The data used to create many EquipeItems.
   */
  data: Prisma.EquipeItemCreateManyInput | Prisma.EquipeItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EquipeItem update
 */
export type EquipeItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * The data needed to update a EquipeItem.
   */
  data: Prisma.XOR<Prisma.EquipeItemUpdateInput, Prisma.EquipeItemUncheckedUpdateInput>
  /**
   * Choose, which EquipeItem to update.
   */
  where: Prisma.EquipeItemWhereUniqueInput
}

/**
 * EquipeItem updateMany
 */
export type EquipeItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EquipeItems.
   */
  data: Prisma.XOR<Prisma.EquipeItemUpdateManyMutationInput, Prisma.EquipeItemUncheckedUpdateManyInput>
  /**
   * Filter which EquipeItems to update
   */
  where?: Prisma.EquipeItemWhereInput
  /**
   * Limit how many EquipeItems to update.
   */
  limit?: number
}

/**
 * EquipeItem updateManyAndReturn
 */
export type EquipeItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * The data used to update EquipeItems.
   */
  data: Prisma.XOR<Prisma.EquipeItemUpdateManyMutationInput, Prisma.EquipeItemUncheckedUpdateManyInput>
  /**
   * Filter which EquipeItems to update
   */
  where?: Prisma.EquipeItemWhereInput
  /**
   * Limit how many EquipeItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EquipeItem upsert
 */
export type EquipeItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * The filter to search for the EquipeItem to update in case it exists.
   */
  where: Prisma.EquipeItemWhereUniqueInput
  /**
   * In case the EquipeItem found by the `where` argument doesn't exist, create a new EquipeItem with this data.
   */
  create: Prisma.XOR<Prisma.EquipeItemCreateInput, Prisma.EquipeItemUncheckedCreateInput>
  /**
   * In case the EquipeItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EquipeItemUpdateInput, Prisma.EquipeItemUncheckedUpdateInput>
}

/**
 * EquipeItem delete
 */
export type EquipeItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
  /**
   * Filter which EquipeItem to delete.
   */
  where: Prisma.EquipeItemWhereUniqueInput
}

/**
 * EquipeItem deleteMany
 */
export type EquipeItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EquipeItems to delete
   */
  where?: Prisma.EquipeItemWhereInput
  /**
   * Limit how many EquipeItems to delete.
   */
  limit?: number
}

/**
 * EquipeItem without action
 */
export type EquipeItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EquipeItem
   */
  select?: Prisma.EquipeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EquipeItem
   */
  omit?: Prisma.EquipeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EquipeItemInclude<ExtArgs> | null
}
