
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Projeto` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Projeto
 * 
 */
export type ProjetoModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjetoPayload>

export type AggregateProjeto = {
  _count: ProjetoCountAggregateOutputType | null
  _avg: ProjetoAvgAggregateOutputType | null
  _sum: ProjetoSumAggregateOutputType | null
  _min: ProjetoMinAggregateOutputType | null
  _max: ProjetoMaxAggregateOutputType | null
}

export type ProjetoAvgAggregateOutputType = {
  id: number | null
  proponenteId: number | null
}

export type ProjetoSumAggregateOutputType = {
  id: number | null
  proponenteId: number | null
}

export type ProjetoMinAggregateOutputType = {
  id: number | null
  titulo: string | null
  objetivos: string | null
  justificativa: string | null
  abrangencia: string | null
  proponenteId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjetoMaxAggregateOutputType = {
  id: number | null
  titulo: string | null
  objetivos: string | null
  justificativa: string | null
  abrangencia: string | null
  proponenteId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjetoCountAggregateOutputType = {
  id: number
  titulo: number
  objetivos: number
  justificativa: number
  abrangencia: number
  proponenteId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProjetoAvgAggregateInputType = {
  id?: true
  proponenteId?: true
}

export type ProjetoSumAggregateInputType = {
  id?: true
  proponenteId?: true
}

export type ProjetoMinAggregateInputType = {
  id?: true
  titulo?: true
  objetivos?: true
  justificativa?: true
  abrangencia?: true
  proponenteId?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjetoMaxAggregateInputType = {
  id?: true
  titulo?: true
  objetivos?: true
  justificativa?: true
  abrangencia?: true
  proponenteId?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjetoCountAggregateInputType = {
  id?: true
  titulo?: true
  objetivos?: true
  justificativa?: true
  abrangencia?: true
  proponenteId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProjetoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Projeto to aggregate.
   */
  where?: Prisma.ProjetoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projetos to fetch.
   */
  orderBy?: Prisma.ProjetoOrderByWithRelationInput | Prisma.ProjetoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjetoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projetos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projetos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Projetos
  **/
  _count?: true | ProjetoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProjetoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProjetoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjetoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjetoMaxAggregateInputType
}

export type GetProjetoAggregateType<T extends ProjetoAggregateArgs> = {
      [P in keyof T & keyof AggregateProjeto]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProjeto[P]>
    : Prisma.GetScalarType<T[P], AggregateProjeto[P]>
}




export type ProjetoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjetoWhereInput
  orderBy?: Prisma.ProjetoOrderByWithAggregationInput | Prisma.ProjetoOrderByWithAggregationInput[]
  by: Prisma.ProjetoScalarFieldEnum[] | Prisma.ProjetoScalarFieldEnum
  having?: Prisma.ProjetoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjetoCountAggregateInputType | true
  _avg?: ProjetoAvgAggregateInputType
  _sum?: ProjetoSumAggregateInputType
  _min?: ProjetoMinAggregateInputType
  _max?: ProjetoMaxAggregateInputType
}

export type ProjetoGroupByOutputType = {
  id: number
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  proponenteId: number
  createdAt: Date
  updatedAt: Date
  _count: ProjetoCountAggregateOutputType | null
  _avg: ProjetoAvgAggregateOutputType | null
  _sum: ProjetoSumAggregateOutputType | null
  _min: ProjetoMinAggregateOutputType | null
  _max: ProjetoMaxAggregateOutputType | null
}

type GetProjetoGroupByPayload<T extends ProjetoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjetoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjetoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjetoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjetoGroupByOutputType[P]>
      }
    >
  >



export type ProjetoWhereInput = {
  AND?: Prisma.ProjetoWhereInput | Prisma.ProjetoWhereInput[]
  OR?: Prisma.ProjetoWhereInput[]
  NOT?: Prisma.ProjetoWhereInput | Prisma.ProjetoWhereInput[]
  id?: Prisma.IntFilter<"Projeto"> | number
  titulo?: Prisma.StringFilter<"Projeto"> | string
  objetivos?: Prisma.StringFilter<"Projeto"> | string
  justificativa?: Prisma.StringFilter<"Projeto"> | string
  abrangencia?: Prisma.StringFilter<"Projeto"> | string
  proponenteId?: Prisma.IntFilter<"Projeto"> | number
  createdAt?: Prisma.DateTimeFilter<"Projeto"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Projeto"> | Date | string
  proponente?: Prisma.XOR<Prisma.ProponenteScalarRelationFilter, Prisma.ProponenteWhereInput>
  planoTrabalho?: Prisma.XOR<Prisma.PlanoTrabalhoNullableScalarRelationFilter, Prisma.PlanoTrabalhoWhereInput> | null
}

export type ProjetoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  objetivos?: Prisma.SortOrder
  justificativa?: Prisma.SortOrder
  abrangencia?: Prisma.SortOrder
  proponenteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  proponente?: Prisma.ProponenteOrderByWithRelationInput
  planoTrabalho?: Prisma.PlanoTrabalhoOrderByWithRelationInput
}

export type ProjetoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ProjetoWhereInput | Prisma.ProjetoWhereInput[]
  OR?: Prisma.ProjetoWhereInput[]
  NOT?: Prisma.ProjetoWhereInput | Prisma.ProjetoWhereInput[]
  titulo?: Prisma.StringFilter<"Projeto"> | string
  objetivos?: Prisma.StringFilter<"Projeto"> | string
  justificativa?: Prisma.StringFilter<"Projeto"> | string
  abrangencia?: Prisma.StringFilter<"Projeto"> | string
  proponenteId?: Prisma.IntFilter<"Projeto"> | number
  createdAt?: Prisma.DateTimeFilter<"Projeto"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Projeto"> | Date | string
  proponente?: Prisma.XOR<Prisma.ProponenteScalarRelationFilter, Prisma.ProponenteWhereInput>
  planoTrabalho?: Prisma.XOR<Prisma.PlanoTrabalhoNullableScalarRelationFilter, Prisma.PlanoTrabalhoWhereInput> | null
}, "id">

export type ProjetoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  objetivos?: Prisma.SortOrder
  justificativa?: Prisma.SortOrder
  abrangencia?: Prisma.SortOrder
  proponenteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProjetoCountOrderByAggregateInput
  _avg?: Prisma.ProjetoAvgOrderByAggregateInput
  _max?: Prisma.ProjetoMaxOrderByAggregateInput
  _min?: Prisma.ProjetoMinOrderByAggregateInput
  _sum?: Prisma.ProjetoSumOrderByAggregateInput
}

export type ProjetoScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjetoScalarWhereWithAggregatesInput | Prisma.ProjetoScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjetoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjetoScalarWhereWithAggregatesInput | Prisma.ProjetoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Projeto"> | number
  titulo?: Prisma.StringWithAggregatesFilter<"Projeto"> | string
  objetivos?: Prisma.StringWithAggregatesFilter<"Projeto"> | string
  justificativa?: Prisma.StringWithAggregatesFilter<"Projeto"> | string
  abrangencia?: Prisma.StringWithAggregatesFilter<"Projeto"> | string
  proponenteId?: Prisma.IntWithAggregatesFilter<"Projeto"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Projeto"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Projeto"> | Date | string
}

export type ProjetoCreateInput = {
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  createdAt?: Date | string
  updatedAt?: Date | string
  proponente: Prisma.ProponenteCreateNestedOneWithoutProjetosInput
  planoTrabalho?: Prisma.PlanoTrabalhoCreateNestedOneWithoutProjetoInput
}

export type ProjetoUncheckedCreateInput = {
  id?: number
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  proponenteId: number
  createdAt?: Date | string
  updatedAt?: Date | string
  planoTrabalho?: Prisma.PlanoTrabalhoUncheckedCreateNestedOneWithoutProjetoInput
}

export type ProjetoUpdateInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  proponente?: Prisma.ProponenteUpdateOneRequiredWithoutProjetosNestedInput
  planoTrabalho?: Prisma.PlanoTrabalhoUpdateOneWithoutProjetoNestedInput
}

export type ProjetoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  proponenteId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  planoTrabalho?: Prisma.PlanoTrabalhoUncheckedUpdateOneWithoutProjetoNestedInput
}

export type ProjetoCreateManyInput = {
  id?: number
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  proponenteId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjetoUpdateManyMutationInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjetoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  proponenteId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjetoListRelationFilter = {
  every?: Prisma.ProjetoWhereInput
  some?: Prisma.ProjetoWhereInput
  none?: Prisma.ProjetoWhereInput
}

export type ProjetoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProjetoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  objetivos?: Prisma.SortOrder
  justificativa?: Prisma.SortOrder
  abrangencia?: Prisma.SortOrder
  proponenteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjetoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  proponenteId?: Prisma.SortOrder
}

export type ProjetoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  objetivos?: Prisma.SortOrder
  justificativa?: Prisma.SortOrder
  abrangencia?: Prisma.SortOrder
  proponenteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjetoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  objetivos?: Prisma.SortOrder
  justificativa?: Prisma.SortOrder
  abrangencia?: Prisma.SortOrder
  proponenteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjetoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  proponenteId?: Prisma.SortOrder
}

export type ProjetoScalarRelationFilter = {
  is?: Prisma.ProjetoWhereInput
  isNot?: Prisma.ProjetoWhereInput
}

export type ProjetoCreateNestedManyWithoutProponenteInput = {
  create?: Prisma.XOR<Prisma.ProjetoCreateWithoutProponenteInput, Prisma.ProjetoUncheckedCreateWithoutProponenteInput> | Prisma.ProjetoCreateWithoutProponenteInput[] | Prisma.ProjetoUncheckedCreateWithoutProponenteInput[]
  connectOrCreate?: Prisma.ProjetoCreateOrConnectWithoutProponenteInput | Prisma.ProjetoCreateOrConnectWithoutProponenteInput[]
  createMany?: Prisma.ProjetoCreateManyProponenteInputEnvelope
  connect?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
}

export type ProjetoUncheckedCreateNestedManyWithoutProponenteInput = {
  create?: Prisma.XOR<Prisma.ProjetoCreateWithoutProponenteInput, Prisma.ProjetoUncheckedCreateWithoutProponenteInput> | Prisma.ProjetoCreateWithoutProponenteInput[] | Prisma.ProjetoUncheckedCreateWithoutProponenteInput[]
  connectOrCreate?: Prisma.ProjetoCreateOrConnectWithoutProponenteInput | Prisma.ProjetoCreateOrConnectWithoutProponenteInput[]
  createMany?: Prisma.ProjetoCreateManyProponenteInputEnvelope
  connect?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
}

export type ProjetoUpdateManyWithoutProponenteNestedInput = {
  create?: Prisma.XOR<Prisma.ProjetoCreateWithoutProponenteInput, Prisma.ProjetoUncheckedCreateWithoutProponenteInput> | Prisma.ProjetoCreateWithoutProponenteInput[] | Prisma.ProjetoUncheckedCreateWithoutProponenteInput[]
  connectOrCreate?: Prisma.ProjetoCreateOrConnectWithoutProponenteInput | Prisma.ProjetoCreateOrConnectWithoutProponenteInput[]
  upsert?: Prisma.ProjetoUpsertWithWhereUniqueWithoutProponenteInput | Prisma.ProjetoUpsertWithWhereUniqueWithoutProponenteInput[]
  createMany?: Prisma.ProjetoCreateManyProponenteInputEnvelope
  set?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
  disconnect?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
  delete?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
  connect?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
  update?: Prisma.ProjetoUpdateWithWhereUniqueWithoutProponenteInput | Prisma.ProjetoUpdateWithWhereUniqueWithoutProponenteInput[]
  updateMany?: Prisma.ProjetoUpdateManyWithWhereWithoutProponenteInput | Prisma.ProjetoUpdateManyWithWhereWithoutProponenteInput[]
  deleteMany?: Prisma.ProjetoScalarWhereInput | Prisma.ProjetoScalarWhereInput[]
}

export type ProjetoUncheckedUpdateManyWithoutProponenteNestedInput = {
  create?: Prisma.XOR<Prisma.ProjetoCreateWithoutProponenteInput, Prisma.ProjetoUncheckedCreateWithoutProponenteInput> | Prisma.ProjetoCreateWithoutProponenteInput[] | Prisma.ProjetoUncheckedCreateWithoutProponenteInput[]
  connectOrCreate?: Prisma.ProjetoCreateOrConnectWithoutProponenteInput | Prisma.ProjetoCreateOrConnectWithoutProponenteInput[]
  upsert?: Prisma.ProjetoUpsertWithWhereUniqueWithoutProponenteInput | Prisma.ProjetoUpsertWithWhereUniqueWithoutProponenteInput[]
  createMany?: Prisma.ProjetoCreateManyProponenteInputEnvelope
  set?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
  disconnect?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
  delete?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
  connect?: Prisma.ProjetoWhereUniqueInput | Prisma.ProjetoWhereUniqueInput[]
  update?: Prisma.ProjetoUpdateWithWhereUniqueWithoutProponenteInput | Prisma.ProjetoUpdateWithWhereUniqueWithoutProponenteInput[]
  updateMany?: Prisma.ProjetoUpdateManyWithWhereWithoutProponenteInput | Prisma.ProjetoUpdateManyWithWhereWithoutProponenteInput[]
  deleteMany?: Prisma.ProjetoScalarWhereInput | Prisma.ProjetoScalarWhereInput[]
}

export type ProjetoCreateNestedOneWithoutPlanoTrabalhoInput = {
  create?: Prisma.XOR<Prisma.ProjetoCreateWithoutPlanoTrabalhoInput, Prisma.ProjetoUncheckedCreateWithoutPlanoTrabalhoInput>
  connectOrCreate?: Prisma.ProjetoCreateOrConnectWithoutPlanoTrabalhoInput
  connect?: Prisma.ProjetoWhereUniqueInput
}

export type ProjetoUpdateOneRequiredWithoutPlanoTrabalhoNestedInput = {
  create?: Prisma.XOR<Prisma.ProjetoCreateWithoutPlanoTrabalhoInput, Prisma.ProjetoUncheckedCreateWithoutPlanoTrabalhoInput>
  connectOrCreate?: Prisma.ProjetoCreateOrConnectWithoutPlanoTrabalhoInput
  upsert?: Prisma.ProjetoUpsertWithoutPlanoTrabalhoInput
  connect?: Prisma.ProjetoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjetoUpdateToOneWithWhereWithoutPlanoTrabalhoInput, Prisma.ProjetoUpdateWithoutPlanoTrabalhoInput>, Prisma.ProjetoUncheckedUpdateWithoutPlanoTrabalhoInput>
}

export type ProjetoCreateWithoutProponenteInput = {
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  createdAt?: Date | string
  updatedAt?: Date | string
  planoTrabalho?: Prisma.PlanoTrabalhoCreateNestedOneWithoutProjetoInput
}

export type ProjetoUncheckedCreateWithoutProponenteInput = {
  id?: number
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  createdAt?: Date | string
  updatedAt?: Date | string
  planoTrabalho?: Prisma.PlanoTrabalhoUncheckedCreateNestedOneWithoutProjetoInput
}

export type ProjetoCreateOrConnectWithoutProponenteInput = {
  where: Prisma.ProjetoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjetoCreateWithoutProponenteInput, Prisma.ProjetoUncheckedCreateWithoutProponenteInput>
}

export type ProjetoCreateManyProponenteInputEnvelope = {
  data: Prisma.ProjetoCreateManyProponenteInput | Prisma.ProjetoCreateManyProponenteInput[]
  skipDuplicates?: boolean
}

export type ProjetoUpsertWithWhereUniqueWithoutProponenteInput = {
  where: Prisma.ProjetoWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjetoUpdateWithoutProponenteInput, Prisma.ProjetoUncheckedUpdateWithoutProponenteInput>
  create: Prisma.XOR<Prisma.ProjetoCreateWithoutProponenteInput, Prisma.ProjetoUncheckedCreateWithoutProponenteInput>
}

export type ProjetoUpdateWithWhereUniqueWithoutProponenteInput = {
  where: Prisma.ProjetoWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjetoUpdateWithoutProponenteInput, Prisma.ProjetoUncheckedUpdateWithoutProponenteInput>
}

export type ProjetoUpdateManyWithWhereWithoutProponenteInput = {
  where: Prisma.ProjetoScalarWhereInput
  data: Prisma.XOR<Prisma.ProjetoUpdateManyMutationInput, Prisma.ProjetoUncheckedUpdateManyWithoutProponenteInput>
}

export type ProjetoScalarWhereInput = {
  AND?: Prisma.ProjetoScalarWhereInput | Prisma.ProjetoScalarWhereInput[]
  OR?: Prisma.ProjetoScalarWhereInput[]
  NOT?: Prisma.ProjetoScalarWhereInput | Prisma.ProjetoScalarWhereInput[]
  id?: Prisma.IntFilter<"Projeto"> | number
  titulo?: Prisma.StringFilter<"Projeto"> | string
  objetivos?: Prisma.StringFilter<"Projeto"> | string
  justificativa?: Prisma.StringFilter<"Projeto"> | string
  abrangencia?: Prisma.StringFilter<"Projeto"> | string
  proponenteId?: Prisma.IntFilter<"Projeto"> | number
  createdAt?: Prisma.DateTimeFilter<"Projeto"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Projeto"> | Date | string
}

export type ProjetoCreateWithoutPlanoTrabalhoInput = {
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  createdAt?: Date | string
  updatedAt?: Date | string
  proponente: Prisma.ProponenteCreateNestedOneWithoutProjetosInput
}

export type ProjetoUncheckedCreateWithoutPlanoTrabalhoInput = {
  id?: number
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  proponenteId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjetoCreateOrConnectWithoutPlanoTrabalhoInput = {
  where: Prisma.ProjetoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjetoCreateWithoutPlanoTrabalhoInput, Prisma.ProjetoUncheckedCreateWithoutPlanoTrabalhoInput>
}

export type ProjetoUpsertWithoutPlanoTrabalhoInput = {
  update: Prisma.XOR<Prisma.ProjetoUpdateWithoutPlanoTrabalhoInput, Prisma.ProjetoUncheckedUpdateWithoutPlanoTrabalhoInput>
  create: Prisma.XOR<Prisma.ProjetoCreateWithoutPlanoTrabalhoInput, Prisma.ProjetoUncheckedCreateWithoutPlanoTrabalhoInput>
  where?: Prisma.ProjetoWhereInput
}

export type ProjetoUpdateToOneWithWhereWithoutPlanoTrabalhoInput = {
  where?: Prisma.ProjetoWhereInput
  data: Prisma.XOR<Prisma.ProjetoUpdateWithoutPlanoTrabalhoInput, Prisma.ProjetoUncheckedUpdateWithoutPlanoTrabalhoInput>
}

export type ProjetoUpdateWithoutPlanoTrabalhoInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  proponente?: Prisma.ProponenteUpdateOneRequiredWithoutProjetosNestedInput
}

export type ProjetoUncheckedUpdateWithoutPlanoTrabalhoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  proponenteId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjetoCreateManyProponenteInput = {
  id?: number
  titulo: string
  objetivos: string
  justificativa: string
  abrangencia: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjetoUpdateWithoutProponenteInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  planoTrabalho?: Prisma.PlanoTrabalhoUpdateOneWithoutProjetoNestedInput
}

export type ProjetoUncheckedUpdateWithoutProponenteInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  planoTrabalho?: Prisma.PlanoTrabalhoUncheckedUpdateOneWithoutProjetoNestedInput
}

export type ProjetoUncheckedUpdateManyWithoutProponenteInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  objetivos?: Prisma.StringFieldUpdateOperationsInput | string
  justificativa?: Prisma.StringFieldUpdateOperationsInput | string
  abrangencia?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProjetoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titulo?: boolean
  objetivos?: boolean
  justificativa?: boolean
  abrangencia?: boolean
  proponenteId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  proponente?: boolean | Prisma.ProponenteDefaultArgs<ExtArgs>
  planoTrabalho?: boolean | Prisma.Projeto$planoTrabalhoArgs<ExtArgs>
}, ExtArgs["result"]["projeto"]>

export type ProjetoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titulo?: boolean
  objetivos?: boolean
  justificativa?: boolean
  abrangencia?: boolean
  proponenteId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  proponente?: boolean | Prisma.ProponenteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projeto"]>

export type ProjetoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titulo?: boolean
  objetivos?: boolean
  justificativa?: boolean
  abrangencia?: boolean
  proponenteId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  proponente?: boolean | Prisma.ProponenteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projeto"]>

export type ProjetoSelectScalar = {
  id?: boolean
  titulo?: boolean
  objetivos?: boolean
  justificativa?: boolean
  abrangencia?: boolean
  proponenteId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProjetoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "titulo" | "objetivos" | "justificativa" | "abrangencia" | "proponenteId" | "createdAt" | "updatedAt", ExtArgs["result"]["projeto"]>
export type ProjetoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  proponente?: boolean | Prisma.ProponenteDefaultArgs<ExtArgs>
  planoTrabalho?: boolean | Prisma.Projeto$planoTrabalhoArgs<ExtArgs>
}
export type ProjetoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  proponente?: boolean | Prisma.ProponenteDefaultArgs<ExtArgs>
}
export type ProjetoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  proponente?: boolean | Prisma.ProponenteDefaultArgs<ExtArgs>
}

export type $ProjetoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Projeto"
  objects: {
    proponente: Prisma.$ProponentePayload<ExtArgs>
    planoTrabalho: Prisma.$PlanoTrabalhoPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    titulo: string
    objetivos: string
    justificativa: string
    abrangencia: string
    proponenteId: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["projeto"]>
  composites: {}
}

export type ProjetoGetPayload<S extends boolean | null | undefined | ProjetoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjetoPayload, S>

export type ProjetoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjetoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjetoCountAggregateInputType | true
  }

export interface ProjetoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Projeto'], meta: { name: 'Projeto' } }
  /**
   * Find zero or one Projeto that matches the filter.
   * @param {ProjetoFindUniqueArgs} args - Arguments to find a Projeto
   * @example
   * // Get one Projeto
   * const projeto = await prisma.projeto.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjetoFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjetoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjetoClient<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Projeto that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjetoFindUniqueOrThrowArgs} args - Arguments to find a Projeto
   * @example
   * // Get one Projeto
   * const projeto = await prisma.projeto.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjetoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjetoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjetoClient<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Projeto that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjetoFindFirstArgs} args - Arguments to find a Projeto
   * @example
   * // Get one Projeto
   * const projeto = await prisma.projeto.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjetoFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjetoFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjetoClient<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Projeto that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjetoFindFirstOrThrowArgs} args - Arguments to find a Projeto
   * @example
   * // Get one Projeto
   * const projeto = await prisma.projeto.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjetoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjetoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjetoClient<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Projetos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjetoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Projetos
   * const projetos = await prisma.projeto.findMany()
   * 
   * // Get first 10 Projetos
   * const projetos = await prisma.projeto.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projetoWithIdOnly = await prisma.projeto.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjetoFindManyArgs>(args?: Prisma.SelectSubset<T, ProjetoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Projeto.
   * @param {ProjetoCreateArgs} args - Arguments to create a Projeto.
   * @example
   * // Create one Projeto
   * const Projeto = await prisma.projeto.create({
   *   data: {
   *     // ... data to create a Projeto
   *   }
   * })
   * 
   */
  create<T extends ProjetoCreateArgs>(args: Prisma.SelectSubset<T, ProjetoCreateArgs<ExtArgs>>): Prisma.Prisma__ProjetoClient<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Projetos.
   * @param {ProjetoCreateManyArgs} args - Arguments to create many Projetos.
   * @example
   * // Create many Projetos
   * const projeto = await prisma.projeto.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjetoCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjetoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Projetos and returns the data saved in the database.
   * @param {ProjetoCreateManyAndReturnArgs} args - Arguments to create many Projetos.
   * @example
   * // Create many Projetos
   * const projeto = await prisma.projeto.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Projetos and only return the `id`
   * const projetoWithIdOnly = await prisma.projeto.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjetoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjetoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Projeto.
   * @param {ProjetoDeleteArgs} args - Arguments to delete one Projeto.
   * @example
   * // Delete one Projeto
   * const Projeto = await prisma.projeto.delete({
   *   where: {
   *     // ... filter to delete one Projeto
   *   }
   * })
   * 
   */
  delete<T extends ProjetoDeleteArgs>(args: Prisma.SelectSubset<T, ProjetoDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjetoClient<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Projeto.
   * @param {ProjetoUpdateArgs} args - Arguments to update one Projeto.
   * @example
   * // Update one Projeto
   * const projeto = await prisma.projeto.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjetoUpdateArgs>(args: Prisma.SelectSubset<T, ProjetoUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjetoClient<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Projetos.
   * @param {ProjetoDeleteManyArgs} args - Arguments to filter Projetos to delete.
   * @example
   * // Delete a few Projetos
   * const { count } = await prisma.projeto.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjetoDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjetoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projetos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjetoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Projetos
   * const projeto = await prisma.projeto.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjetoUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjetoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projetos and returns the data updated in the database.
   * @param {ProjetoUpdateManyAndReturnArgs} args - Arguments to update many Projetos.
   * @example
   * // Update many Projetos
   * const projeto = await prisma.projeto.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Projetos and only return the `id`
   * const projetoWithIdOnly = await prisma.projeto.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjetoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjetoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Projeto.
   * @param {ProjetoUpsertArgs} args - Arguments to update or create a Projeto.
   * @example
   * // Update or create a Projeto
   * const projeto = await prisma.projeto.upsert({
   *   create: {
   *     // ... data to create a Projeto
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Projeto we want to update
   *   }
   * })
   */
  upsert<T extends ProjetoUpsertArgs>(args: Prisma.SelectSubset<T, ProjetoUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjetoClient<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Projetos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjetoCountArgs} args - Arguments to filter Projetos to count.
   * @example
   * // Count the number of Projetos
   * const count = await prisma.projeto.count({
   *   where: {
   *     // ... the filter for the Projetos we want to count
   *   }
   * })
  **/
  count<T extends ProjetoCountArgs>(
    args?: Prisma.Subset<T, ProjetoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjetoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Projeto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjetoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjetoAggregateArgs>(args: Prisma.Subset<T, ProjetoAggregateArgs>): Prisma.PrismaPromise<GetProjetoAggregateType<T>>

  /**
   * Group by Projeto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjetoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjetoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjetoGroupByArgs['orderBy'] }
      : { orderBy?: ProjetoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjetoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjetoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Projeto model
 */
readonly fields: ProjetoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Projeto.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjetoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  proponente<T extends Prisma.ProponenteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProponenteDefaultArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  planoTrabalho<T extends Prisma.Projeto$planoTrabalhoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Projeto$planoTrabalhoArgs<ExtArgs>>): Prisma.Prisma__PlanoTrabalhoClient<runtime.Types.Result.GetResult<Prisma.$PlanoTrabalhoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Projeto model
 */
export interface ProjetoFieldRefs {
  readonly id: Prisma.FieldRef<"Projeto", 'Int'>
  readonly titulo: Prisma.FieldRef<"Projeto", 'String'>
  readonly objetivos: Prisma.FieldRef<"Projeto", 'String'>
  readonly justificativa: Prisma.FieldRef<"Projeto", 'String'>
  readonly abrangencia: Prisma.FieldRef<"Projeto", 'String'>
  readonly proponenteId: Prisma.FieldRef<"Projeto", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Projeto", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Projeto", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Projeto findUnique
 */
export type ProjetoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * Filter, which Projeto to fetch.
   */
  where: Prisma.ProjetoWhereUniqueInput
}

/**
 * Projeto findUniqueOrThrow
 */
export type ProjetoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * Filter, which Projeto to fetch.
   */
  where: Prisma.ProjetoWhereUniqueInput
}

/**
 * Projeto findFirst
 */
export type ProjetoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * Filter, which Projeto to fetch.
   */
  where?: Prisma.ProjetoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projetos to fetch.
   */
  orderBy?: Prisma.ProjetoOrderByWithRelationInput | Prisma.ProjetoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projetos.
   */
  cursor?: Prisma.ProjetoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projetos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projetos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projetos.
   */
  distinct?: Prisma.ProjetoScalarFieldEnum | Prisma.ProjetoScalarFieldEnum[]
}

/**
 * Projeto findFirstOrThrow
 */
export type ProjetoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * Filter, which Projeto to fetch.
   */
  where?: Prisma.ProjetoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projetos to fetch.
   */
  orderBy?: Prisma.ProjetoOrderByWithRelationInput | Prisma.ProjetoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projetos.
   */
  cursor?: Prisma.ProjetoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projetos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projetos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projetos.
   */
  distinct?: Prisma.ProjetoScalarFieldEnum | Prisma.ProjetoScalarFieldEnum[]
}

/**
 * Projeto findMany
 */
export type ProjetoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * Filter, which Projetos to fetch.
   */
  where?: Prisma.ProjetoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projetos to fetch.
   */
  orderBy?: Prisma.ProjetoOrderByWithRelationInput | Prisma.ProjetoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Projetos.
   */
  cursor?: Prisma.ProjetoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projetos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projetos.
   */
  skip?: number
  distinct?: Prisma.ProjetoScalarFieldEnum | Prisma.ProjetoScalarFieldEnum[]
}

/**
 * Projeto create
 */
export type ProjetoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * The data needed to create a Projeto.
   */
  data: Prisma.XOR<Prisma.ProjetoCreateInput, Prisma.ProjetoUncheckedCreateInput>
}

/**
 * Projeto createMany
 */
export type ProjetoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Projetos.
   */
  data: Prisma.ProjetoCreateManyInput | Prisma.ProjetoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Projeto createManyAndReturn
 */
export type ProjetoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * The data used to create many Projetos.
   */
  data: Prisma.ProjetoCreateManyInput | Prisma.ProjetoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Projeto update
 */
export type ProjetoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * The data needed to update a Projeto.
   */
  data: Prisma.XOR<Prisma.ProjetoUpdateInput, Prisma.ProjetoUncheckedUpdateInput>
  /**
   * Choose, which Projeto to update.
   */
  where: Prisma.ProjetoWhereUniqueInput
}

/**
 * Projeto updateMany
 */
export type ProjetoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Projetos.
   */
  data: Prisma.XOR<Prisma.ProjetoUpdateManyMutationInput, Prisma.ProjetoUncheckedUpdateManyInput>
  /**
   * Filter which Projetos to update
   */
  where?: Prisma.ProjetoWhereInput
  /**
   * Limit how many Projetos to update.
   */
  limit?: number
}

/**
 * Projeto updateManyAndReturn
 */
export type ProjetoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * The data used to update Projetos.
   */
  data: Prisma.XOR<Prisma.ProjetoUpdateManyMutationInput, Prisma.ProjetoUncheckedUpdateManyInput>
  /**
   * Filter which Projetos to update
   */
  where?: Prisma.ProjetoWhereInput
  /**
   * Limit how many Projetos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Projeto upsert
 */
export type ProjetoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * The filter to search for the Projeto to update in case it exists.
   */
  where: Prisma.ProjetoWhereUniqueInput
  /**
   * In case the Projeto found by the `where` argument doesn't exist, create a new Projeto with this data.
   */
  create: Prisma.XOR<Prisma.ProjetoCreateInput, Prisma.ProjetoUncheckedCreateInput>
  /**
   * In case the Projeto was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjetoUpdateInput, Prisma.ProjetoUncheckedUpdateInput>
}

/**
 * Projeto delete
 */
export type ProjetoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  /**
   * Filter which Projeto to delete.
   */
  where: Prisma.ProjetoWhereUniqueInput
}

/**
 * Projeto deleteMany
 */
export type ProjetoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Projetos to delete
   */
  where?: Prisma.ProjetoWhereInput
  /**
   * Limit how many Projetos to delete.
   */
  limit?: number
}

/**
 * Projeto.planoTrabalho
 */
export type Projeto$planoTrabalhoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlanoTrabalho
   */
  select?: Prisma.PlanoTrabalhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlanoTrabalho
   */
  omit?: Prisma.PlanoTrabalhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlanoTrabalhoInclude<ExtArgs> | null
  where?: Prisma.PlanoTrabalhoWhereInput
}

/**
 * Projeto without action
 */
export type ProjetoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
}
