
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Proponente` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Proponente
 * 
 */
export type ProponenteModel = runtime.Types.Result.DefaultSelection<Prisma.$ProponentePayload>

export type AggregateProponente = {
  _count: ProponenteCountAggregateOutputType | null
  _avg: ProponenteAvgAggregateOutputType | null
  _sum: ProponenteSumAggregateOutputType | null
  _min: ProponenteMinAggregateOutputType | null
  _max: ProponenteMaxAggregateOutputType | null
}

export type ProponenteAvgAggregateOutputType = {
  id: number | null
}

export type ProponenteSumAggregateOutputType = {
  id: number | null
}

export type ProponenteMinAggregateOutputType = {
  id: number | null
  nome: string | null
  email: string | null
  instituicao: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProponenteMaxAggregateOutputType = {
  id: number | null
  nome: string | null
  email: string | null
  instituicao: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProponenteCountAggregateOutputType = {
  id: number
  nome: number
  email: number
  instituicao: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProponenteAvgAggregateInputType = {
  id?: true
}

export type ProponenteSumAggregateInputType = {
  id?: true
}

export type ProponenteMinAggregateInputType = {
  id?: true
  nome?: true
  email?: true
  instituicao?: true
  createdAt?: true
  updatedAt?: true
}

export type ProponenteMaxAggregateInputType = {
  id?: true
  nome?: true
  email?: true
  instituicao?: true
  createdAt?: true
  updatedAt?: true
}

export type ProponenteCountAggregateInputType = {
  id?: true
  nome?: true
  email?: true
  instituicao?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProponenteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proponente to aggregate.
   */
  where?: Prisma.ProponenteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proponentes to fetch.
   */
  orderBy?: Prisma.ProponenteOrderByWithRelationInput | Prisma.ProponenteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProponenteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proponentes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proponentes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Proponentes
  **/
  _count?: true | ProponenteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProponenteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProponenteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProponenteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProponenteMaxAggregateInputType
}

export type GetProponenteAggregateType<T extends ProponenteAggregateArgs> = {
      [P in keyof T & keyof AggregateProponente]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProponente[P]>
    : Prisma.GetScalarType<T[P], AggregateProponente[P]>
}




export type ProponenteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProponenteWhereInput
  orderBy?: Prisma.ProponenteOrderByWithAggregationInput | Prisma.ProponenteOrderByWithAggregationInput[]
  by: Prisma.ProponenteScalarFieldEnum[] | Prisma.ProponenteScalarFieldEnum
  having?: Prisma.ProponenteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProponenteCountAggregateInputType | true
  _avg?: ProponenteAvgAggregateInputType
  _sum?: ProponenteSumAggregateInputType
  _min?: ProponenteMinAggregateInputType
  _max?: ProponenteMaxAggregateInputType
}

export type ProponenteGroupByOutputType = {
  id: number
  nome: string
  email: string
  instituicao: string | null
  createdAt: Date
  updatedAt: Date
  _count: ProponenteCountAggregateOutputType | null
  _avg: ProponenteAvgAggregateOutputType | null
  _sum: ProponenteSumAggregateOutputType | null
  _min: ProponenteMinAggregateOutputType | null
  _max: ProponenteMaxAggregateOutputType | null
}

type GetProponenteGroupByPayload<T extends ProponenteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProponenteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProponenteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProponenteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProponenteGroupByOutputType[P]>
      }
    >
  >



export type ProponenteWhereInput = {
  AND?: Prisma.ProponenteWhereInput | Prisma.ProponenteWhereInput[]
  OR?: Prisma.ProponenteWhereInput[]
  NOT?: Prisma.ProponenteWhereInput | Prisma.ProponenteWhereInput[]
  id?: Prisma.IntFilter<"Proponente"> | number
  nome?: Prisma.StringFilter<"Proponente"> | string
  email?: Prisma.StringFilter<"Proponente"> | string
  instituicao?: Prisma.StringNullableFilter<"Proponente"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Proponente"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Proponente"> | Date | string
  projetos?: Prisma.ProjetoListRelationFilter
}

export type ProponenteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  email?: Prisma.SortOrder
  instituicao?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projetos?: Prisma.ProjetoOrderByRelationAggregateInput
}

export type ProponenteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  email?: string
  AND?: Prisma.ProponenteWhereInput | Prisma.ProponenteWhereInput[]
  OR?: Prisma.ProponenteWhereInput[]
  NOT?: Prisma.ProponenteWhereInput | Prisma.ProponenteWhereInput[]
  nome?: Prisma.StringFilter<"Proponente"> | string
  instituicao?: Prisma.StringNullableFilter<"Proponente"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Proponente"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Proponente"> | Date | string
  projetos?: Prisma.ProjetoListRelationFilter
}, "id" | "email">

export type ProponenteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  email?: Prisma.SortOrder
  instituicao?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProponenteCountOrderByAggregateInput
  _avg?: Prisma.ProponenteAvgOrderByAggregateInput
  _max?: Prisma.ProponenteMaxOrderByAggregateInput
  _min?: Prisma.ProponenteMinOrderByAggregateInput
  _sum?: Prisma.ProponenteSumOrderByAggregateInput
}

export type ProponenteScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProponenteScalarWhereWithAggregatesInput | Prisma.ProponenteScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProponenteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProponenteScalarWhereWithAggregatesInput | Prisma.ProponenteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Proponente"> | number
  nome?: Prisma.StringWithAggregatesFilter<"Proponente"> | string
  email?: Prisma.StringWithAggregatesFilter<"Proponente"> | string
  instituicao?: Prisma.StringNullableWithAggregatesFilter<"Proponente"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Proponente"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Proponente"> | Date | string
}

export type ProponenteCreateInput = {
  nome: string
  email: string
  instituicao?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  projetos?: Prisma.ProjetoCreateNestedManyWithoutProponenteInput
}

export type ProponenteUncheckedCreateInput = {
  id?: number
  nome: string
  email: string
  instituicao?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  projetos?: Prisma.ProjetoUncheckedCreateNestedManyWithoutProponenteInput
}

export type ProponenteUpdateInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projetos?: Prisma.ProjetoUpdateManyWithoutProponenteNestedInput
}

export type ProponenteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projetos?: Prisma.ProjetoUncheckedUpdateManyWithoutProponenteNestedInput
}

export type ProponenteCreateManyInput = {
  id?: number
  nome: string
  email: string
  instituicao?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProponenteUpdateManyMutationInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProponenteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProponenteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  email?: Prisma.SortOrder
  instituicao?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProponenteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ProponenteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  email?: Prisma.SortOrder
  instituicao?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProponenteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  email?: Prisma.SortOrder
  instituicao?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProponenteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ProponenteScalarRelationFilter = {
  is?: Prisma.ProponenteWhereInput
  isNot?: Prisma.ProponenteWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ProponenteCreateNestedOneWithoutProjetosInput = {
  create?: Prisma.XOR<Prisma.ProponenteCreateWithoutProjetosInput, Prisma.ProponenteUncheckedCreateWithoutProjetosInput>
  connectOrCreate?: Prisma.ProponenteCreateOrConnectWithoutProjetosInput
  connect?: Prisma.ProponenteWhereUniqueInput
}

export type ProponenteUpdateOneRequiredWithoutProjetosNestedInput = {
  create?: Prisma.XOR<Prisma.ProponenteCreateWithoutProjetosInput, Prisma.ProponenteUncheckedCreateWithoutProjetosInput>
  connectOrCreate?: Prisma.ProponenteCreateOrConnectWithoutProjetosInput
  upsert?: Prisma.ProponenteUpsertWithoutProjetosInput
  connect?: Prisma.ProponenteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProponenteUpdateToOneWithWhereWithoutProjetosInput, Prisma.ProponenteUpdateWithoutProjetosInput>, Prisma.ProponenteUncheckedUpdateWithoutProjetosInput>
}

export type ProponenteCreateWithoutProjetosInput = {
  nome: string
  email: string
  instituicao?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProponenteUncheckedCreateWithoutProjetosInput = {
  id?: number
  nome: string
  email: string
  instituicao?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProponenteCreateOrConnectWithoutProjetosInput = {
  where: Prisma.ProponenteWhereUniqueInput
  create: Prisma.XOR<Prisma.ProponenteCreateWithoutProjetosInput, Prisma.ProponenteUncheckedCreateWithoutProjetosInput>
}

export type ProponenteUpsertWithoutProjetosInput = {
  update: Prisma.XOR<Prisma.ProponenteUpdateWithoutProjetosInput, Prisma.ProponenteUncheckedUpdateWithoutProjetosInput>
  create: Prisma.XOR<Prisma.ProponenteCreateWithoutProjetosInput, Prisma.ProponenteUncheckedCreateWithoutProjetosInput>
  where?: Prisma.ProponenteWhereInput
}

export type ProponenteUpdateToOneWithWhereWithoutProjetosInput = {
  where?: Prisma.ProponenteWhereInput
  data: Prisma.XOR<Prisma.ProponenteUpdateWithoutProjetosInput, Prisma.ProponenteUncheckedUpdateWithoutProjetosInput>
}

export type ProponenteUpdateWithoutProjetosInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProponenteUncheckedUpdateWithoutProjetosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  instituicao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProponenteCountOutputType
 */

export type ProponenteCountOutputType = {
  projetos: number
}

export type ProponenteCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projetos?: boolean | ProponenteCountOutputTypeCountProjetosArgs
}

/**
 * ProponenteCountOutputType without action
 */
export type ProponenteCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProponenteCountOutputType
   */
  select?: Prisma.ProponenteCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProponenteCountOutputType without action
 */
export type ProponenteCountOutputTypeCountProjetosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjetoWhereInput
}


export type ProponenteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  email?: boolean
  instituicao?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projetos?: boolean | Prisma.Proponente$projetosArgs<ExtArgs>
  _count?: boolean | Prisma.ProponenteCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proponente"]>

export type ProponenteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  email?: boolean
  instituicao?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["proponente"]>

export type ProponenteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  email?: boolean
  instituicao?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["proponente"]>

export type ProponenteSelectScalar = {
  id?: boolean
  nome?: boolean
  email?: boolean
  instituicao?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProponenteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "email" | "instituicao" | "createdAt" | "updatedAt", ExtArgs["result"]["proponente"]>
export type ProponenteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projetos?: boolean | Prisma.Proponente$projetosArgs<ExtArgs>
  _count?: boolean | Prisma.ProponenteCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProponenteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ProponenteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ProponentePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Proponente"
  objects: {
    projetos: Prisma.$ProjetoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nome: string
    email: string
    instituicao: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["proponente"]>
  composites: {}
}

export type ProponenteGetPayload<S extends boolean | null | undefined | ProponenteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProponentePayload, S>

export type ProponenteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProponenteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProponenteCountAggregateInputType | true
  }

export interface ProponenteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Proponente'], meta: { name: 'Proponente' } }
  /**
   * Find zero or one Proponente that matches the filter.
   * @param {ProponenteFindUniqueArgs} args - Arguments to find a Proponente
   * @example
   * // Get one Proponente
   * const proponente = await prisma.proponente.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProponenteFindUniqueArgs>(args: Prisma.SelectSubset<T, ProponenteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Proponente that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProponenteFindUniqueOrThrowArgs} args - Arguments to find a Proponente
   * @example
   * // Get one Proponente
   * const proponente = await prisma.proponente.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProponenteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProponenteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proponente that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponenteFindFirstArgs} args - Arguments to find a Proponente
   * @example
   * // Get one Proponente
   * const proponente = await prisma.proponente.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProponenteFindFirstArgs>(args?: Prisma.SelectSubset<T, ProponenteFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proponente that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponenteFindFirstOrThrowArgs} args - Arguments to find a Proponente
   * @example
   * // Get one Proponente
   * const proponente = await prisma.proponente.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProponenteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProponenteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Proponentes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponenteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Proponentes
   * const proponentes = await prisma.proponente.findMany()
   * 
   * // Get first 10 Proponentes
   * const proponentes = await prisma.proponente.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const proponenteWithIdOnly = await prisma.proponente.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProponenteFindManyArgs>(args?: Prisma.SelectSubset<T, ProponenteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Proponente.
   * @param {ProponenteCreateArgs} args - Arguments to create a Proponente.
   * @example
   * // Create one Proponente
   * const Proponente = await prisma.proponente.create({
   *   data: {
   *     // ... data to create a Proponente
   *   }
   * })
   * 
   */
  create<T extends ProponenteCreateArgs>(args: Prisma.SelectSubset<T, ProponenteCreateArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Proponentes.
   * @param {ProponenteCreateManyArgs} args - Arguments to create many Proponentes.
   * @example
   * // Create many Proponentes
   * const proponente = await prisma.proponente.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProponenteCreateManyArgs>(args?: Prisma.SelectSubset<T, ProponenteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Proponentes and returns the data saved in the database.
   * @param {ProponenteCreateManyAndReturnArgs} args - Arguments to create many Proponentes.
   * @example
   * // Create many Proponentes
   * const proponente = await prisma.proponente.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Proponentes and only return the `id`
   * const proponenteWithIdOnly = await prisma.proponente.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProponenteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProponenteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Proponente.
   * @param {ProponenteDeleteArgs} args - Arguments to delete one Proponente.
   * @example
   * // Delete one Proponente
   * const Proponente = await prisma.proponente.delete({
   *   where: {
   *     // ... filter to delete one Proponente
   *   }
   * })
   * 
   */
  delete<T extends ProponenteDeleteArgs>(args: Prisma.SelectSubset<T, ProponenteDeleteArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Proponente.
   * @param {ProponenteUpdateArgs} args - Arguments to update one Proponente.
   * @example
   * // Update one Proponente
   * const proponente = await prisma.proponente.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProponenteUpdateArgs>(args: Prisma.SelectSubset<T, ProponenteUpdateArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Proponentes.
   * @param {ProponenteDeleteManyArgs} args - Arguments to filter Proponentes to delete.
   * @example
   * // Delete a few Proponentes
   * const { count } = await prisma.proponente.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProponenteDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProponenteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proponentes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponenteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Proponentes
   * const proponente = await prisma.proponente.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProponenteUpdateManyArgs>(args: Prisma.SelectSubset<T, ProponenteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proponentes and returns the data updated in the database.
   * @param {ProponenteUpdateManyAndReturnArgs} args - Arguments to update many Proponentes.
   * @example
   * // Update many Proponentes
   * const proponente = await prisma.proponente.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Proponentes and only return the `id`
   * const proponenteWithIdOnly = await prisma.proponente.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProponenteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProponenteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Proponente.
   * @param {ProponenteUpsertArgs} args - Arguments to update or create a Proponente.
   * @example
   * // Update or create a Proponente
   * const proponente = await prisma.proponente.upsert({
   *   create: {
   *     // ... data to create a Proponente
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Proponente we want to update
   *   }
   * })
   */
  upsert<T extends ProponenteUpsertArgs>(args: Prisma.SelectSubset<T, ProponenteUpsertArgs<ExtArgs>>): Prisma.Prisma__ProponenteClient<runtime.Types.Result.GetResult<Prisma.$ProponentePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Proponentes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponenteCountArgs} args - Arguments to filter Proponentes to count.
   * @example
   * // Count the number of Proponentes
   * const count = await prisma.proponente.count({
   *   where: {
   *     // ... the filter for the Proponentes we want to count
   *   }
   * })
  **/
  count<T extends ProponenteCountArgs>(
    args?: Prisma.Subset<T, ProponenteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProponenteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Proponente.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponenteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProponenteAggregateArgs>(args: Prisma.Subset<T, ProponenteAggregateArgs>): Prisma.PrismaPromise<GetProponenteAggregateType<T>>

  /**
   * Group by Proponente.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponenteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProponenteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProponenteGroupByArgs['orderBy'] }
      : { orderBy?: ProponenteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProponenteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProponenteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Proponente model
 */
readonly fields: ProponenteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Proponente.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProponenteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  projetos<T extends Prisma.Proponente$projetosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proponente$projetosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjetoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Proponente model
 */
export interface ProponenteFieldRefs {
  readonly id: Prisma.FieldRef<"Proponente", 'Int'>
  readonly nome: Prisma.FieldRef<"Proponente", 'String'>
  readonly email: Prisma.FieldRef<"Proponente", 'String'>
  readonly instituicao: Prisma.FieldRef<"Proponente", 'String'>
  readonly createdAt: Prisma.FieldRef<"Proponente", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Proponente", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Proponente findUnique
 */
export type ProponenteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * Filter, which Proponente to fetch.
   */
  where: Prisma.ProponenteWhereUniqueInput
}

/**
 * Proponente findUniqueOrThrow
 */
export type ProponenteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * Filter, which Proponente to fetch.
   */
  where: Prisma.ProponenteWhereUniqueInput
}

/**
 * Proponente findFirst
 */
export type ProponenteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * Filter, which Proponente to fetch.
   */
  where?: Prisma.ProponenteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proponentes to fetch.
   */
  orderBy?: Prisma.ProponenteOrderByWithRelationInput | Prisma.ProponenteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proponentes.
   */
  cursor?: Prisma.ProponenteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proponentes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proponentes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proponentes.
   */
  distinct?: Prisma.ProponenteScalarFieldEnum | Prisma.ProponenteScalarFieldEnum[]
}

/**
 * Proponente findFirstOrThrow
 */
export type ProponenteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * Filter, which Proponente to fetch.
   */
  where?: Prisma.ProponenteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proponentes to fetch.
   */
  orderBy?: Prisma.ProponenteOrderByWithRelationInput | Prisma.ProponenteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proponentes.
   */
  cursor?: Prisma.ProponenteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proponentes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proponentes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proponentes.
   */
  distinct?: Prisma.ProponenteScalarFieldEnum | Prisma.ProponenteScalarFieldEnum[]
}

/**
 * Proponente findMany
 */
export type ProponenteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * Filter, which Proponentes to fetch.
   */
  where?: Prisma.ProponenteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proponentes to fetch.
   */
  orderBy?: Prisma.ProponenteOrderByWithRelationInput | Prisma.ProponenteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Proponentes.
   */
  cursor?: Prisma.ProponenteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proponentes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proponentes.
   */
  skip?: number
  distinct?: Prisma.ProponenteScalarFieldEnum | Prisma.ProponenteScalarFieldEnum[]
}

/**
 * Proponente create
 */
export type ProponenteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * The data needed to create a Proponente.
   */
  data: Prisma.XOR<Prisma.ProponenteCreateInput, Prisma.ProponenteUncheckedCreateInput>
}

/**
 * Proponente createMany
 */
export type ProponenteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Proponentes.
   */
  data: Prisma.ProponenteCreateManyInput | Prisma.ProponenteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Proponente createManyAndReturn
 */
export type ProponenteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * The data used to create many Proponentes.
   */
  data: Prisma.ProponenteCreateManyInput | Prisma.ProponenteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Proponente update
 */
export type ProponenteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * The data needed to update a Proponente.
   */
  data: Prisma.XOR<Prisma.ProponenteUpdateInput, Prisma.ProponenteUncheckedUpdateInput>
  /**
   * Choose, which Proponente to update.
   */
  where: Prisma.ProponenteWhereUniqueInput
}

/**
 * Proponente updateMany
 */
export type ProponenteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Proponentes.
   */
  data: Prisma.XOR<Prisma.ProponenteUpdateManyMutationInput, Prisma.ProponenteUncheckedUpdateManyInput>
  /**
   * Filter which Proponentes to update
   */
  where?: Prisma.ProponenteWhereInput
  /**
   * Limit how many Proponentes to update.
   */
  limit?: number
}

/**
 * Proponente updateManyAndReturn
 */
export type ProponenteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * The data used to update Proponentes.
   */
  data: Prisma.XOR<Prisma.ProponenteUpdateManyMutationInput, Prisma.ProponenteUncheckedUpdateManyInput>
  /**
   * Filter which Proponentes to update
   */
  where?: Prisma.ProponenteWhereInput
  /**
   * Limit how many Proponentes to update.
   */
  limit?: number
}

/**
 * Proponente upsert
 */
export type ProponenteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * The filter to search for the Proponente to update in case it exists.
   */
  where: Prisma.ProponenteWhereUniqueInput
  /**
   * In case the Proponente found by the `where` argument doesn't exist, create a new Proponente with this data.
   */
  create: Prisma.XOR<Prisma.ProponenteCreateInput, Prisma.ProponenteUncheckedCreateInput>
  /**
   * In case the Proponente was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProponenteUpdateInput, Prisma.ProponenteUncheckedUpdateInput>
}

/**
 * Proponente delete
 */
export type ProponenteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
  /**
   * Filter which Proponente to delete.
   */
  where: Prisma.ProponenteWhereUniqueInput
}

/**
 * Proponente deleteMany
 */
export type ProponenteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proponentes to delete
   */
  where?: Prisma.ProponenteWhereInput
  /**
   * Limit how many Proponentes to delete.
   */
  limit?: number
}

/**
 * Proponente.projetos
 */
export type Proponente$projetosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Projeto
   */
  select?: Prisma.ProjetoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Projeto
   */
  omit?: Prisma.ProjetoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjetoInclude<ExtArgs> | null
  where?: Prisma.ProjetoWhereInput
  orderBy?: Prisma.ProjetoOrderByWithRelationInput | Prisma.ProjetoOrderByWithRelationInput[]
  cursor?: Prisma.ProjetoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProjetoScalarFieldEnum | Prisma.ProjetoScalarFieldEnum[]
}

/**
 * Proponente without action
 */
export type ProponenteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponente
   */
  select?: Prisma.ProponenteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponente
   */
  omit?: Prisma.ProponenteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponenteInclude<ExtArgs> | null
}
