
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Proponent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Proponent
 * 
 */
export type ProponentModel = runtime.Types.Result.DefaultSelection<Prisma.$ProponentPayload>

export type AggregateProponent = {
  _count: ProponentCountAggregateOutputType | null
  _avg: ProponentAvgAggregateOutputType | null
  _sum: ProponentSumAggregateOutputType | null
  _min: ProponentMinAggregateOutputType | null
  _max: ProponentMaxAggregateOutputType | null
}

export type ProponentAvgAggregateOutputType = {
  id: number | null
}

export type ProponentSumAggregateOutputType = {
  id: number | null
}

export type ProponentMinAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  institution: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProponentMaxAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  institution: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProponentCountAggregateOutputType = {
  id: number
  name: number
  email: number
  institution: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProponentAvgAggregateInputType = {
  id?: true
}

export type ProponentSumAggregateInputType = {
  id?: true
}

export type ProponentMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  institution?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type ProponentMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  institution?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type ProponentCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  institution?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProponentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proponent to aggregate.
   */
  where?: Prisma.ProponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proponents to fetch.
   */
  orderBy?: Prisma.ProponentOrderByWithRelationInput | Prisma.ProponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Proponents
  **/
  _count?: true | ProponentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProponentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProponentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProponentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProponentMaxAggregateInputType
}

export type GetProponentAggregateType<T extends ProponentAggregateArgs> = {
      [P in keyof T & keyof AggregateProponent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProponent[P]>
    : Prisma.GetScalarType<T[P], AggregateProponent[P]>
}




export type ProponentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProponentWhereInput
  orderBy?: Prisma.ProponentOrderByWithAggregationInput | Prisma.ProponentOrderByWithAggregationInput[]
  by: Prisma.ProponentScalarFieldEnum[] | Prisma.ProponentScalarFieldEnum
  having?: Prisma.ProponentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProponentCountAggregateInputType | true
  _avg?: ProponentAvgAggregateInputType
  _sum?: ProponentSumAggregateInputType
  _min?: ProponentMinAggregateInputType
  _max?: ProponentMaxAggregateInputType
}

export type ProponentGroupByOutputType = {
  id: number
  name: string
  email: string
  institution: string | null
  userId: string | null
  createdAt: Date
  updatedAt: Date
  _count: ProponentCountAggregateOutputType | null
  _avg: ProponentAvgAggregateOutputType | null
  _sum: ProponentSumAggregateOutputType | null
  _min: ProponentMinAggregateOutputType | null
  _max: ProponentMaxAggregateOutputType | null
}

type GetProponentGroupByPayload<T extends ProponentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProponentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProponentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProponentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProponentGroupByOutputType[P]>
      }
    >
  >



export type ProponentWhereInput = {
  AND?: Prisma.ProponentWhereInput | Prisma.ProponentWhereInput[]
  OR?: Prisma.ProponentWhereInput[]
  NOT?: Prisma.ProponentWhereInput | Prisma.ProponentWhereInput[]
  id?: Prisma.IntFilter<"Proponent"> | number
  name?: Prisma.StringFilter<"Proponent"> | string
  email?: Prisma.StringFilter<"Proponent"> | string
  institution?: Prisma.StringNullableFilter<"Proponent"> | string | null
  userId?: Prisma.StringNullableFilter<"Proponent"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Proponent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Proponent"> | Date | string
  projects?: Prisma.ProjectListRelationFilter
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type ProponentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  institution?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projects?: Prisma.ProjectOrderByRelationAggregateInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type ProponentWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  email?: string
  userId?: string
  AND?: Prisma.ProponentWhereInput | Prisma.ProponentWhereInput[]
  OR?: Prisma.ProponentWhereInput[]
  NOT?: Prisma.ProponentWhereInput | Prisma.ProponentWhereInput[]
  name?: Prisma.StringFilter<"Proponent"> | string
  institution?: Prisma.StringNullableFilter<"Proponent"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Proponent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Proponent"> | Date | string
  projects?: Prisma.ProjectListRelationFilter
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "email" | "userId">

export type ProponentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  institution?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProponentCountOrderByAggregateInput
  _avg?: Prisma.ProponentAvgOrderByAggregateInput
  _max?: Prisma.ProponentMaxOrderByAggregateInput
  _min?: Prisma.ProponentMinOrderByAggregateInput
  _sum?: Prisma.ProponentSumOrderByAggregateInput
}

export type ProponentScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProponentScalarWhereWithAggregatesInput | Prisma.ProponentScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProponentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProponentScalarWhereWithAggregatesInput | Prisma.ProponentScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Proponent"> | number
  name?: Prisma.StringWithAggregatesFilter<"Proponent"> | string
  email?: Prisma.StringWithAggregatesFilter<"Proponent"> | string
  institution?: Prisma.StringNullableWithAggregatesFilter<"Proponent"> | string | null
  userId?: Prisma.StringNullableWithAggregatesFilter<"Proponent"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Proponent"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Proponent"> | Date | string
}

export type ProponentCreateInput = {
  name: string
  email: string
  institution?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  projects?: Prisma.ProjectCreateNestedManyWithoutProponentInput
  user?: Prisma.UserCreateNestedOneWithoutProponentInput
}

export type ProponentUncheckedCreateInput = {
  id?: number
  name: string
  email: string
  institution?: string | null
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutProponentInput
}

export type ProponentUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  institution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projects?: Prisma.ProjectUpdateManyWithoutProponentNestedInput
  user?: Prisma.UserUpdateOneWithoutProponentNestedInput
}

export type ProponentUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  institution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutProponentNestedInput
}

export type ProponentCreateManyInput = {
  id?: number
  name: string
  email: string
  institution?: string | null
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProponentUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  institution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProponentUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  institution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProponentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  institution?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProponentAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ProponentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  institution?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProponentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  institution?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProponentSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ProponentScalarRelationFilter = {
  is?: Prisma.ProponentWhereInput
  isNot?: Prisma.ProponentWhereInput
}

export type ProponentNullableScalarRelationFilter = {
  is?: Prisma.ProponentWhereInput | null
  isNot?: Prisma.ProponentWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ProponentCreateNestedOneWithoutProjectsInput = {
  create?: Prisma.XOR<Prisma.ProponentCreateWithoutProjectsInput, Prisma.ProponentUncheckedCreateWithoutProjectsInput>
  connectOrCreate?: Prisma.ProponentCreateOrConnectWithoutProjectsInput
  connect?: Prisma.ProponentWhereUniqueInput
}

export type ProponentUpdateOneRequiredWithoutProjectsNestedInput = {
  create?: Prisma.XOR<Prisma.ProponentCreateWithoutProjectsInput, Prisma.ProponentUncheckedCreateWithoutProjectsInput>
  connectOrCreate?: Prisma.ProponentCreateOrConnectWithoutProjectsInput
  upsert?: Prisma.ProponentUpsertWithoutProjectsInput
  connect?: Prisma.ProponentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProponentUpdateToOneWithWhereWithoutProjectsInput, Prisma.ProponentUpdateWithoutProjectsInput>, Prisma.ProponentUncheckedUpdateWithoutProjectsInput>
}

export type ProponentCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProponentCreateWithoutUserInput, Prisma.ProponentUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProponentCreateOrConnectWithoutUserInput
  connect?: Prisma.ProponentWhereUniqueInput
}

export type ProponentUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProponentCreateWithoutUserInput, Prisma.ProponentUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProponentCreateOrConnectWithoutUserInput
  connect?: Prisma.ProponentWhereUniqueInput
}

export type ProponentUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProponentCreateWithoutUserInput, Prisma.ProponentUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProponentCreateOrConnectWithoutUserInput
  upsert?: Prisma.ProponentUpsertWithoutUserInput
  disconnect?: Prisma.ProponentWhereInput | boolean
  delete?: Prisma.ProponentWhereInput | boolean
  connect?: Prisma.ProponentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProponentUpdateToOneWithWhereWithoutUserInput, Prisma.ProponentUpdateWithoutUserInput>, Prisma.ProponentUncheckedUpdateWithoutUserInput>
}

export type ProponentUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProponentCreateWithoutUserInput, Prisma.ProponentUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProponentCreateOrConnectWithoutUserInput
  upsert?: Prisma.ProponentUpsertWithoutUserInput
  disconnect?: Prisma.ProponentWhereInput | boolean
  delete?: Prisma.ProponentWhereInput | boolean
  connect?: Prisma.ProponentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProponentUpdateToOneWithWhereWithoutUserInput, Prisma.ProponentUpdateWithoutUserInput>, Prisma.ProponentUncheckedUpdateWithoutUserInput>
}

export type ProponentCreateWithoutProjectsInput = {
  name: string
  email: string
  institution?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutProponentInput
}

export type ProponentUncheckedCreateWithoutProjectsInput = {
  id?: number
  name: string
  email: string
  institution?: string | null
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProponentCreateOrConnectWithoutProjectsInput = {
  where: Prisma.ProponentWhereUniqueInput
  create: Prisma.XOR<Prisma.ProponentCreateWithoutProjectsInput, Prisma.ProponentUncheckedCreateWithoutProjectsInput>
}

export type ProponentUpsertWithoutProjectsInput = {
  update: Prisma.XOR<Prisma.ProponentUpdateWithoutProjectsInput, Prisma.ProponentUncheckedUpdateWithoutProjectsInput>
  create: Prisma.XOR<Prisma.ProponentCreateWithoutProjectsInput, Prisma.ProponentUncheckedCreateWithoutProjectsInput>
  where?: Prisma.ProponentWhereInput
}

export type ProponentUpdateToOneWithWhereWithoutProjectsInput = {
  where?: Prisma.ProponentWhereInput
  data: Prisma.XOR<Prisma.ProponentUpdateWithoutProjectsInput, Prisma.ProponentUncheckedUpdateWithoutProjectsInput>
}

export type ProponentUpdateWithoutProjectsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  institution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutProponentNestedInput
}

export type ProponentUncheckedUpdateWithoutProjectsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  institution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProponentCreateWithoutUserInput = {
  name: string
  email: string
  institution?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  projects?: Prisma.ProjectCreateNestedManyWithoutProponentInput
}

export type ProponentUncheckedCreateWithoutUserInput = {
  id?: number
  name: string
  email: string
  institution?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutProponentInput
}

export type ProponentCreateOrConnectWithoutUserInput = {
  where: Prisma.ProponentWhereUniqueInput
  create: Prisma.XOR<Prisma.ProponentCreateWithoutUserInput, Prisma.ProponentUncheckedCreateWithoutUserInput>
}

export type ProponentUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.ProponentUpdateWithoutUserInput, Prisma.ProponentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ProponentCreateWithoutUserInput, Prisma.ProponentUncheckedCreateWithoutUserInput>
  where?: Prisma.ProponentWhereInput
}

export type ProponentUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.ProponentWhereInput
  data: Prisma.XOR<Prisma.ProponentUpdateWithoutUserInput, Prisma.ProponentUncheckedUpdateWithoutUserInput>
}

export type ProponentUpdateWithoutUserInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  institution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projects?: Prisma.ProjectUpdateManyWithoutProponentNestedInput
}

export type ProponentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  institution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutProponentNestedInput
}


/**
 * Count Type ProponentCountOutputType
 */

export type ProponentCountOutputType = {
  projects: number
}

export type ProponentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projects?: boolean | ProponentCountOutputTypeCountProjectsArgs
}

/**
 * ProponentCountOutputType without action
 */
export type ProponentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProponentCountOutputType
   */
  select?: Prisma.ProponentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProponentCountOutputType without action
 */
export type ProponentCountOutputTypeCountProjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
}


export type ProponentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  institution?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projects?: boolean | Prisma.Proponent$projectsArgs<ExtArgs>
  user?: boolean | Prisma.Proponent$userArgs<ExtArgs>
  _count?: boolean | Prisma.ProponentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proponent"]>

export type ProponentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  institution?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.Proponent$userArgs<ExtArgs>
}, ExtArgs["result"]["proponent"]>

export type ProponentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  institution?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.Proponent$userArgs<ExtArgs>
}, ExtArgs["result"]["proponent"]>

export type ProponentSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  institution?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProponentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "institution" | "userId" | "createdAt" | "updatedAt", ExtArgs["result"]["proponent"]>
export type ProponentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projects?: boolean | Prisma.Proponent$projectsArgs<ExtArgs>
  user?: boolean | Prisma.Proponent$userArgs<ExtArgs>
  _count?: boolean | Prisma.ProponentCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProponentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Proponent$userArgs<ExtArgs>
}
export type ProponentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Proponent$userArgs<ExtArgs>
}

export type $ProponentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Proponent"
  objects: {
    projects: Prisma.$ProjectPayload<ExtArgs>[]
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    email: string
    institution: string | null
    userId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["proponent"]>
  composites: {}
}

export type ProponentGetPayload<S extends boolean | null | undefined | ProponentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProponentPayload, S>

export type ProponentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProponentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProponentCountAggregateInputType | true
  }

export interface ProponentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Proponent'], meta: { name: 'Proponent' } }
  /**
   * Find zero or one Proponent that matches the filter.
   * @param {ProponentFindUniqueArgs} args - Arguments to find a Proponent
   * @example
   * // Get one Proponent
   * const proponent = await prisma.proponent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProponentFindUniqueArgs>(args: Prisma.SelectSubset<T, ProponentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProponentClient<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Proponent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProponentFindUniqueOrThrowArgs} args - Arguments to find a Proponent
   * @example
   * // Get one Proponent
   * const proponent = await prisma.proponent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProponentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProponentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProponentClient<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proponent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponentFindFirstArgs} args - Arguments to find a Proponent
   * @example
   * // Get one Proponent
   * const proponent = await prisma.proponent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProponentFindFirstArgs>(args?: Prisma.SelectSubset<T, ProponentFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProponentClient<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proponent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponentFindFirstOrThrowArgs} args - Arguments to find a Proponent
   * @example
   * // Get one Proponent
   * const proponent = await prisma.proponent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProponentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProponentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProponentClient<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Proponents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Proponents
   * const proponents = await prisma.proponent.findMany()
   * 
   * // Get first 10 Proponents
   * const proponents = await prisma.proponent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const proponentWithIdOnly = await prisma.proponent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProponentFindManyArgs>(args?: Prisma.SelectSubset<T, ProponentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Proponent.
   * @param {ProponentCreateArgs} args - Arguments to create a Proponent.
   * @example
   * // Create one Proponent
   * const Proponent = await prisma.proponent.create({
   *   data: {
   *     // ... data to create a Proponent
   *   }
   * })
   * 
   */
  create<T extends ProponentCreateArgs>(args: Prisma.SelectSubset<T, ProponentCreateArgs<ExtArgs>>): Prisma.Prisma__ProponentClient<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Proponents.
   * @param {ProponentCreateManyArgs} args - Arguments to create many Proponents.
   * @example
   * // Create many Proponents
   * const proponent = await prisma.proponent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProponentCreateManyArgs>(args?: Prisma.SelectSubset<T, ProponentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Proponents and returns the data saved in the database.
   * @param {ProponentCreateManyAndReturnArgs} args - Arguments to create many Proponents.
   * @example
   * // Create many Proponents
   * const proponent = await prisma.proponent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Proponents and only return the `id`
   * const proponentWithIdOnly = await prisma.proponent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProponentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProponentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Proponent.
   * @param {ProponentDeleteArgs} args - Arguments to delete one Proponent.
   * @example
   * // Delete one Proponent
   * const Proponent = await prisma.proponent.delete({
   *   where: {
   *     // ... filter to delete one Proponent
   *   }
   * })
   * 
   */
  delete<T extends ProponentDeleteArgs>(args: Prisma.SelectSubset<T, ProponentDeleteArgs<ExtArgs>>): Prisma.Prisma__ProponentClient<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Proponent.
   * @param {ProponentUpdateArgs} args - Arguments to update one Proponent.
   * @example
   * // Update one Proponent
   * const proponent = await prisma.proponent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProponentUpdateArgs>(args: Prisma.SelectSubset<T, ProponentUpdateArgs<ExtArgs>>): Prisma.Prisma__ProponentClient<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Proponents.
   * @param {ProponentDeleteManyArgs} args - Arguments to filter Proponents to delete.
   * @example
   * // Delete a few Proponents
   * const { count } = await prisma.proponent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProponentDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProponentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proponents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Proponents
   * const proponent = await prisma.proponent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProponentUpdateManyArgs>(args: Prisma.SelectSubset<T, ProponentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proponents and returns the data updated in the database.
   * @param {ProponentUpdateManyAndReturnArgs} args - Arguments to update many Proponents.
   * @example
   * // Update many Proponents
   * const proponent = await prisma.proponent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Proponents and only return the `id`
   * const proponentWithIdOnly = await prisma.proponent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProponentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProponentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Proponent.
   * @param {ProponentUpsertArgs} args - Arguments to update or create a Proponent.
   * @example
   * // Update or create a Proponent
   * const proponent = await prisma.proponent.upsert({
   *   create: {
   *     // ... data to create a Proponent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Proponent we want to update
   *   }
   * })
   */
  upsert<T extends ProponentUpsertArgs>(args: Prisma.SelectSubset<T, ProponentUpsertArgs<ExtArgs>>): Prisma.Prisma__ProponentClient<runtime.Types.Result.GetResult<Prisma.$ProponentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Proponents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponentCountArgs} args - Arguments to filter Proponents to count.
   * @example
   * // Count the number of Proponents
   * const count = await prisma.proponent.count({
   *   where: {
   *     // ... the filter for the Proponents we want to count
   *   }
   * })
  **/
  count<T extends ProponentCountArgs>(
    args?: Prisma.Subset<T, ProponentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProponentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Proponent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProponentAggregateArgs>(args: Prisma.Subset<T, ProponentAggregateArgs>): Prisma.PrismaPromise<GetProponentAggregateType<T>>

  /**
   * Group by Proponent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProponentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProponentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProponentGroupByArgs['orderBy'] }
      : { orderBy?: ProponentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProponentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProponentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Proponent model
 */
readonly fields: ProponentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Proponent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProponentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  projects<T extends Prisma.Proponent$projectsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proponent$projectsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user<T extends Prisma.Proponent$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proponent$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Proponent model
 */
export interface ProponentFieldRefs {
  readonly id: Prisma.FieldRef<"Proponent", 'Int'>
  readonly name: Prisma.FieldRef<"Proponent", 'String'>
  readonly email: Prisma.FieldRef<"Proponent", 'String'>
  readonly institution: Prisma.FieldRef<"Proponent", 'String'>
  readonly userId: Prisma.FieldRef<"Proponent", 'String'>
  readonly createdAt: Prisma.FieldRef<"Proponent", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Proponent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Proponent findUnique
 */
export type ProponentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * Filter, which Proponent to fetch.
   */
  where: Prisma.ProponentWhereUniqueInput
}

/**
 * Proponent findUniqueOrThrow
 */
export type ProponentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * Filter, which Proponent to fetch.
   */
  where: Prisma.ProponentWhereUniqueInput
}

/**
 * Proponent findFirst
 */
export type ProponentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * Filter, which Proponent to fetch.
   */
  where?: Prisma.ProponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proponents to fetch.
   */
  orderBy?: Prisma.ProponentOrderByWithRelationInput | Prisma.ProponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proponents.
   */
  cursor?: Prisma.ProponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proponents.
   */
  distinct?: Prisma.ProponentScalarFieldEnum | Prisma.ProponentScalarFieldEnum[]
}

/**
 * Proponent findFirstOrThrow
 */
export type ProponentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * Filter, which Proponent to fetch.
   */
  where?: Prisma.ProponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proponents to fetch.
   */
  orderBy?: Prisma.ProponentOrderByWithRelationInput | Prisma.ProponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proponents.
   */
  cursor?: Prisma.ProponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proponents.
   */
  distinct?: Prisma.ProponentScalarFieldEnum | Prisma.ProponentScalarFieldEnum[]
}

/**
 * Proponent findMany
 */
export type ProponentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * Filter, which Proponents to fetch.
   */
  where?: Prisma.ProponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proponents to fetch.
   */
  orderBy?: Prisma.ProponentOrderByWithRelationInput | Prisma.ProponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Proponents.
   */
  cursor?: Prisma.ProponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proponents.
   */
  skip?: number
  distinct?: Prisma.ProponentScalarFieldEnum | Prisma.ProponentScalarFieldEnum[]
}

/**
 * Proponent create
 */
export type ProponentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * The data needed to create a Proponent.
   */
  data: Prisma.XOR<Prisma.ProponentCreateInput, Prisma.ProponentUncheckedCreateInput>
}

/**
 * Proponent createMany
 */
export type ProponentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Proponents.
   */
  data: Prisma.ProponentCreateManyInput | Prisma.ProponentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Proponent createManyAndReturn
 */
export type ProponentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * The data used to create many Proponents.
   */
  data: Prisma.ProponentCreateManyInput | Prisma.ProponentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Proponent update
 */
export type ProponentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * The data needed to update a Proponent.
   */
  data: Prisma.XOR<Prisma.ProponentUpdateInput, Prisma.ProponentUncheckedUpdateInput>
  /**
   * Choose, which Proponent to update.
   */
  where: Prisma.ProponentWhereUniqueInput
}

/**
 * Proponent updateMany
 */
export type ProponentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Proponents.
   */
  data: Prisma.XOR<Prisma.ProponentUpdateManyMutationInput, Prisma.ProponentUncheckedUpdateManyInput>
  /**
   * Filter which Proponents to update
   */
  where?: Prisma.ProponentWhereInput
  /**
   * Limit how many Proponents to update.
   */
  limit?: number
}

/**
 * Proponent updateManyAndReturn
 */
export type ProponentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * The data used to update Proponents.
   */
  data: Prisma.XOR<Prisma.ProponentUpdateManyMutationInput, Prisma.ProponentUncheckedUpdateManyInput>
  /**
   * Filter which Proponents to update
   */
  where?: Prisma.ProponentWhereInput
  /**
   * Limit how many Proponents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Proponent upsert
 */
export type ProponentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * The filter to search for the Proponent to update in case it exists.
   */
  where: Prisma.ProponentWhereUniqueInput
  /**
   * In case the Proponent found by the `where` argument doesn't exist, create a new Proponent with this data.
   */
  create: Prisma.XOR<Prisma.ProponentCreateInput, Prisma.ProponentUncheckedCreateInput>
  /**
   * In case the Proponent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProponentUpdateInput, Prisma.ProponentUncheckedUpdateInput>
}

/**
 * Proponent delete
 */
export type ProponentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
  /**
   * Filter which Proponent to delete.
   */
  where: Prisma.ProponentWhereUniqueInput
}

/**
 * Proponent deleteMany
 */
export type ProponentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proponents to delete
   */
  where?: Prisma.ProponentWhereInput
  /**
   * Limit how many Proponents to delete.
   */
  limit?: number
}

/**
 * Proponent.projects
 */
export type Proponent$projectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  cursor?: Prisma.ProjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Proponent.user
 */
export type Proponent$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Proponent without action
 */
export type ProponentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proponent
   */
  select?: Prisma.ProponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proponent
   */
  omit?: Prisma.ProponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProponentInclude<ExtArgs> | null
}
