
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Responsibility` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Responsibility
 * 
 */
export type ResponsibilityModel = runtime.Types.Result.DefaultSelection<Prisma.$ResponsibilityPayload>

export type AggregateResponsibility = {
  _count: ResponsibilityCountAggregateOutputType | null
  _avg: ResponsibilityAvgAggregateOutputType | null
  _sum: ResponsibilitySumAggregateOutputType | null
  _min: ResponsibilityMinAggregateOutputType | null
  _max: ResponsibilityMaxAggregateOutputType | null
}

export type ResponsibilityAvgAggregateOutputType = {
  id: number | null
  workPlanId: number | null
  participantId: number | null
}

export type ResponsibilitySumAggregateOutputType = {
  id: number | null
  workPlanId: number | null
  participantId: number | null
}

export type ResponsibilityMinAggregateOutputType = {
  id: number | null
  workPlanId: number | null
  participantId: number | null
  description: string | null
}

export type ResponsibilityMaxAggregateOutputType = {
  id: number | null
  workPlanId: number | null
  participantId: number | null
  description: string | null
}

export type ResponsibilityCountAggregateOutputType = {
  id: number
  workPlanId: number
  participantId: number
  description: number
  _all: number
}


export type ResponsibilityAvgAggregateInputType = {
  id?: true
  workPlanId?: true
  participantId?: true
}

export type ResponsibilitySumAggregateInputType = {
  id?: true
  workPlanId?: true
  participantId?: true
}

export type ResponsibilityMinAggregateInputType = {
  id?: true
  workPlanId?: true
  participantId?: true
  description?: true
}

export type ResponsibilityMaxAggregateInputType = {
  id?: true
  workPlanId?: true
  participantId?: true
  description?: true
}

export type ResponsibilityCountAggregateInputType = {
  id?: true
  workPlanId?: true
  participantId?: true
  description?: true
  _all?: true
}

export type ResponsibilityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Responsibility to aggregate.
   */
  where?: Prisma.ResponsibilityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Responsibilities to fetch.
   */
  orderBy?: Prisma.ResponsibilityOrderByWithRelationInput | Prisma.ResponsibilityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ResponsibilityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Responsibilities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Responsibilities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Responsibilities
  **/
  _count?: true | ResponsibilityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ResponsibilityAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ResponsibilitySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ResponsibilityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ResponsibilityMaxAggregateInputType
}

export type GetResponsibilityAggregateType<T extends ResponsibilityAggregateArgs> = {
      [P in keyof T & keyof AggregateResponsibility]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateResponsibility[P]>
    : Prisma.GetScalarType<T[P], AggregateResponsibility[P]>
}




export type ResponsibilityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ResponsibilityWhereInput
  orderBy?: Prisma.ResponsibilityOrderByWithAggregationInput | Prisma.ResponsibilityOrderByWithAggregationInput[]
  by: Prisma.ResponsibilityScalarFieldEnum[] | Prisma.ResponsibilityScalarFieldEnum
  having?: Prisma.ResponsibilityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ResponsibilityCountAggregateInputType | true
  _avg?: ResponsibilityAvgAggregateInputType
  _sum?: ResponsibilitySumAggregateInputType
  _min?: ResponsibilityMinAggregateInputType
  _max?: ResponsibilityMaxAggregateInputType
}

export type ResponsibilityGroupByOutputType = {
  id: number
  workPlanId: number
  participantId: number | null
  description: string
  _count: ResponsibilityCountAggregateOutputType | null
  _avg: ResponsibilityAvgAggregateOutputType | null
  _sum: ResponsibilitySumAggregateOutputType | null
  _min: ResponsibilityMinAggregateOutputType | null
  _max: ResponsibilityMaxAggregateOutputType | null
}

type GetResponsibilityGroupByPayload<T extends ResponsibilityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ResponsibilityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ResponsibilityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ResponsibilityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ResponsibilityGroupByOutputType[P]>
      }
    >
  >



export type ResponsibilityWhereInput = {
  AND?: Prisma.ResponsibilityWhereInput | Prisma.ResponsibilityWhereInput[]
  OR?: Prisma.ResponsibilityWhereInput[]
  NOT?: Prisma.ResponsibilityWhereInput | Prisma.ResponsibilityWhereInput[]
  id?: Prisma.IntFilter<"Responsibility"> | number
  workPlanId?: Prisma.IntFilter<"Responsibility"> | number
  participantId?: Prisma.IntNullableFilter<"Responsibility"> | number | null
  description?: Prisma.StringFilter<"Responsibility"> | string
  workPlan?: Prisma.XOR<Prisma.WorkPlanScalarRelationFilter, Prisma.WorkPlanWhereInput>
  participant?: Prisma.XOR<Prisma.ParticipantNullableScalarRelationFilter, Prisma.ParticipantWhereInput> | null
}

export type ResponsibilityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  participantId?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  workPlan?: Prisma.WorkPlanOrderByWithRelationInput
  participant?: Prisma.ParticipantOrderByWithRelationInput
}

export type ResponsibilityWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ResponsibilityWhereInput | Prisma.ResponsibilityWhereInput[]
  OR?: Prisma.ResponsibilityWhereInput[]
  NOT?: Prisma.ResponsibilityWhereInput | Prisma.ResponsibilityWhereInput[]
  workPlanId?: Prisma.IntFilter<"Responsibility"> | number
  participantId?: Prisma.IntNullableFilter<"Responsibility"> | number | null
  description?: Prisma.StringFilter<"Responsibility"> | string
  workPlan?: Prisma.XOR<Prisma.WorkPlanScalarRelationFilter, Prisma.WorkPlanWhereInput>
  participant?: Prisma.XOR<Prisma.ParticipantNullableScalarRelationFilter, Prisma.ParticipantWhereInput> | null
}, "id">

export type ResponsibilityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  participantId?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  _count?: Prisma.ResponsibilityCountOrderByAggregateInput
  _avg?: Prisma.ResponsibilityAvgOrderByAggregateInput
  _max?: Prisma.ResponsibilityMaxOrderByAggregateInput
  _min?: Prisma.ResponsibilityMinOrderByAggregateInput
  _sum?: Prisma.ResponsibilitySumOrderByAggregateInput
}

export type ResponsibilityScalarWhereWithAggregatesInput = {
  AND?: Prisma.ResponsibilityScalarWhereWithAggregatesInput | Prisma.ResponsibilityScalarWhereWithAggregatesInput[]
  OR?: Prisma.ResponsibilityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ResponsibilityScalarWhereWithAggregatesInput | Prisma.ResponsibilityScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Responsibility"> | number
  workPlanId?: Prisma.IntWithAggregatesFilter<"Responsibility"> | number
  participantId?: Prisma.IntNullableWithAggregatesFilter<"Responsibility"> | number | null
  description?: Prisma.StringWithAggregatesFilter<"Responsibility"> | string
}

export type ResponsibilityCreateInput = {
  description: string
  workPlan: Prisma.WorkPlanCreateNestedOneWithoutResponsibilitiesInput
  participant?: Prisma.ParticipantCreateNestedOneWithoutResponsibilitiesInput
}

export type ResponsibilityUncheckedCreateInput = {
  id?: number
  workPlanId: number
  participantId?: number | null
  description: string
}

export type ResponsibilityUpdateInput = {
  description?: Prisma.StringFieldUpdateOperationsInput | string
  workPlan?: Prisma.WorkPlanUpdateOneRequiredWithoutResponsibilitiesNestedInput
  participant?: Prisma.ParticipantUpdateOneWithoutResponsibilitiesNestedInput
}

export type ResponsibilityUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  workPlanId?: Prisma.IntFieldUpdateOperationsInput | number
  participantId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ResponsibilityCreateManyInput = {
  id?: number
  workPlanId: number
  participantId?: number | null
  description: string
}

export type ResponsibilityUpdateManyMutationInput = {
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ResponsibilityUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  workPlanId?: Prisma.IntFieldUpdateOperationsInput | number
  participantId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ResponsibilityListRelationFilter = {
  every?: Prisma.ResponsibilityWhereInput
  some?: Prisma.ResponsibilityWhereInput
  none?: Prisma.ResponsibilityWhereInput
}

export type ResponsibilityOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ResponsibilityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ResponsibilityAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
}

export type ResponsibilityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ResponsibilityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ResponsibilitySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
}

export type ResponsibilityCreateNestedManyWithoutWorkPlanInput = {
  create?: Prisma.XOR<Prisma.ResponsibilityCreateWithoutWorkPlanInput, Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput> | Prisma.ResponsibilityCreateWithoutWorkPlanInput[] | Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput[]
  connectOrCreate?: Prisma.ResponsibilityCreateOrConnectWithoutWorkPlanInput | Prisma.ResponsibilityCreateOrConnectWithoutWorkPlanInput[]
  createMany?: Prisma.ResponsibilityCreateManyWorkPlanInputEnvelope
  connect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
}

export type ResponsibilityUncheckedCreateNestedManyWithoutWorkPlanInput = {
  create?: Prisma.XOR<Prisma.ResponsibilityCreateWithoutWorkPlanInput, Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput> | Prisma.ResponsibilityCreateWithoutWorkPlanInput[] | Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput[]
  connectOrCreate?: Prisma.ResponsibilityCreateOrConnectWithoutWorkPlanInput | Prisma.ResponsibilityCreateOrConnectWithoutWorkPlanInput[]
  createMany?: Prisma.ResponsibilityCreateManyWorkPlanInputEnvelope
  connect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
}

export type ResponsibilityUpdateManyWithoutWorkPlanNestedInput = {
  create?: Prisma.XOR<Prisma.ResponsibilityCreateWithoutWorkPlanInput, Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput> | Prisma.ResponsibilityCreateWithoutWorkPlanInput[] | Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput[]
  connectOrCreate?: Prisma.ResponsibilityCreateOrConnectWithoutWorkPlanInput | Prisma.ResponsibilityCreateOrConnectWithoutWorkPlanInput[]
  upsert?: Prisma.ResponsibilityUpsertWithWhereUniqueWithoutWorkPlanInput | Prisma.ResponsibilityUpsertWithWhereUniqueWithoutWorkPlanInput[]
  createMany?: Prisma.ResponsibilityCreateManyWorkPlanInputEnvelope
  set?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  disconnect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  delete?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  connect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  update?: Prisma.ResponsibilityUpdateWithWhereUniqueWithoutWorkPlanInput | Prisma.ResponsibilityUpdateWithWhereUniqueWithoutWorkPlanInput[]
  updateMany?: Prisma.ResponsibilityUpdateManyWithWhereWithoutWorkPlanInput | Prisma.ResponsibilityUpdateManyWithWhereWithoutWorkPlanInput[]
  deleteMany?: Prisma.ResponsibilityScalarWhereInput | Prisma.ResponsibilityScalarWhereInput[]
}

export type ResponsibilityUncheckedUpdateManyWithoutWorkPlanNestedInput = {
  create?: Prisma.XOR<Prisma.ResponsibilityCreateWithoutWorkPlanInput, Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput> | Prisma.ResponsibilityCreateWithoutWorkPlanInput[] | Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput[]
  connectOrCreate?: Prisma.ResponsibilityCreateOrConnectWithoutWorkPlanInput | Prisma.ResponsibilityCreateOrConnectWithoutWorkPlanInput[]
  upsert?: Prisma.ResponsibilityUpsertWithWhereUniqueWithoutWorkPlanInput | Prisma.ResponsibilityUpsertWithWhereUniqueWithoutWorkPlanInput[]
  createMany?: Prisma.ResponsibilityCreateManyWorkPlanInputEnvelope
  set?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  disconnect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  delete?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  connect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  update?: Prisma.ResponsibilityUpdateWithWhereUniqueWithoutWorkPlanInput | Prisma.ResponsibilityUpdateWithWhereUniqueWithoutWorkPlanInput[]
  updateMany?: Prisma.ResponsibilityUpdateManyWithWhereWithoutWorkPlanInput | Prisma.ResponsibilityUpdateManyWithWhereWithoutWorkPlanInput[]
  deleteMany?: Prisma.ResponsibilityScalarWhereInput | Prisma.ResponsibilityScalarWhereInput[]
}

export type ResponsibilityCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.ResponsibilityCreateWithoutParticipantInput, Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput> | Prisma.ResponsibilityCreateWithoutParticipantInput[] | Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ResponsibilityCreateOrConnectWithoutParticipantInput | Prisma.ResponsibilityCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.ResponsibilityCreateManyParticipantInputEnvelope
  connect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
}

export type ResponsibilityUncheckedCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.ResponsibilityCreateWithoutParticipantInput, Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput> | Prisma.ResponsibilityCreateWithoutParticipantInput[] | Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ResponsibilityCreateOrConnectWithoutParticipantInput | Prisma.ResponsibilityCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.ResponsibilityCreateManyParticipantInputEnvelope
  connect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
}

export type ResponsibilityUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.ResponsibilityCreateWithoutParticipantInput, Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput> | Prisma.ResponsibilityCreateWithoutParticipantInput[] | Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ResponsibilityCreateOrConnectWithoutParticipantInput | Prisma.ResponsibilityCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.ResponsibilityUpsertWithWhereUniqueWithoutParticipantInput | Prisma.ResponsibilityUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.ResponsibilityCreateManyParticipantInputEnvelope
  set?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  disconnect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  delete?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  connect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  update?: Prisma.ResponsibilityUpdateWithWhereUniqueWithoutParticipantInput | Prisma.ResponsibilityUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.ResponsibilityUpdateManyWithWhereWithoutParticipantInput | Prisma.ResponsibilityUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.ResponsibilityScalarWhereInput | Prisma.ResponsibilityScalarWhereInput[]
}

export type ResponsibilityUncheckedUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.ResponsibilityCreateWithoutParticipantInput, Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput> | Prisma.ResponsibilityCreateWithoutParticipantInput[] | Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ResponsibilityCreateOrConnectWithoutParticipantInput | Prisma.ResponsibilityCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.ResponsibilityUpsertWithWhereUniqueWithoutParticipantInput | Prisma.ResponsibilityUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.ResponsibilityCreateManyParticipantInputEnvelope
  set?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  disconnect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  delete?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  connect?: Prisma.ResponsibilityWhereUniqueInput | Prisma.ResponsibilityWhereUniqueInput[]
  update?: Prisma.ResponsibilityUpdateWithWhereUniqueWithoutParticipantInput | Prisma.ResponsibilityUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.ResponsibilityUpdateManyWithWhereWithoutParticipantInput | Prisma.ResponsibilityUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.ResponsibilityScalarWhereInput | Prisma.ResponsibilityScalarWhereInput[]
}

export type ResponsibilityCreateWithoutWorkPlanInput = {
  description: string
  participant?: Prisma.ParticipantCreateNestedOneWithoutResponsibilitiesInput
}

export type ResponsibilityUncheckedCreateWithoutWorkPlanInput = {
  id?: number
  participantId?: number | null
  description: string
}

export type ResponsibilityCreateOrConnectWithoutWorkPlanInput = {
  where: Prisma.ResponsibilityWhereUniqueInput
  create: Prisma.XOR<Prisma.ResponsibilityCreateWithoutWorkPlanInput, Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput>
}

export type ResponsibilityCreateManyWorkPlanInputEnvelope = {
  data: Prisma.ResponsibilityCreateManyWorkPlanInput | Prisma.ResponsibilityCreateManyWorkPlanInput[]
  skipDuplicates?: boolean
}

export type ResponsibilityUpsertWithWhereUniqueWithoutWorkPlanInput = {
  where: Prisma.ResponsibilityWhereUniqueInput
  update: Prisma.XOR<Prisma.ResponsibilityUpdateWithoutWorkPlanInput, Prisma.ResponsibilityUncheckedUpdateWithoutWorkPlanInput>
  create: Prisma.XOR<Prisma.ResponsibilityCreateWithoutWorkPlanInput, Prisma.ResponsibilityUncheckedCreateWithoutWorkPlanInput>
}

export type ResponsibilityUpdateWithWhereUniqueWithoutWorkPlanInput = {
  where: Prisma.ResponsibilityWhereUniqueInput
  data: Prisma.XOR<Prisma.ResponsibilityUpdateWithoutWorkPlanInput, Prisma.ResponsibilityUncheckedUpdateWithoutWorkPlanInput>
}

export type ResponsibilityUpdateManyWithWhereWithoutWorkPlanInput = {
  where: Prisma.ResponsibilityScalarWhereInput
  data: Prisma.XOR<Prisma.ResponsibilityUpdateManyMutationInput, Prisma.ResponsibilityUncheckedUpdateManyWithoutWorkPlanInput>
}

export type ResponsibilityScalarWhereInput = {
  AND?: Prisma.ResponsibilityScalarWhereInput | Prisma.ResponsibilityScalarWhereInput[]
  OR?: Prisma.ResponsibilityScalarWhereInput[]
  NOT?: Prisma.ResponsibilityScalarWhereInput | Prisma.ResponsibilityScalarWhereInput[]
  id?: Prisma.IntFilter<"Responsibility"> | number
  workPlanId?: Prisma.IntFilter<"Responsibility"> | number
  participantId?: Prisma.IntNullableFilter<"Responsibility"> | number | null
  description?: Prisma.StringFilter<"Responsibility"> | string
}

export type ResponsibilityCreateWithoutParticipantInput = {
  description: string
  workPlan: Prisma.WorkPlanCreateNestedOneWithoutResponsibilitiesInput
}

export type ResponsibilityUncheckedCreateWithoutParticipantInput = {
  id?: number
  workPlanId: number
  description: string
}

export type ResponsibilityCreateOrConnectWithoutParticipantInput = {
  where: Prisma.ResponsibilityWhereUniqueInput
  create: Prisma.XOR<Prisma.ResponsibilityCreateWithoutParticipantInput, Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput>
}

export type ResponsibilityCreateManyParticipantInputEnvelope = {
  data: Prisma.ResponsibilityCreateManyParticipantInput | Prisma.ResponsibilityCreateManyParticipantInput[]
  skipDuplicates?: boolean
}

export type ResponsibilityUpsertWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.ResponsibilityWhereUniqueInput
  update: Prisma.XOR<Prisma.ResponsibilityUpdateWithoutParticipantInput, Prisma.ResponsibilityUncheckedUpdateWithoutParticipantInput>
  create: Prisma.XOR<Prisma.ResponsibilityCreateWithoutParticipantInput, Prisma.ResponsibilityUncheckedCreateWithoutParticipantInput>
}

export type ResponsibilityUpdateWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.ResponsibilityWhereUniqueInput
  data: Prisma.XOR<Prisma.ResponsibilityUpdateWithoutParticipantInput, Prisma.ResponsibilityUncheckedUpdateWithoutParticipantInput>
}

export type ResponsibilityUpdateManyWithWhereWithoutParticipantInput = {
  where: Prisma.ResponsibilityScalarWhereInput
  data: Prisma.XOR<Prisma.ResponsibilityUpdateManyMutationInput, Prisma.ResponsibilityUncheckedUpdateManyWithoutParticipantInput>
}

export type ResponsibilityCreateManyWorkPlanInput = {
  id?: number
  participantId?: number | null
  description: string
}

export type ResponsibilityUpdateWithoutWorkPlanInput = {
  description?: Prisma.StringFieldUpdateOperationsInput | string
  participant?: Prisma.ParticipantUpdateOneWithoutResponsibilitiesNestedInput
}

export type ResponsibilityUncheckedUpdateWithoutWorkPlanInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  participantId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ResponsibilityUncheckedUpdateManyWithoutWorkPlanInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  participantId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ResponsibilityCreateManyParticipantInput = {
  id?: number
  workPlanId: number
  description: string
}

export type ResponsibilityUpdateWithoutParticipantInput = {
  description?: Prisma.StringFieldUpdateOperationsInput | string
  workPlan?: Prisma.WorkPlanUpdateOneRequiredWithoutResponsibilitiesNestedInput
}

export type ResponsibilityUncheckedUpdateWithoutParticipantInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  workPlanId?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ResponsibilityUncheckedUpdateManyWithoutParticipantInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  workPlanId?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ResponsibilitySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workPlanId?: boolean
  participantId?: boolean
  description?: boolean
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.Responsibility$participantArgs<ExtArgs>
}, ExtArgs["result"]["responsibility"]>

export type ResponsibilitySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workPlanId?: boolean
  participantId?: boolean
  description?: boolean
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.Responsibility$participantArgs<ExtArgs>
}, ExtArgs["result"]["responsibility"]>

export type ResponsibilitySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workPlanId?: boolean
  participantId?: boolean
  description?: boolean
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.Responsibility$participantArgs<ExtArgs>
}, ExtArgs["result"]["responsibility"]>

export type ResponsibilitySelectScalar = {
  id?: boolean
  workPlanId?: boolean
  participantId?: boolean
  description?: boolean
}

export type ResponsibilityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workPlanId" | "participantId" | "description", ExtArgs["result"]["responsibility"]>
export type ResponsibilityInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.Responsibility$participantArgs<ExtArgs>
}
export type ResponsibilityIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.Responsibility$participantArgs<ExtArgs>
}
export type ResponsibilityIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.Responsibility$participantArgs<ExtArgs>
}

export type $ResponsibilityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Responsibility"
  objects: {
    workPlan: Prisma.$WorkPlanPayload<ExtArgs>
    participant: Prisma.$ParticipantPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    workPlanId: number
    participantId: number | null
    description: string
  }, ExtArgs["result"]["responsibility"]>
  composites: {}
}

export type ResponsibilityGetPayload<S extends boolean | null | undefined | ResponsibilityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload, S>

export type ResponsibilityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ResponsibilityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ResponsibilityCountAggregateInputType | true
  }

export interface ResponsibilityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Responsibility'], meta: { name: 'Responsibility' } }
  /**
   * Find zero or one Responsibility that matches the filter.
   * @param {ResponsibilityFindUniqueArgs} args - Arguments to find a Responsibility
   * @example
   * // Get one Responsibility
   * const responsibility = await prisma.responsibility.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ResponsibilityFindUniqueArgs>(args: Prisma.SelectSubset<T, ResponsibilityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ResponsibilityClient<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Responsibility that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ResponsibilityFindUniqueOrThrowArgs} args - Arguments to find a Responsibility
   * @example
   * // Get one Responsibility
   * const responsibility = await prisma.responsibility.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ResponsibilityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ResponsibilityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ResponsibilityClient<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Responsibility that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResponsibilityFindFirstArgs} args - Arguments to find a Responsibility
   * @example
   * // Get one Responsibility
   * const responsibility = await prisma.responsibility.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ResponsibilityFindFirstArgs>(args?: Prisma.SelectSubset<T, ResponsibilityFindFirstArgs<ExtArgs>>): Prisma.Prisma__ResponsibilityClient<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Responsibility that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResponsibilityFindFirstOrThrowArgs} args - Arguments to find a Responsibility
   * @example
   * // Get one Responsibility
   * const responsibility = await prisma.responsibility.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ResponsibilityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ResponsibilityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ResponsibilityClient<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Responsibilities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResponsibilityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Responsibilities
   * const responsibilities = await prisma.responsibility.findMany()
   * 
   * // Get first 10 Responsibilities
   * const responsibilities = await prisma.responsibility.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const responsibilityWithIdOnly = await prisma.responsibility.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ResponsibilityFindManyArgs>(args?: Prisma.SelectSubset<T, ResponsibilityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Responsibility.
   * @param {ResponsibilityCreateArgs} args - Arguments to create a Responsibility.
   * @example
   * // Create one Responsibility
   * const Responsibility = await prisma.responsibility.create({
   *   data: {
   *     // ... data to create a Responsibility
   *   }
   * })
   * 
   */
  create<T extends ResponsibilityCreateArgs>(args: Prisma.SelectSubset<T, ResponsibilityCreateArgs<ExtArgs>>): Prisma.Prisma__ResponsibilityClient<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Responsibilities.
   * @param {ResponsibilityCreateManyArgs} args - Arguments to create many Responsibilities.
   * @example
   * // Create many Responsibilities
   * const responsibility = await prisma.responsibility.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ResponsibilityCreateManyArgs>(args?: Prisma.SelectSubset<T, ResponsibilityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Responsibilities and returns the data saved in the database.
   * @param {ResponsibilityCreateManyAndReturnArgs} args - Arguments to create many Responsibilities.
   * @example
   * // Create many Responsibilities
   * const responsibility = await prisma.responsibility.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Responsibilities and only return the `id`
   * const responsibilityWithIdOnly = await prisma.responsibility.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ResponsibilityCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ResponsibilityCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Responsibility.
   * @param {ResponsibilityDeleteArgs} args - Arguments to delete one Responsibility.
   * @example
   * // Delete one Responsibility
   * const Responsibility = await prisma.responsibility.delete({
   *   where: {
   *     // ... filter to delete one Responsibility
   *   }
   * })
   * 
   */
  delete<T extends ResponsibilityDeleteArgs>(args: Prisma.SelectSubset<T, ResponsibilityDeleteArgs<ExtArgs>>): Prisma.Prisma__ResponsibilityClient<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Responsibility.
   * @param {ResponsibilityUpdateArgs} args - Arguments to update one Responsibility.
   * @example
   * // Update one Responsibility
   * const responsibility = await prisma.responsibility.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ResponsibilityUpdateArgs>(args: Prisma.SelectSubset<T, ResponsibilityUpdateArgs<ExtArgs>>): Prisma.Prisma__ResponsibilityClient<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Responsibilities.
   * @param {ResponsibilityDeleteManyArgs} args - Arguments to filter Responsibilities to delete.
   * @example
   * // Delete a few Responsibilities
   * const { count } = await prisma.responsibility.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ResponsibilityDeleteManyArgs>(args?: Prisma.SelectSubset<T, ResponsibilityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Responsibilities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResponsibilityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Responsibilities
   * const responsibility = await prisma.responsibility.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ResponsibilityUpdateManyArgs>(args: Prisma.SelectSubset<T, ResponsibilityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Responsibilities and returns the data updated in the database.
   * @param {ResponsibilityUpdateManyAndReturnArgs} args - Arguments to update many Responsibilities.
   * @example
   * // Update many Responsibilities
   * const responsibility = await prisma.responsibility.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Responsibilities and only return the `id`
   * const responsibilityWithIdOnly = await prisma.responsibility.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ResponsibilityUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ResponsibilityUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Responsibility.
   * @param {ResponsibilityUpsertArgs} args - Arguments to update or create a Responsibility.
   * @example
   * // Update or create a Responsibility
   * const responsibility = await prisma.responsibility.upsert({
   *   create: {
   *     // ... data to create a Responsibility
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Responsibility we want to update
   *   }
   * })
   */
  upsert<T extends ResponsibilityUpsertArgs>(args: Prisma.SelectSubset<T, ResponsibilityUpsertArgs<ExtArgs>>): Prisma.Prisma__ResponsibilityClient<runtime.Types.Result.GetResult<Prisma.$ResponsibilityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Responsibilities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResponsibilityCountArgs} args - Arguments to filter Responsibilities to count.
   * @example
   * // Count the number of Responsibilities
   * const count = await prisma.responsibility.count({
   *   where: {
   *     // ... the filter for the Responsibilities we want to count
   *   }
   * })
  **/
  count<T extends ResponsibilityCountArgs>(
    args?: Prisma.Subset<T, ResponsibilityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ResponsibilityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Responsibility.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResponsibilityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ResponsibilityAggregateArgs>(args: Prisma.Subset<T, ResponsibilityAggregateArgs>): Prisma.PrismaPromise<GetResponsibilityAggregateType<T>>

  /**
   * Group by Responsibility.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResponsibilityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ResponsibilityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ResponsibilityGroupByArgs['orderBy'] }
      : { orderBy?: ResponsibilityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ResponsibilityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetResponsibilityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Responsibility model
 */
readonly fields: ResponsibilityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Responsibility.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ResponsibilityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workPlan<T extends Prisma.WorkPlanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkPlanDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkPlanClient<runtime.Types.Result.GetResult<Prisma.$WorkPlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  participant<T extends Prisma.Responsibility$participantArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Responsibility$participantArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Responsibility model
 */
export interface ResponsibilityFieldRefs {
  readonly id: Prisma.FieldRef<"Responsibility", 'Int'>
  readonly workPlanId: Prisma.FieldRef<"Responsibility", 'Int'>
  readonly participantId: Prisma.FieldRef<"Responsibility", 'Int'>
  readonly description: Prisma.FieldRef<"Responsibility", 'String'>
}
    

// Custom InputTypes
/**
 * Responsibility findUnique
 */
export type ResponsibilityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * Filter, which Responsibility to fetch.
   */
  where: Prisma.ResponsibilityWhereUniqueInput
}

/**
 * Responsibility findUniqueOrThrow
 */
export type ResponsibilityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * Filter, which Responsibility to fetch.
   */
  where: Prisma.ResponsibilityWhereUniqueInput
}

/**
 * Responsibility findFirst
 */
export type ResponsibilityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * Filter, which Responsibility to fetch.
   */
  where?: Prisma.ResponsibilityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Responsibilities to fetch.
   */
  orderBy?: Prisma.ResponsibilityOrderByWithRelationInput | Prisma.ResponsibilityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Responsibilities.
   */
  cursor?: Prisma.ResponsibilityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Responsibilities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Responsibilities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Responsibilities.
   */
  distinct?: Prisma.ResponsibilityScalarFieldEnum | Prisma.ResponsibilityScalarFieldEnum[]
}

/**
 * Responsibility findFirstOrThrow
 */
export type ResponsibilityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * Filter, which Responsibility to fetch.
   */
  where?: Prisma.ResponsibilityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Responsibilities to fetch.
   */
  orderBy?: Prisma.ResponsibilityOrderByWithRelationInput | Prisma.ResponsibilityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Responsibilities.
   */
  cursor?: Prisma.ResponsibilityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Responsibilities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Responsibilities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Responsibilities.
   */
  distinct?: Prisma.ResponsibilityScalarFieldEnum | Prisma.ResponsibilityScalarFieldEnum[]
}

/**
 * Responsibility findMany
 */
export type ResponsibilityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * Filter, which Responsibilities to fetch.
   */
  where?: Prisma.ResponsibilityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Responsibilities to fetch.
   */
  orderBy?: Prisma.ResponsibilityOrderByWithRelationInput | Prisma.ResponsibilityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Responsibilities.
   */
  cursor?: Prisma.ResponsibilityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Responsibilities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Responsibilities.
   */
  skip?: number
  distinct?: Prisma.ResponsibilityScalarFieldEnum | Prisma.ResponsibilityScalarFieldEnum[]
}

/**
 * Responsibility create
 */
export type ResponsibilityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * The data needed to create a Responsibility.
   */
  data: Prisma.XOR<Prisma.ResponsibilityCreateInput, Prisma.ResponsibilityUncheckedCreateInput>
}

/**
 * Responsibility createMany
 */
export type ResponsibilityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Responsibilities.
   */
  data: Prisma.ResponsibilityCreateManyInput | Prisma.ResponsibilityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Responsibility createManyAndReturn
 */
export type ResponsibilityCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * The data used to create many Responsibilities.
   */
  data: Prisma.ResponsibilityCreateManyInput | Prisma.ResponsibilityCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Responsibility update
 */
export type ResponsibilityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * The data needed to update a Responsibility.
   */
  data: Prisma.XOR<Prisma.ResponsibilityUpdateInput, Prisma.ResponsibilityUncheckedUpdateInput>
  /**
   * Choose, which Responsibility to update.
   */
  where: Prisma.ResponsibilityWhereUniqueInput
}

/**
 * Responsibility updateMany
 */
export type ResponsibilityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Responsibilities.
   */
  data: Prisma.XOR<Prisma.ResponsibilityUpdateManyMutationInput, Prisma.ResponsibilityUncheckedUpdateManyInput>
  /**
   * Filter which Responsibilities to update
   */
  where?: Prisma.ResponsibilityWhereInput
  /**
   * Limit how many Responsibilities to update.
   */
  limit?: number
}

/**
 * Responsibility updateManyAndReturn
 */
export type ResponsibilityUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * The data used to update Responsibilities.
   */
  data: Prisma.XOR<Prisma.ResponsibilityUpdateManyMutationInput, Prisma.ResponsibilityUncheckedUpdateManyInput>
  /**
   * Filter which Responsibilities to update
   */
  where?: Prisma.ResponsibilityWhereInput
  /**
   * Limit how many Responsibilities to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Responsibility upsert
 */
export type ResponsibilityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * The filter to search for the Responsibility to update in case it exists.
   */
  where: Prisma.ResponsibilityWhereUniqueInput
  /**
   * In case the Responsibility found by the `where` argument doesn't exist, create a new Responsibility with this data.
   */
  create: Prisma.XOR<Prisma.ResponsibilityCreateInput, Prisma.ResponsibilityUncheckedCreateInput>
  /**
   * In case the Responsibility was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ResponsibilityUpdateInput, Prisma.ResponsibilityUncheckedUpdateInput>
}

/**
 * Responsibility delete
 */
export type ResponsibilityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
  /**
   * Filter which Responsibility to delete.
   */
  where: Prisma.ResponsibilityWhereUniqueInput
}

/**
 * Responsibility deleteMany
 */
export type ResponsibilityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Responsibilities to delete
   */
  where?: Prisma.ResponsibilityWhereInput
  /**
   * Limit how many Responsibilities to delete.
   */
  limit?: number
}

/**
 * Responsibility.participant
 */
export type Responsibility$participantArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  where?: Prisma.ParticipantWhereInput
}

/**
 * Responsibility without action
 */
export type ResponsibilityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Responsibility
   */
  select?: Prisma.ResponsibilitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Responsibility
   */
  omit?: Prisma.ResponsibilityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponsibilityInclude<ExtArgs> | null
}
