
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ScheduleItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ScheduleItem
 * 
 */
export type ScheduleItemModel = runtime.Types.Result.DefaultSelection<Prisma.$ScheduleItemPayload>

export type AggregateScheduleItem = {
  _count: ScheduleItemCountAggregateOutputType | null
  _avg: ScheduleItemAvgAggregateOutputType | null
  _sum: ScheduleItemSumAggregateOutputType | null
  _min: ScheduleItemMinAggregateOutputType | null
  _max: ScheduleItemMaxAggregateOutputType | null
}

export type ScheduleItemAvgAggregateOutputType = {
  id: number | null
  workPlanId: number | null
}

export type ScheduleItemSumAggregateOutputType = {
  id: number | null
  workPlanId: number | null
}

export type ScheduleItemMinAggregateOutputType = {
  id: number | null
  workPlanId: number | null
  axisGoal: string | null
  actionStep: string | null
  indicator: string | null
  responsible: string | null
  startDate: Date | null
  endDate: Date | null
  status: $Enums.ScheduleStatus | null
}

export type ScheduleItemMaxAggregateOutputType = {
  id: number | null
  workPlanId: number | null
  axisGoal: string | null
  actionStep: string | null
  indicator: string | null
  responsible: string | null
  startDate: Date | null
  endDate: Date | null
  status: $Enums.ScheduleStatus | null
}

export type ScheduleItemCountAggregateOutputType = {
  id: number
  workPlanId: number
  axisGoal: number
  actionStep: number
  indicator: number
  responsible: number
  startDate: number
  endDate: number
  status: number
  _all: number
}


export type ScheduleItemAvgAggregateInputType = {
  id?: true
  workPlanId?: true
}

export type ScheduleItemSumAggregateInputType = {
  id?: true
  workPlanId?: true
}

export type ScheduleItemMinAggregateInputType = {
  id?: true
  workPlanId?: true
  axisGoal?: true
  actionStep?: true
  indicator?: true
  responsible?: true
  startDate?: true
  endDate?: true
  status?: true
}

export type ScheduleItemMaxAggregateInputType = {
  id?: true
  workPlanId?: true
  axisGoal?: true
  actionStep?: true
  indicator?: true
  responsible?: true
  startDate?: true
  endDate?: true
  status?: true
}

export type ScheduleItemCountAggregateInputType = {
  id?: true
  workPlanId?: true
  axisGoal?: true
  actionStep?: true
  indicator?: true
  responsible?: true
  startDate?: true
  endDate?: true
  status?: true
  _all?: true
}

export type ScheduleItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ScheduleItem to aggregate.
   */
  where?: Prisma.ScheduleItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduleItems to fetch.
   */
  orderBy?: Prisma.ScheduleItemOrderByWithRelationInput | Prisma.ScheduleItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ScheduleItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduleItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduleItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ScheduleItems
  **/
  _count?: true | ScheduleItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ScheduleItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ScheduleItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ScheduleItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ScheduleItemMaxAggregateInputType
}

export type GetScheduleItemAggregateType<T extends ScheduleItemAggregateArgs> = {
      [P in keyof T & keyof AggregateScheduleItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateScheduleItem[P]>
    : Prisma.GetScalarType<T[P], AggregateScheduleItem[P]>
}




export type ScheduleItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ScheduleItemWhereInput
  orderBy?: Prisma.ScheduleItemOrderByWithAggregationInput | Prisma.ScheduleItemOrderByWithAggregationInput[]
  by: Prisma.ScheduleItemScalarFieldEnum[] | Prisma.ScheduleItemScalarFieldEnum
  having?: Prisma.ScheduleItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ScheduleItemCountAggregateInputType | true
  _avg?: ScheduleItemAvgAggregateInputType
  _sum?: ScheduleItemSumAggregateInputType
  _min?: ScheduleItemMinAggregateInputType
  _max?: ScheduleItemMaxAggregateInputType
}

export type ScheduleItemGroupByOutputType = {
  id: number
  workPlanId: number
  axisGoal: string
  actionStep: string
  indicator: string
  responsible: string
  startDate: Date
  endDate: Date
  status: $Enums.ScheduleStatus
  _count: ScheduleItemCountAggregateOutputType | null
  _avg: ScheduleItemAvgAggregateOutputType | null
  _sum: ScheduleItemSumAggregateOutputType | null
  _min: ScheduleItemMinAggregateOutputType | null
  _max: ScheduleItemMaxAggregateOutputType | null
}

type GetScheduleItemGroupByPayload<T extends ScheduleItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ScheduleItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ScheduleItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ScheduleItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ScheduleItemGroupByOutputType[P]>
      }
    >
  >



export type ScheduleItemWhereInput = {
  AND?: Prisma.ScheduleItemWhereInput | Prisma.ScheduleItemWhereInput[]
  OR?: Prisma.ScheduleItemWhereInput[]
  NOT?: Prisma.ScheduleItemWhereInput | Prisma.ScheduleItemWhereInput[]
  id?: Prisma.IntFilter<"ScheduleItem"> | number
  workPlanId?: Prisma.IntFilter<"ScheduleItem"> | number
  axisGoal?: Prisma.StringFilter<"ScheduleItem"> | string
  actionStep?: Prisma.StringFilter<"ScheduleItem"> | string
  indicator?: Prisma.StringFilter<"ScheduleItem"> | string
  responsible?: Prisma.StringFilter<"ScheduleItem"> | string
  startDate?: Prisma.DateTimeFilter<"ScheduleItem"> | Date | string
  endDate?: Prisma.DateTimeFilter<"ScheduleItem"> | Date | string
  status?: Prisma.EnumScheduleStatusFilter<"ScheduleItem"> | $Enums.ScheduleStatus
  workPlan?: Prisma.XOR<Prisma.WorkPlanScalarRelationFilter, Prisma.WorkPlanWhereInput>
}

export type ScheduleItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  axisGoal?: Prisma.SortOrder
  actionStep?: Prisma.SortOrder
  indicator?: Prisma.SortOrder
  responsible?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  workPlan?: Prisma.WorkPlanOrderByWithRelationInput
}

export type ScheduleItemWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ScheduleItemWhereInput | Prisma.ScheduleItemWhereInput[]
  OR?: Prisma.ScheduleItemWhereInput[]
  NOT?: Prisma.ScheduleItemWhereInput | Prisma.ScheduleItemWhereInput[]
  workPlanId?: Prisma.IntFilter<"ScheduleItem"> | number
  axisGoal?: Prisma.StringFilter<"ScheduleItem"> | string
  actionStep?: Prisma.StringFilter<"ScheduleItem"> | string
  indicator?: Prisma.StringFilter<"ScheduleItem"> | string
  responsible?: Prisma.StringFilter<"ScheduleItem"> | string
  startDate?: Prisma.DateTimeFilter<"ScheduleItem"> | Date | string
  endDate?: Prisma.DateTimeFilter<"ScheduleItem"> | Date | string
  status?: Prisma.EnumScheduleStatusFilter<"ScheduleItem"> | $Enums.ScheduleStatus
  workPlan?: Prisma.XOR<Prisma.WorkPlanScalarRelationFilter, Prisma.WorkPlanWhereInput>
}, "id">

export type ScheduleItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  axisGoal?: Prisma.SortOrder
  actionStep?: Prisma.SortOrder
  indicator?: Prisma.SortOrder
  responsible?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.ScheduleItemCountOrderByAggregateInput
  _avg?: Prisma.ScheduleItemAvgOrderByAggregateInput
  _max?: Prisma.ScheduleItemMaxOrderByAggregateInput
  _min?: Prisma.ScheduleItemMinOrderByAggregateInput
  _sum?: Prisma.ScheduleItemSumOrderByAggregateInput
}

export type ScheduleItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.ScheduleItemScalarWhereWithAggregatesInput | Prisma.ScheduleItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.ScheduleItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ScheduleItemScalarWhereWithAggregatesInput | Prisma.ScheduleItemScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ScheduleItem"> | number
  workPlanId?: Prisma.IntWithAggregatesFilter<"ScheduleItem"> | number
  axisGoal?: Prisma.StringWithAggregatesFilter<"ScheduleItem"> | string
  actionStep?: Prisma.StringWithAggregatesFilter<"ScheduleItem"> | string
  indicator?: Prisma.StringWithAggregatesFilter<"ScheduleItem"> | string
  responsible?: Prisma.StringWithAggregatesFilter<"ScheduleItem"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"ScheduleItem"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"ScheduleItem"> | Date | string
  status?: Prisma.EnumScheduleStatusWithAggregatesFilter<"ScheduleItem"> | $Enums.ScheduleStatus
}

export type ScheduleItemCreateInput = {
  axisGoal: string
  actionStep: string
  indicator: string
  responsible: string
  startDate: Date | string
  endDate: Date | string
  status?: $Enums.ScheduleStatus
  workPlan: Prisma.WorkPlanCreateNestedOneWithoutScheduleInput
}

export type ScheduleItemUncheckedCreateInput = {
  id?: number
  workPlanId: number
  axisGoal: string
  actionStep: string
  indicator: string
  responsible: string
  startDate: Date | string
  endDate: Date | string
  status?: $Enums.ScheduleStatus
}

export type ScheduleItemUpdateInput = {
  axisGoal?: Prisma.StringFieldUpdateOperationsInput | string
  actionStep?: Prisma.StringFieldUpdateOperationsInput | string
  indicator?: Prisma.StringFieldUpdateOperationsInput | string
  responsible?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumScheduleStatusFieldUpdateOperationsInput | $Enums.ScheduleStatus
  workPlan?: Prisma.WorkPlanUpdateOneRequiredWithoutScheduleNestedInput
}

export type ScheduleItemUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  workPlanId?: Prisma.IntFieldUpdateOperationsInput | number
  axisGoal?: Prisma.StringFieldUpdateOperationsInput | string
  actionStep?: Prisma.StringFieldUpdateOperationsInput | string
  indicator?: Prisma.StringFieldUpdateOperationsInput | string
  responsible?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumScheduleStatusFieldUpdateOperationsInput | $Enums.ScheduleStatus
}

export type ScheduleItemCreateManyInput = {
  id?: number
  workPlanId: number
  axisGoal: string
  actionStep: string
  indicator: string
  responsible: string
  startDate: Date | string
  endDate: Date | string
  status?: $Enums.ScheduleStatus
}

export type ScheduleItemUpdateManyMutationInput = {
  axisGoal?: Prisma.StringFieldUpdateOperationsInput | string
  actionStep?: Prisma.StringFieldUpdateOperationsInput | string
  indicator?: Prisma.StringFieldUpdateOperationsInput | string
  responsible?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumScheduleStatusFieldUpdateOperationsInput | $Enums.ScheduleStatus
}

export type ScheduleItemUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  workPlanId?: Prisma.IntFieldUpdateOperationsInput | number
  axisGoal?: Prisma.StringFieldUpdateOperationsInput | string
  actionStep?: Prisma.StringFieldUpdateOperationsInput | string
  indicator?: Prisma.StringFieldUpdateOperationsInput | string
  responsible?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumScheduleStatusFieldUpdateOperationsInput | $Enums.ScheduleStatus
}

export type ScheduleItemListRelationFilter = {
  every?: Prisma.ScheduleItemWhereInput
  some?: Prisma.ScheduleItemWhereInput
  none?: Prisma.ScheduleItemWhereInput
}

export type ScheduleItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ScheduleItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  axisGoal?: Prisma.SortOrder
  actionStep?: Prisma.SortOrder
  indicator?: Prisma.SortOrder
  responsible?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ScheduleItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
}

export type ScheduleItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  axisGoal?: Prisma.SortOrder
  actionStep?: Prisma.SortOrder
  indicator?: Prisma.SortOrder
  responsible?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ScheduleItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
  axisGoal?: Prisma.SortOrder
  actionStep?: Prisma.SortOrder
  indicator?: Prisma.SortOrder
  responsible?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ScheduleItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workPlanId?: Prisma.SortOrder
}

export type ScheduleItemCreateNestedManyWithoutWorkPlanInput = {
  create?: Prisma.XOR<Prisma.ScheduleItemCreateWithoutWorkPlanInput, Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput> | Prisma.ScheduleItemCreateWithoutWorkPlanInput[] | Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput[]
  connectOrCreate?: Prisma.ScheduleItemCreateOrConnectWithoutWorkPlanInput | Prisma.ScheduleItemCreateOrConnectWithoutWorkPlanInput[]
  createMany?: Prisma.ScheduleItemCreateManyWorkPlanInputEnvelope
  connect?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
}

export type ScheduleItemUncheckedCreateNestedManyWithoutWorkPlanInput = {
  create?: Prisma.XOR<Prisma.ScheduleItemCreateWithoutWorkPlanInput, Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput> | Prisma.ScheduleItemCreateWithoutWorkPlanInput[] | Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput[]
  connectOrCreate?: Prisma.ScheduleItemCreateOrConnectWithoutWorkPlanInput | Prisma.ScheduleItemCreateOrConnectWithoutWorkPlanInput[]
  createMany?: Prisma.ScheduleItemCreateManyWorkPlanInputEnvelope
  connect?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
}

export type ScheduleItemUpdateManyWithoutWorkPlanNestedInput = {
  create?: Prisma.XOR<Prisma.ScheduleItemCreateWithoutWorkPlanInput, Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput> | Prisma.ScheduleItemCreateWithoutWorkPlanInput[] | Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput[]
  connectOrCreate?: Prisma.ScheduleItemCreateOrConnectWithoutWorkPlanInput | Prisma.ScheduleItemCreateOrConnectWithoutWorkPlanInput[]
  upsert?: Prisma.ScheduleItemUpsertWithWhereUniqueWithoutWorkPlanInput | Prisma.ScheduleItemUpsertWithWhereUniqueWithoutWorkPlanInput[]
  createMany?: Prisma.ScheduleItemCreateManyWorkPlanInputEnvelope
  set?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
  disconnect?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
  delete?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
  connect?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
  update?: Prisma.ScheduleItemUpdateWithWhereUniqueWithoutWorkPlanInput | Prisma.ScheduleItemUpdateWithWhereUniqueWithoutWorkPlanInput[]
  updateMany?: Prisma.ScheduleItemUpdateManyWithWhereWithoutWorkPlanInput | Prisma.ScheduleItemUpdateManyWithWhereWithoutWorkPlanInput[]
  deleteMany?: Prisma.ScheduleItemScalarWhereInput | Prisma.ScheduleItemScalarWhereInput[]
}

export type ScheduleItemUncheckedUpdateManyWithoutWorkPlanNestedInput = {
  create?: Prisma.XOR<Prisma.ScheduleItemCreateWithoutWorkPlanInput, Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput> | Prisma.ScheduleItemCreateWithoutWorkPlanInput[] | Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput[]
  connectOrCreate?: Prisma.ScheduleItemCreateOrConnectWithoutWorkPlanInput | Prisma.ScheduleItemCreateOrConnectWithoutWorkPlanInput[]
  upsert?: Prisma.ScheduleItemUpsertWithWhereUniqueWithoutWorkPlanInput | Prisma.ScheduleItemUpsertWithWhereUniqueWithoutWorkPlanInput[]
  createMany?: Prisma.ScheduleItemCreateManyWorkPlanInputEnvelope
  set?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
  disconnect?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
  delete?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
  connect?: Prisma.ScheduleItemWhereUniqueInput | Prisma.ScheduleItemWhereUniqueInput[]
  update?: Prisma.ScheduleItemUpdateWithWhereUniqueWithoutWorkPlanInput | Prisma.ScheduleItemUpdateWithWhereUniqueWithoutWorkPlanInput[]
  updateMany?: Prisma.ScheduleItemUpdateManyWithWhereWithoutWorkPlanInput | Prisma.ScheduleItemUpdateManyWithWhereWithoutWorkPlanInput[]
  deleteMany?: Prisma.ScheduleItemScalarWhereInput | Prisma.ScheduleItemScalarWhereInput[]
}

export type EnumScheduleStatusFieldUpdateOperationsInput = {
  set?: $Enums.ScheduleStatus
}

export type ScheduleItemCreateWithoutWorkPlanInput = {
  axisGoal: string
  actionStep: string
  indicator: string
  responsible: string
  startDate: Date | string
  endDate: Date | string
  status?: $Enums.ScheduleStatus
}

export type ScheduleItemUncheckedCreateWithoutWorkPlanInput = {
  id?: number
  axisGoal: string
  actionStep: string
  indicator: string
  responsible: string
  startDate: Date | string
  endDate: Date | string
  status?: $Enums.ScheduleStatus
}

export type ScheduleItemCreateOrConnectWithoutWorkPlanInput = {
  where: Prisma.ScheduleItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ScheduleItemCreateWithoutWorkPlanInput, Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput>
}

export type ScheduleItemCreateManyWorkPlanInputEnvelope = {
  data: Prisma.ScheduleItemCreateManyWorkPlanInput | Prisma.ScheduleItemCreateManyWorkPlanInput[]
  skipDuplicates?: boolean
}

export type ScheduleItemUpsertWithWhereUniqueWithoutWorkPlanInput = {
  where: Prisma.ScheduleItemWhereUniqueInput
  update: Prisma.XOR<Prisma.ScheduleItemUpdateWithoutWorkPlanInput, Prisma.ScheduleItemUncheckedUpdateWithoutWorkPlanInput>
  create: Prisma.XOR<Prisma.ScheduleItemCreateWithoutWorkPlanInput, Prisma.ScheduleItemUncheckedCreateWithoutWorkPlanInput>
}

export type ScheduleItemUpdateWithWhereUniqueWithoutWorkPlanInput = {
  where: Prisma.ScheduleItemWhereUniqueInput
  data: Prisma.XOR<Prisma.ScheduleItemUpdateWithoutWorkPlanInput, Prisma.ScheduleItemUncheckedUpdateWithoutWorkPlanInput>
}

export type ScheduleItemUpdateManyWithWhereWithoutWorkPlanInput = {
  where: Prisma.ScheduleItemScalarWhereInput
  data: Prisma.XOR<Prisma.ScheduleItemUpdateManyMutationInput, Prisma.ScheduleItemUncheckedUpdateManyWithoutWorkPlanInput>
}

export type ScheduleItemScalarWhereInput = {
  AND?: Prisma.ScheduleItemScalarWhereInput | Prisma.ScheduleItemScalarWhereInput[]
  OR?: Prisma.ScheduleItemScalarWhereInput[]
  NOT?: Prisma.ScheduleItemScalarWhereInput | Prisma.ScheduleItemScalarWhereInput[]
  id?: Prisma.IntFilter<"ScheduleItem"> | number
  workPlanId?: Prisma.IntFilter<"ScheduleItem"> | number
  axisGoal?: Prisma.StringFilter<"ScheduleItem"> | string
  actionStep?: Prisma.StringFilter<"ScheduleItem"> | string
  indicator?: Prisma.StringFilter<"ScheduleItem"> | string
  responsible?: Prisma.StringFilter<"ScheduleItem"> | string
  startDate?: Prisma.DateTimeFilter<"ScheduleItem"> | Date | string
  endDate?: Prisma.DateTimeFilter<"ScheduleItem"> | Date | string
  status?: Prisma.EnumScheduleStatusFilter<"ScheduleItem"> | $Enums.ScheduleStatus
}

export type ScheduleItemCreateManyWorkPlanInput = {
  id?: number
  axisGoal: string
  actionStep: string
  indicator: string
  responsible: string
  startDate: Date | string
  endDate: Date | string
  status?: $Enums.ScheduleStatus
}

export type ScheduleItemUpdateWithoutWorkPlanInput = {
  axisGoal?: Prisma.StringFieldUpdateOperationsInput | string
  actionStep?: Prisma.StringFieldUpdateOperationsInput | string
  indicator?: Prisma.StringFieldUpdateOperationsInput | string
  responsible?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumScheduleStatusFieldUpdateOperationsInput | $Enums.ScheduleStatus
}

export type ScheduleItemUncheckedUpdateWithoutWorkPlanInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  axisGoal?: Prisma.StringFieldUpdateOperationsInput | string
  actionStep?: Prisma.StringFieldUpdateOperationsInput | string
  indicator?: Prisma.StringFieldUpdateOperationsInput | string
  responsible?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumScheduleStatusFieldUpdateOperationsInput | $Enums.ScheduleStatus
}

export type ScheduleItemUncheckedUpdateManyWithoutWorkPlanInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  axisGoal?: Prisma.StringFieldUpdateOperationsInput | string
  actionStep?: Prisma.StringFieldUpdateOperationsInput | string
  indicator?: Prisma.StringFieldUpdateOperationsInput | string
  responsible?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumScheduleStatusFieldUpdateOperationsInput | $Enums.ScheduleStatus
}



export type ScheduleItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workPlanId?: boolean
  axisGoal?: boolean
  actionStep?: boolean
  indicator?: boolean
  responsible?: boolean
  startDate?: boolean
  endDate?: boolean
  status?: boolean
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["scheduleItem"]>

export type ScheduleItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workPlanId?: boolean
  axisGoal?: boolean
  actionStep?: boolean
  indicator?: boolean
  responsible?: boolean
  startDate?: boolean
  endDate?: boolean
  status?: boolean
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["scheduleItem"]>

export type ScheduleItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workPlanId?: boolean
  axisGoal?: boolean
  actionStep?: boolean
  indicator?: boolean
  responsible?: boolean
  startDate?: boolean
  endDate?: boolean
  status?: boolean
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["scheduleItem"]>

export type ScheduleItemSelectScalar = {
  id?: boolean
  workPlanId?: boolean
  axisGoal?: boolean
  actionStep?: boolean
  indicator?: boolean
  responsible?: boolean
  startDate?: boolean
  endDate?: boolean
  status?: boolean
}

export type ScheduleItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workPlanId" | "axisGoal" | "actionStep" | "indicator" | "responsible" | "startDate" | "endDate" | "status", ExtArgs["result"]["scheduleItem"]>
export type ScheduleItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
}
export type ScheduleItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
}
export type ScheduleItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workPlan?: boolean | Prisma.WorkPlanDefaultArgs<ExtArgs>
}

export type $ScheduleItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ScheduleItem"
  objects: {
    workPlan: Prisma.$WorkPlanPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    workPlanId: number
    axisGoal: string
    actionStep: string
    indicator: string
    responsible: string
    startDate: Date
    endDate: Date
    status: $Enums.ScheduleStatus
  }, ExtArgs["result"]["scheduleItem"]>
  composites: {}
}

export type ScheduleItemGetPayload<S extends boolean | null | undefined | ScheduleItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload, S>

export type ScheduleItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ScheduleItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ScheduleItemCountAggregateInputType | true
  }

export interface ScheduleItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ScheduleItem'], meta: { name: 'ScheduleItem' } }
  /**
   * Find zero or one ScheduleItem that matches the filter.
   * @param {ScheduleItemFindUniqueArgs} args - Arguments to find a ScheduleItem
   * @example
   * // Get one ScheduleItem
   * const scheduleItem = await prisma.scheduleItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ScheduleItemFindUniqueArgs>(args: Prisma.SelectSubset<T, ScheduleItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ScheduleItemClient<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ScheduleItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ScheduleItemFindUniqueOrThrowArgs} args - Arguments to find a ScheduleItem
   * @example
   * // Get one ScheduleItem
   * const scheduleItem = await prisma.scheduleItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ScheduleItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ScheduleItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ScheduleItemClient<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ScheduleItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduleItemFindFirstArgs} args - Arguments to find a ScheduleItem
   * @example
   * // Get one ScheduleItem
   * const scheduleItem = await prisma.scheduleItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ScheduleItemFindFirstArgs>(args?: Prisma.SelectSubset<T, ScheduleItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__ScheduleItemClient<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ScheduleItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduleItemFindFirstOrThrowArgs} args - Arguments to find a ScheduleItem
   * @example
   * // Get one ScheduleItem
   * const scheduleItem = await prisma.scheduleItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ScheduleItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ScheduleItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ScheduleItemClient<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ScheduleItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduleItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ScheduleItems
   * const scheduleItems = await prisma.scheduleItem.findMany()
   * 
   * // Get first 10 ScheduleItems
   * const scheduleItems = await prisma.scheduleItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const scheduleItemWithIdOnly = await prisma.scheduleItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ScheduleItemFindManyArgs>(args?: Prisma.SelectSubset<T, ScheduleItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ScheduleItem.
   * @param {ScheduleItemCreateArgs} args - Arguments to create a ScheduleItem.
   * @example
   * // Create one ScheduleItem
   * const ScheduleItem = await prisma.scheduleItem.create({
   *   data: {
   *     // ... data to create a ScheduleItem
   *   }
   * })
   * 
   */
  create<T extends ScheduleItemCreateArgs>(args: Prisma.SelectSubset<T, ScheduleItemCreateArgs<ExtArgs>>): Prisma.Prisma__ScheduleItemClient<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ScheduleItems.
   * @param {ScheduleItemCreateManyArgs} args - Arguments to create many ScheduleItems.
   * @example
   * // Create many ScheduleItems
   * const scheduleItem = await prisma.scheduleItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ScheduleItemCreateManyArgs>(args?: Prisma.SelectSubset<T, ScheduleItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ScheduleItems and returns the data saved in the database.
   * @param {ScheduleItemCreateManyAndReturnArgs} args - Arguments to create many ScheduleItems.
   * @example
   * // Create many ScheduleItems
   * const scheduleItem = await prisma.scheduleItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ScheduleItems and only return the `id`
   * const scheduleItemWithIdOnly = await prisma.scheduleItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ScheduleItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ScheduleItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ScheduleItem.
   * @param {ScheduleItemDeleteArgs} args - Arguments to delete one ScheduleItem.
   * @example
   * // Delete one ScheduleItem
   * const ScheduleItem = await prisma.scheduleItem.delete({
   *   where: {
   *     // ... filter to delete one ScheduleItem
   *   }
   * })
   * 
   */
  delete<T extends ScheduleItemDeleteArgs>(args: Prisma.SelectSubset<T, ScheduleItemDeleteArgs<ExtArgs>>): Prisma.Prisma__ScheduleItemClient<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ScheduleItem.
   * @param {ScheduleItemUpdateArgs} args - Arguments to update one ScheduleItem.
   * @example
   * // Update one ScheduleItem
   * const scheduleItem = await prisma.scheduleItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ScheduleItemUpdateArgs>(args: Prisma.SelectSubset<T, ScheduleItemUpdateArgs<ExtArgs>>): Prisma.Prisma__ScheduleItemClient<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ScheduleItems.
   * @param {ScheduleItemDeleteManyArgs} args - Arguments to filter ScheduleItems to delete.
   * @example
   * // Delete a few ScheduleItems
   * const { count } = await prisma.scheduleItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ScheduleItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, ScheduleItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ScheduleItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduleItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ScheduleItems
   * const scheduleItem = await prisma.scheduleItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ScheduleItemUpdateManyArgs>(args: Prisma.SelectSubset<T, ScheduleItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ScheduleItems and returns the data updated in the database.
   * @param {ScheduleItemUpdateManyAndReturnArgs} args - Arguments to update many ScheduleItems.
   * @example
   * // Update many ScheduleItems
   * const scheduleItem = await prisma.scheduleItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ScheduleItems and only return the `id`
   * const scheduleItemWithIdOnly = await prisma.scheduleItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ScheduleItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ScheduleItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ScheduleItem.
   * @param {ScheduleItemUpsertArgs} args - Arguments to update or create a ScheduleItem.
   * @example
   * // Update or create a ScheduleItem
   * const scheduleItem = await prisma.scheduleItem.upsert({
   *   create: {
   *     // ... data to create a ScheduleItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ScheduleItem we want to update
   *   }
   * })
   */
  upsert<T extends ScheduleItemUpsertArgs>(args: Prisma.SelectSubset<T, ScheduleItemUpsertArgs<ExtArgs>>): Prisma.Prisma__ScheduleItemClient<runtime.Types.Result.GetResult<Prisma.$ScheduleItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ScheduleItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduleItemCountArgs} args - Arguments to filter ScheduleItems to count.
   * @example
   * // Count the number of ScheduleItems
   * const count = await prisma.scheduleItem.count({
   *   where: {
   *     // ... the filter for the ScheduleItems we want to count
   *   }
   * })
  **/
  count<T extends ScheduleItemCountArgs>(
    args?: Prisma.Subset<T, ScheduleItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ScheduleItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ScheduleItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduleItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ScheduleItemAggregateArgs>(args: Prisma.Subset<T, ScheduleItemAggregateArgs>): Prisma.PrismaPromise<GetScheduleItemAggregateType<T>>

  /**
   * Group by ScheduleItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduleItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ScheduleItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ScheduleItemGroupByArgs['orderBy'] }
      : { orderBy?: ScheduleItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ScheduleItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetScheduleItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ScheduleItem model
 */
readonly fields: ScheduleItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ScheduleItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ScheduleItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workPlan<T extends Prisma.WorkPlanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkPlanDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkPlanClient<runtime.Types.Result.GetResult<Prisma.$WorkPlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ScheduleItem model
 */
export interface ScheduleItemFieldRefs {
  readonly id: Prisma.FieldRef<"ScheduleItem", 'Int'>
  readonly workPlanId: Prisma.FieldRef<"ScheduleItem", 'Int'>
  readonly axisGoal: Prisma.FieldRef<"ScheduleItem", 'String'>
  readonly actionStep: Prisma.FieldRef<"ScheduleItem", 'String'>
  readonly indicator: Prisma.FieldRef<"ScheduleItem", 'String'>
  readonly responsible: Prisma.FieldRef<"ScheduleItem", 'String'>
  readonly startDate: Prisma.FieldRef<"ScheduleItem", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"ScheduleItem", 'DateTime'>
  readonly status: Prisma.FieldRef<"ScheduleItem", 'ScheduleStatus'>
}
    

// Custom InputTypes
/**
 * ScheduleItem findUnique
 */
export type ScheduleItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * Filter, which ScheduleItem to fetch.
   */
  where: Prisma.ScheduleItemWhereUniqueInput
}

/**
 * ScheduleItem findUniqueOrThrow
 */
export type ScheduleItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * Filter, which ScheduleItem to fetch.
   */
  where: Prisma.ScheduleItemWhereUniqueInput
}

/**
 * ScheduleItem findFirst
 */
export type ScheduleItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * Filter, which ScheduleItem to fetch.
   */
  where?: Prisma.ScheduleItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduleItems to fetch.
   */
  orderBy?: Prisma.ScheduleItemOrderByWithRelationInput | Prisma.ScheduleItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ScheduleItems.
   */
  cursor?: Prisma.ScheduleItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduleItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduleItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ScheduleItems.
   */
  distinct?: Prisma.ScheduleItemScalarFieldEnum | Prisma.ScheduleItemScalarFieldEnum[]
}

/**
 * ScheduleItem findFirstOrThrow
 */
export type ScheduleItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * Filter, which ScheduleItem to fetch.
   */
  where?: Prisma.ScheduleItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduleItems to fetch.
   */
  orderBy?: Prisma.ScheduleItemOrderByWithRelationInput | Prisma.ScheduleItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ScheduleItems.
   */
  cursor?: Prisma.ScheduleItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduleItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduleItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ScheduleItems.
   */
  distinct?: Prisma.ScheduleItemScalarFieldEnum | Prisma.ScheduleItemScalarFieldEnum[]
}

/**
 * ScheduleItem findMany
 */
export type ScheduleItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * Filter, which ScheduleItems to fetch.
   */
  where?: Prisma.ScheduleItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduleItems to fetch.
   */
  orderBy?: Prisma.ScheduleItemOrderByWithRelationInput | Prisma.ScheduleItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ScheduleItems.
   */
  cursor?: Prisma.ScheduleItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduleItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduleItems.
   */
  skip?: number
  distinct?: Prisma.ScheduleItemScalarFieldEnum | Prisma.ScheduleItemScalarFieldEnum[]
}

/**
 * ScheduleItem create
 */
export type ScheduleItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * The data needed to create a ScheduleItem.
   */
  data: Prisma.XOR<Prisma.ScheduleItemCreateInput, Prisma.ScheduleItemUncheckedCreateInput>
}

/**
 * ScheduleItem createMany
 */
export type ScheduleItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ScheduleItems.
   */
  data: Prisma.ScheduleItemCreateManyInput | Prisma.ScheduleItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ScheduleItem createManyAndReturn
 */
export type ScheduleItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * The data used to create many ScheduleItems.
   */
  data: Prisma.ScheduleItemCreateManyInput | Prisma.ScheduleItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ScheduleItem update
 */
export type ScheduleItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * The data needed to update a ScheduleItem.
   */
  data: Prisma.XOR<Prisma.ScheduleItemUpdateInput, Prisma.ScheduleItemUncheckedUpdateInput>
  /**
   * Choose, which ScheduleItem to update.
   */
  where: Prisma.ScheduleItemWhereUniqueInput
}

/**
 * ScheduleItem updateMany
 */
export type ScheduleItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ScheduleItems.
   */
  data: Prisma.XOR<Prisma.ScheduleItemUpdateManyMutationInput, Prisma.ScheduleItemUncheckedUpdateManyInput>
  /**
   * Filter which ScheduleItems to update
   */
  where?: Prisma.ScheduleItemWhereInput
  /**
   * Limit how many ScheduleItems to update.
   */
  limit?: number
}

/**
 * ScheduleItem updateManyAndReturn
 */
export type ScheduleItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * The data used to update ScheduleItems.
   */
  data: Prisma.XOR<Prisma.ScheduleItemUpdateManyMutationInput, Prisma.ScheduleItemUncheckedUpdateManyInput>
  /**
   * Filter which ScheduleItems to update
   */
  where?: Prisma.ScheduleItemWhereInput
  /**
   * Limit how many ScheduleItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ScheduleItem upsert
 */
export type ScheduleItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * The filter to search for the ScheduleItem to update in case it exists.
   */
  where: Prisma.ScheduleItemWhereUniqueInput
  /**
   * In case the ScheduleItem found by the `where` argument doesn't exist, create a new ScheduleItem with this data.
   */
  create: Prisma.XOR<Prisma.ScheduleItemCreateInput, Prisma.ScheduleItemUncheckedCreateInput>
  /**
   * In case the ScheduleItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ScheduleItemUpdateInput, Prisma.ScheduleItemUncheckedUpdateInput>
}

/**
 * ScheduleItem delete
 */
export type ScheduleItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
  /**
   * Filter which ScheduleItem to delete.
   */
  where: Prisma.ScheduleItemWhereUniqueInput
}

/**
 * ScheduleItem deleteMany
 */
export type ScheduleItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ScheduleItems to delete
   */
  where?: Prisma.ScheduleItemWhereInput
  /**
   * Limit how many ScheduleItems to delete.
   */
  limit?: number
}

/**
 * ScheduleItem without action
 */
export type ScheduleItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduleItem
   */
  select?: Prisma.ScheduleItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduleItem
   */
  omit?: Prisma.ScheduleItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScheduleItemInclude<ExtArgs> | null
}
